import type { WordModel } from "~/models";

export const ABOUT_SIZE_BEAUTY: WordModel[] = [
    {
        id: 1,
        korean: "큰",
        read: "keun",
        english: "big",
        lao: "ໃຫຍ່",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "큰 집",
                read: "keun jip",
                english: "big house",
                lao: "ເຮືອນໃຫຍ່",
            },
        ],
    },
    {
        id: 2,
        korean: "좋은",
        read: "joeun",
        english: "good",
        lao: "ດີ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "좋은 날씨",
                read: "joeun nalssi",
                english: "good weather",
                lao: "ອາກາດດີ",
            },
        ],
    },
    {
        id: 3,
        korean: "나쁜",
        read: "nappeun",
        english: "bad",
        lao: "ເລວ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "나쁜 꿈",
                read: "nappeun kkum",
                english: "bad dream",
                lao: "ຝັນເລວ",
            },
        ],
    },
    {
        id: 4,
        korean: "아름다운",
        read: "areumdaun",
        english: "beautiful",
        lao: "ງາມ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "아름다운 꽃",
                read: "areumdaun kkot",
                english: "beautiful flower",
                lao: "ດອກໄມ້ທີ່ງາມ",
            },
        ],
    },
    {
        id: 5,
        korean: "쉬운",
        read: "swiun",
        english: "easy",
        lao: "ງ່າຍ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "쉬운 문제",
                read: "swiun munje",
                english: "easy problem",
                lao: "ບັນຫາທີ່ງ່າຍ",
            },
        ],
    },
    {
        id: 6,
        korean: "작은",
        read: "jageun",
        english: "small",
        lao: "ນ້ອຍ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "작은 집",
                read: "jageun jip",
                english: "small house",
                lao: "ເຮືອນນ້ອຍ",
            },
        ],
    },
    {
        id: 7,
        korean: "차가운",
        read: "chagaun",
        english: "cold",
        lao: "ເຢັນ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "차가운 물",
                read: "chagaun mul",
                english: "cold water",
                lao: "ນ້ຳເຢັນ",
            },
        ],
    },
    {
        id: 8,
        korean: "더운",
        read: "deoun",
        english: "hot",
        lao: "ຮ້ອນ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "더운 날씨",
                read: "deoun nalssi",
                english: "hot weather",
                lao: "ອາກາດຮ້ອນ",
            },
        ],
    },
    {
        id: 9,
        korean: "중요한",
        read: "jungyohan",
        english: "important",
        lao: "ສຳຄັນ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "중요한 회의",
                read: "jungyohan hoeui",
                english: "important meeting",
                lao: "ປະຊຸມສຳຄັນ",
            },
        ],
    },
    {
        id: 10,
        korean: "친절한",
        read: "chinjeoran",
        english: "kind",
        lao: "ມີນ້ຳໃຈ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "친절한 사람",
                read: "chinjeoran saram",
                english: "kind person",
                lao: "ຄົນທີ່ມີນ້ຳໃຈ",
            },
        ],
    },
    {
        id: 11,
        korean: "강한",
        read: "ganghan",
        english: "strong",
        lao: "ແຂງແຮງ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "강한 바람",
                read: "ganghan baram",
                english: "strong wind",
                lao: "ລົມແຮງ",
            },
        ],
    },
    {
        id: 12,
        korean: "늦은",
        read: "neujeun",
        english: "late",
        lao: "ຊ້າ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "늦은 밤",
                read: "neujeun bam",
                english: "late night",
                lao: "ກາງຄືນດືກ",
            },
        ],
    },
    {
        id: 13,
        korean: "긴",
        read: "gin",
        english: "long",
        lao: "ຍາວ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "긴 거리",
                read: "gin geori",
                english: "long distance",
                lao: "ໄລຍະທາງຍາວ",
            },
        ],
    },
    {
        id: 14,
        korean: "좁은",
        read: "jobeun",
        english: "narrow",
        lao: "ແຄບ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "좁은 길",
                read: "jobeun gil",
                english: "narrow path",
                lao: "ທາງແຄບ",
            },
        ],
    },
    {
        id: 15,
        korean: "짧은",
        read: "jjalbeun",
        english: "short",
        lao: "ສັ້ນ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "짧은 시간",
                read: "jjalbeun sigan",
                english: "short time",
                lao: "ເວລາສັ້ນ",
            },
        ],
    },
    {
        id: 16,
        korean: "넓은",
        read: "neolbeun",
        english: "wide",
        lao: "ກວ້າງ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "넓은 길",
                read: "neolbeun gil",
                english: "wide road",
                lao: "ທາງກວ້າງ",
            },
        ],
    },
    {
        id: 17,
        korean: "생기 넘치는",
        read: "saenggi neomchineun",
        english: "lively",
        lao: "ມີຊີວິດຊີວາ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "생기 넘치는 음악",
                read: "saenggi neomchineun eumak",
                english: "lively music",
                lao: "ດົນຕີທີ່ມີຊີວິດຊີວາ",
            },
        ],
    },
    {
        id: 18,
        korean: "낮은",
        read: "najeun",
        english: "low",
        lao: "ຕໍ່າ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "낮은 산",
                read: "najeun san",
                english: "low mountain",
                lao: "ພູຕໍ່າ",
            },
        ],
    },
    {
        id: 19,
        korean: "높은",
        read: "nopeun",
        english: "high",
        lao: "ສູງ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "높은 빌딩",
                read: "nopeun bilding",
                english: "high building",
                lao: "ອາຄານສູງ",
            },
        ],
    },
    {
        id: 20,
        korean: "유명한",
        read: "yumyeonghan",
        english: "famous",
        lao: "ມີຊື່ສຽງ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "유명한 배우",
                read: "yumyeonghan bae-u",
                english: "famous actor",
                lao: "ນັກສະແດງທີ່ມີຊື່ສຽງ",
            },
        ],
    },
    {
        id: 21,
        korean: "조용한",
        read: "joyonghan",
        english: "quiet",
        lao: "ເງົາ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "조용한 방",
                read: "joyonghan bang",
                english: "quiet room",
                lao: "ຫ້ອງທີ່ເງົາ",
            },
        ],
    },
    {
        id: 22,
        korean: "동일하다",
        read: "dongilhada",
        english: "same",
        lao: "ເຫມືອນກັນ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "동일한 크기",
                read: "dongilhan keugi",
                english: "same size",
                lao: "ຂະໜາດເຫມືອນກັນ",
            },
        ],
    },
    {
        id: 23,
        korean: "작다",
        read: "jakda",
        english: "little",
        lao: "ໜ້ອຍ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "작은 아이",
                read: "jageun ai",
                english: "little child",
                lao: "ເດັກນ້ອຍ",
            },
        ],
    },
    {
        id: 24,
        korean: "다르다",
        read: "dareuda",
        english: "different",
        lao: "ແຕກຕ່າງ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "다른 색깔",
                read: "dareun saekkkal",
                english: "different color",
                lao: "ສີທີ່ແຕກຕ່າງ",
            },
        ],
    },
    {
        id: 25,
        korean: "이르다",
        read: "ireuda",
        english: "early",
        lao: "ເຊົ້າ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "이른 아침",
                read: "ireun achim",
                english: "early morning",
                lao: "ເຊົ້າເຊົ້າ",
            },
        ],
    },
    {
        id: 26,
        korean: "많다",
        read: "manta",
        english: "great",
        lao: "ໃຫຍ່",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "많은 양",
                read: "maneun yang",
                english: "great amount",
                lao: "ຈຳນວນໃຫຍ່",
            },
        ],
    },
    {
        id: 27,
        korean: "새롭다",
        read: "saeropda",
        english: "new",
        lao: "ໃໝ່",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "새로운 아이디어",
                read: "saeroun aidi-eo",
                english: "new idea",
                lao: "ຄວາມຄິດໃໝ່",
            },
        ],
    },
    {
        id: 28,
        korean: "젊다",
        read: "jeomda",
        english: "young",
        lao: "ໜຸ່ມ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "젊은 사람",
                read: "jeom-eun saram",
                english: "young person",
                lao: "ຄົນໜຸ່ມ",
            },
        ],
    },
    {
        id: 29,
        korean: "오래되다",
        read: "oraedoeda",
        english: "old",
        lao: "ເຖົ້າ",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "오래된 집",
                read: "oraedoen jip",
                english: "old house",
                lao: "ເຮືອນເຖົ້າ",
            },
        ],
    },
    {
        id: 30,
        korean: "크다",
        read: "keuda",
        english: "large",
        lao: "ໃຫຍ່",
        speech: "a",
        examples: [
            {
                id: 1,
                korean: "큰 도시",
                read: "keun dosi",
                english: "large city",
                lao: "ເມືອງໃຫຍ່",
            },
        ],
    },
];
