import type { WordModel } from "~/models";

export const ABOUT_DRINK: WordModel[] = [
    {
        id: 1,
        korean: "물",
        read: "mul",
        english: "water",
        lao: "ນ້ຳ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 하루에 물을 많이 마십니다.",
                read: "Naneun haru-e mul-eul manh-i masimnida.",
                english: "I drink a lot of water every day.",
                lao: "ຂ້ອຍດື່ມນ້ຳຫລາຍໆທຸກມື້.",
            },
        ],
    },
    {
        id: 2,
        korean: "주스",
        read: "ju-seu",
        english: "juice",
        lao: "ນ້ຳຫວານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오렌지 주스는 상큼합니다.",
                read: "Orenji ju-seu-neun sangkeumhamnida.",
                english: "Orange juice is refreshing.",
                lao: "ນ້ຳສົ້ມມີຄວາມຊື່ນຊົມ.",
            },
        ],
    },
    {
        id: 3,
        korean: "우유",
        read: "u-yu",
        english: "milk",
        lao: "ນ້ຳນົມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 아침마다 우유를 마십니다.",
                read: "Jeoneun achim-mada uyureul masimnida.",
                english: "I drink milk every morning.",
                lao: "ຂ້ອຍດື່ມນ້ຳນົມທຸກໆເຊົ້າ.",
            },
        ],
    },
    {
        id: 4,
        korean: "커피",
        read: "keo-pi",
        english: "coffee",
        lao: "ກາເຟ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 커피를 마시는 것을 좋아합니다.",
                read: "Achim-e keopi-reul masineun geos-eul joahamnida.",
                english: "I like drinking coffee in the morning.",
                lao: "ຂ້ອຍມັກດື່ມກາເຟໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 5,
        korean: "차",
        read: "cha",
        english: "tea",
        lao: "ຊາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저녁에 따뜻한 차를 마십니다.",
                read: "Jeonyeog-e ttatteuthan cha-reul masimnida.",
                english: "I drink warm tea in the evening.",
                lao: "ຂ້ອຍດື່ມຊາອຸ່ນໆໃນຕອນແລງ.",
            },
        ],
    },
    {
        id: 6,
        korean: "소다",
        read: "so-da",
        english: "soda",
        lao: "ນ້ຳອັດລົມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 더운 날에 소다를 마십니다.",
                read: "Naneun deoun nal-e soda-reul masimnida.",
                english: "I drink soda on hot days.",
                lao: "ຂ້ອຍດື່ມນ້ຳອັດລົມໃນວັນຮ້ອນ.",
            },
        ],
    },
    {
        id: 7,
        korean: "맥주",
        read: "maek-ju",
        english: "beer",
        lao: "ເບຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 주말에 맥주를 마십니다.",
                read: "Jeoneun jumal-e maekju-reul masimnida.",
                english: "I drink beer on weekends.",
                lao: "ຂ້ອຍດື່ມເບຍໃນມື້ເສົາອາທິດ.",
            },
        ],
    },
    {
        id: 8,
        korean: "와인",
        read: "wa-in",
        english: "wine",
        lao: "ໄວຣ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "특별한 날에 와인을 마십니다.",
                read: "Teukbyeolhan nal-e wa-in-eul masimnida.",
                english: "I drink wine on special occasions.",
                lao: "ຂ້ອຍດື່ມໄວຣໃນວັນພິເສດ.",
            },
        ],
    },
    {
        id: 9,
        korean: "과일 주스",
        read: "gwa-il ju-seu",
        english: "fruit juice",
        lao: "ນ້ຳຜົນໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 과일 주스를 마십니다.",
                read: "Achim-e gwa-il ju-seu-reul masimnida.",
                english: "I drink fruit juice in the morning.",
                lao: "ຂ້ອຍດື່ມນ້ຳຜົນໄມ້ໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 10,
        korean: "초콜릿 우유",
        read: "cho-ko-lit u-yu",
        english: "chocolate milk",
        lao: "ນ້ຳນົມຊັອກໂກແລດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 초콜릿 우유를 좋아합니다.",
                read: "Jeoneun cho-ko-lit u-yu-reul joahamnida.",
                english: "I like chocolate milk.",
                lao: "ຂ້ອຍມັກນ້ຳນົມຊັອກໂກແລດ.",
            },
        ],
    },
    {
        id: 11,
        korean: "미네랄 워터",
        read: "mi-ne-ral wo-teo",
        english: "mineral water",
        lao: "ນ້ຳແຮ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "미네랄 워터는 몸에 좋습니다.",
                read: "Mineral wo-teo-neun mom-e johseumnida.",
                english: "Mineral water is good for your health.",
                lao: "ນ້ຳແຮ່ເປັນຜົນດີຕໍ່ສຸຂະພາບ.",
            },
        ],
    },
    {
        id: 12,
        korean: "스무디",
        read: "seu-mu-di",
        english: "smoothie",
        lao: "ນ້ຳປັ່ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 더운 날에 스무디를 마십니다.",
                read: "Naneun deoun nal-e seu-mu-di-reul masimnida.",
                english: "I drink smoothies on hot days.",
                lao: "ຂ້ອຍດື່ມນ້ຳປັ່ນໃນວັນຮ້ອນ.",
            },
        ],
    },
    {
        id: 13,
        korean: "에너지 드링크",
        read: "e-neo-ji deu-ring-keu",
        english: "energy drink",
        lao: "ເຄື່ອງດື່ມສູ່ກຳລັງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "에너지 드링크는 피로할 때 좋습니다.",
                read: "E-neoji deu-ring-keu-neun piro-hal ttae johseumnida.",
                english: "Energy drinks are good when you're tired.",
                lao: "ເຄື່ອງດື່ມສູ່ກຳລັງເປັນຜົນດີເມື່ອທ່ານເມື່ອຍລ້າ.",
            },
        ],
    },
];
