import type { WordModel } from "~/models";

export const ABOUT_HOUSE_GARDEN: WordModel[] = [
    {
        id: 1,
        korean: "정원",
        read: "jeong-won",
        english: "garden",
        lao: "ສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에서 꽃을 심었어요.",
                read: "Jeong-won-e-seo kkoch-eul sim-eoss-eo-yo.",
                english: "I planted flowers in the garden.",
                lao: "ຂ້ອຍປູກດອກໄມ້ໃນສວນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "잔디",
        read: "jan-di",
        english: "lawn",
        lao: "ຫຍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "잔디를 깎아야 해요.",
                read: "Jan-di-reul kka-kka-ya hae-yo.",
                english: "I need to mow the lawn.",
                lao: "ຂ້ອຍຕ້ອງຕັດຫຍ້າ.",
            },
        ],
    },
    {
        id: 3,
        korean: "꽃",
        read: "kkot",
        english: "flower",
        lao: "ດອກໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에 꽃이 많이 피었어요.",
                read: "Jeong-won-e kkoch-i manh-i pi-eoss-eo-yo.",
                english: "Many flowers bloomed in the garden.",
                lao: "ດອກໄມ້ຫຼາຍດອກບານໃນສວນ.",
            },
        ],
    },
    {
        id: 4,
        korean: "정원사",
        read: "jeong-won-sa",
        english: "gardener",
        lao: "ຄົນເຮັດສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원사가 정원을 돌보고 있어요.",
                read: "Jeong-won-sa-ga jeong-won-eul dol-bo-go iss-eo-yo.",
                english: "The gardener is taking care of the garden.",
                lao: "ຄົນເຮັດສວນກຳລັງດູແລສວນ.",
            },
        ],
    },
    {
        id: 5,
        korean: "화초",
        read: "hwa-cho",
        english: "plant",
        lao: "ພືດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "화초를 물을 주었어요.",
                read: "Hwa-cho-reul mul-eul ju-eoss-eo-yo.",
                english: "I watered the plants.",
                lao: "ຂ້ອຍໄດ້ລາດນ້ຳພືດ.",
            },
        ],
    },
    {
        id: 6,
        korean: "나무",
        read: "na-mu",
        english: "tree",
        lao: "ໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에 나무를 심었어요.",
                read: "Jeong-won-e na-mu-reul sim-eoss-eo-yo.",
                english: "I planted a tree in the garden.",
                lao: "ຂ້ອຍປູກໄມ້ໃນສວນ.",
            },
        ],
    },
    {
        id: 7,
        korean: "풀",
        read: "pul",
        english: "grass",
        lao: "ຫຍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에 풀이 많아요.",
                read: "Jeong-won-e pul-i manh-a-yo.",
                english: "There is a lot of grass in the garden.",
                lao: "ມີຫຍ້າຫຼາຍໃນສວນ.",
            },
        ],
    },
    {
        id: 8,
        korean: "정원 도구",
        read: "jeong-won do-gu",
        english: "garden tools",
        lao: "ເຄື່ອງມືເຮັດສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 도구를 사용하여 일을 했어요.",
                read: "Jeong-won do-gu-reul sa-yong-ha-yeo il-eul haess-eo-yo.",
                english: "I used garden tools to do the work.",
                lao: "ຂ້ອຍໃຊ້ເຄື່ອງມືເຮັດສວນເພື່ອເຮັດວຽກ.",
            },
        ],
    },
    {
        id: 9,
        korean: "물뿌리개",
        read: "mul-ppu-ri-gae",
        english: "watering can",
        lao: "ກະບອກນ້ຳ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "물뿌리개로 식물에 물을 주었어요.",
                read: "Mul-ppu-ri-gae-ro sik-mul-e mul-eul ju-eoss-eo-yo.",
                english: "I watered the plants with a watering can.",
                lao: "ຂ້ອຍໄດ້ລາດນ້ຳພືດໂດຍກະບອກນ້ຳ.",
            },
        ],
    },
    {
        id: 10,
        korean: "비료",
        read: "bi-ryo",
        english: "fertilizer",
        lao: "ປຸ໋ຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식물에 비료를 주었어요.",
                read: "Sik-mul-e bi-ryo-reul ju-eoss-eo-yo.",
                english: "I gave fertilizer to the plants.",
                lao: "ຂ້ອຍໃສ່ປຸ໋ຍໃຫ້ພືດ.",
            },
        ],
    },
    {
        id: 11,
        korean: "정원 가꾸기",
        read: "jeong-won ga-kku-gi",
        english: "gardening",
        lao: "ການເຮັດສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 가꾸기는 제 취미예요.",
                read: "Jeong-won ga-kku-gi-neun je chwi-mi-ye-yo.",
                english: "Gardening is my hobby.",
                lao: "ການເຮັດສວນແມ່ນສິ່ງທີ່ຂ້ອຍມັກ.",
            },
        ],
    },
    {
        id: 12,
        korean: "잔디 깎는 기계",
        read: "jan-di kkan-neun gi-gye",
        english: "lawn mower",
        lao: "ເຄື່ອງຕັດຫຍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "잔디 깎는 기계로 잔디를 깎았어요.",
                read: "Jan-di kkan-neun gi-gye-ro jan-di-reul kka-kka-ss-eo-yo.",
                english: "I mowed the lawn with a lawn mower.",
                lao: "ຂ້ອຍຕັດຫຍ້າໂດຍເຄື່ອງຕັດຫຍ້າ.",
            },
        ],
    },
    {
        id: 13,
        korean: "정원 가꾸기 장갑",
        read: "jeong-won ga-kku-gi jang-gap",
        english: "gardening gloves",
        lao: "ຖົງມືສຳລັບເຮັດສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 가꾸기 장갑을 끼고 일했어요.",
                read: "Jeong-won ga-kku-gi jang-gap-eul kki-go il-haess-eo-yo.",
                english: "I worked wearing gardening gloves.",
                lao: "ຂ້ອຍເຮັດວຽກໂດຍໃສ່ຖົງມືສຳລັບເຮັດສວນ.",
            },
        ],
    },
    {
        id: 14,
        korean: "정원 호미",
        read: "jeong-won ho-mi",
        english: "garden hoe",
        lao: "ແຫຼມຂຸດດິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 호미로 잡초를 뽑았어요.",
                read: "Jeong-won ho-mi-ro jap-cho-reul ppo-bass-eo-yo.",
                english: "I removed weeds with a garden hoe.",
                lao: "ຂ້ອຍຖອນຫຍ້າເຫຍື້ອດ້ວຍແຫຼມຂຸດດິນ.",
            },
        ],
    },
    {
        id: 15,
        korean: "정원 의자",
        read: "jeong-won ui-ja",
        english: "garden chair",
        lao: "ເກົ້າອີ້ສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 의자에 앉아서 책을 읽었어요.",
                read: "Jeong-won ui-ja-e an-ja-seo chaeg-eul il-geoss-eo-yo.",
                english: "I sat on the garden chair and read a book.",
                lao: "ຂ້ອຍນັ່ງຢູ່ເກົ້າອີ້ສວນແລະອ່ານປື້ມ.",
            },
        ],
    },
    {
        id: 16,
        korean: "온실",
        read: "on-sil",
        english: "greenhouse",
        lao: "ເຮືອນແກ້ວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "온실에서 채소를 키웠어요.",
                read: "On-sil-e-seo chae-so-reul ki-woss-eo-yo.",
                english: "I grew vegetables in the greenhouse.",
                lao: "ຂ້ອຍປູກຜັກໃນເຮືອນແກ້ວ.",
            },
        ],
    },
    {
        id: 17,
        korean: "정원 스프링클러",
        read: "jeong-won seu-peu-ring-keul-leo",
        english: "garden sprinkler",
        lao: "ເຄື່ອງພ້ຽງນ້ຳສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원 스프링클러로 물을 뿌렸어요.",
                read: "Jeong-won seu-peu-ring-keul-leo-ro mul-eul ppu-ryeoss-eo-yo.",
                english: "I watered the garden with a sprinkler.",
                lao: "ຂ້ອຍພ້ຽງນ້ຳສວນໂດຍເຄື່ອງພ້ຽງນ້ຳ.",
            },
        ],
    },
    {
        id: 18,
        korean: "비닐하우스",
        read: "bi-nil-ha-u-seu",
        english: "plastic greenhouse",
        lao: "ເຮືອນກະຈົກພາສະຕິກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "비닐하우스에서 작물을 재배했어요.",
                read: "Bi-nil-ha-u-seu-e-seo jak-mul-eul jae-bae-haess-eo-yo.",
                english: "I cultivated crops in a plastic greenhouse.",
                lao: "ຂ້ອຍປູກພືດໃນເຮືອນກະຈົກພາສະຕິກ.",
            },
        ],
    },
    {
        id: 19,
        korean: "물통",
        read: "mul-tong",
        english: "watering can",
        lao: "ກະບອກນ້ຳ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "물통으로 식물에 물을 줬어요.",
                read: "Mul-tong-eu-ro sik-mul-e mul-eul jweoss-eo-yo.",
                english: "I watered the plants with a watering can.",
                lao: "ຂ້ອຍລາດນ້ຳຕົ້ນໄມ້ໂດຍກະບອກນ້ຳ.",
            },
        ],
    },
    {
        id: 20,
        korean: "씨앗",
        read: "ssi-at",
        english: "seed",
        lao: "ເມັດພືດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에 씨앗을 뿌렸어요.",
                read: "Jeong-won-e ssi-at-eul ppu-ryeoss-eo-yo.",
                english: "I sowed seeds in the garden.",
                lao: "ຂ້ອຍຫວານເມັດພືດໃນສວນ.",
            },
        ],
    },
];
