import type { WordModel } from "~/models";

export const ABOUT_PRONOUNS: WordModel[] = [
    {
        id: 1,
        korean: "나는",
        read: "naneun",
        english: "I",
        lao: "ຂ້ອຍ",
        speech: "p",
        examples: [
            {
                id: 1,
                korean: "저는 매일 밤 아홉 시에 잠을 잡니다.",
                read: "jeoneun maeil bam ahop sie jameul jamnida.",
                english: "I go to bed every night at 9 o’clock PM.",
                lao: "ຂ້ອຍນອນຫຼັບທຸກຄືນເວລາ 9 ໂມງແລງ.",
            },
        ],
    },
    {
        id: 2,
        korean: "너는",
        read: "neoneun",
        english: "you",
        speech: "p",
        lao: "ເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "너는 ...이다",
                read: "neoneun ...ida",
                english: "You are…",
                lao: "ເຈົ້າແມ່ນ...",
            },
        ],
    },
    {
        id: 3,
        korean: "그녀는",
        read: "geunyeoneun",
        english: "she",
        speech: "p",
        lao: "ນາງ",
        examples: [
            {
                id: 1,
                korean: "그녀는 귀엽습니다.",
                read: "geunyeoneun gwiyeopseumnida.",
                english: "She is cute.",
                lao: "ນາງນ່າຮັກ.",
            },
        ],
    },
    {
        id: 4,
        korean: "그것은",
        read: "geugeoseun",
        english: "it",
        speech: "p",
        lao: "ມັນ",
        examples: [
            {
                id: 1,
                korean: "그것은 빨갛습니다.",
                read: "geugeoseun ppalkatseumnida.",
                english: "It's red.",
                lao: "ມັນມີສີແດງ.",
            },
        ],
    },
    {
        id: 5,
        korean: "그녀의",
        read: "geunyeoui",
        english: "her",
        speech: "p",
        lao: "ຂອງນາງ",
        examples: [
            {
                id: 1,
                korean: "그녀의 차",
                read: "geunyeoui cha",
                english: "her car",
                lao: "ລົດຂອງນາງ",
            },
        ],
    },
    {
        id: 6,
        korean: "우리의",
        read: "uriui",
        english: "our",
        speech: "p",
        lao: "ຂອງພວກເຮົາ",
        examples: [
            {
                id: 1,
                korean: "우리의 집",
                read: "uriui jip",
                english: "our house",
                lao: "ບ້ານຂອງພວກເຮົາ",
            },
        ],
    },
    {
        id: 7,
        korean: "그를",
        read: "geureul",
        english: "him",
        speech: "p",
        lao: "ເຂົາ",
        examples: [
            {
                id: 1,
                korean: "나는 그를 좋아합니다.",
                read: "naneun geureul johahamnida.",
                english: "I like him.",
                lao: "ຂ້ອຍມັກເຂົາ.",
            },
        ],
    },
    {
        id: 8,
        korean: "우리들을",
        read: "urideur-eul",
        english: "us",
        speech: "p",
        lao: "ພວກເຮົາ",
        examples: [
            {
                id: 1,
                korean: "그는 우리들을 도왔습니다.",
                read: "geuneun urideureul dowasseumnida.",
                english: "He helped us.",
                lao: "ເຂົາຊ່ວຍເຮົາ.",
            },
        ],
    },
    {
        id: 9,
        korean: "그녀의 것",
        read: "geunyeoui geot",
        english: "hers",
        speech: "p",
        lao: "ຂອງນາງ",
        examples: [
            {
                id: 1,
                korean: "이 책은 그녀의 것입니다.",
                read: "i chaeg-eun geunyeoui geosimnida.",
                english: "This book is hers.",
                lao: "ໜັງສືເລ່ມນີ້ແມ່ນຂອງນາງ.",
            },
        ],
    },
    {
        id: 10,
        korean: "너",
        read: "neo",
        english: "you",
        speech: "p",
        lao: "ເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "너는 정말 똑똑해요.",
                read: "neoneun jeongmal ttokttokhaeyo.",
                english: "You are really smart.",
                lao: "ເຈົ້າສົມຫຼາດຈິງໆ.",
            },
        ],
    },
    {
        id: 11,
        korean: "그들",
        read: "geudeul",
        english: "they",
        speech: "p",
        lao: "ພວກເຂົາ",
        examples: [
            {
                id: 1,
                korean: "그들은 공원에서 놀고 있어요.",
                read: "geudeul-eun gongwon-eseo nolgo iss-eoyo.",
                english: "They are playing in the park.",
                lao: "ພວກເຂົາກຳລັງຫຼິ້ນຢູ່ໃນສວນ.",
            },
        ],
    },
    {
        id: 12,
        korean: "당신의 것/너의 것",
        read: "dangsinui geot/neoui geot",
        english: "yours",
        speech: "p",
        lao: "ຂອງເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "이 집은 당신의 것입니다.",
                read: "i jib-eun dangsinui geosimnida.",
                english: "This house is yours.",
                lao: "ບ້ານຫຼັງນີ້ແມ່ນຂອງເຈົ້າ.",
            },
        ],
    },
    {
        id: 13,
        korean: "우리",
        read: "uri",
        english: "us",
        speech: "p",
        lao: "ພວກເຮົາ",
        examples: [
            {
                id: 1,
                korean: "우리는 친구입니다.",
                read: "urineun chinguimnida.",
                english: "We are friends.",
                lao: "ພວກເຮົາເປັນເພື່ອນ.",
            },
        ],
    },
    {
        id: 14,
        korean: "우리의 것",
        read: "uriui geot",
        english: "ours",
        speech: "p",
        lao: "ຂອງພວກເຮົາ",
        examples: [
            {
                id: 1,
                korean: "이 물건은 우리의 것입니다.",
                read: "i mulgeon-eun uriui geosimnida.",
                english: "This item is ours.",
                lao: "ສິ່ງນີ້ແມ່ນຂອງພວກເຮົາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "제 것/내 것",
        read: "je geot/nae geot",
        english: "mine",
        speech: "p",
        lao: "ຂອງຂ້ອຍ",
        examples: [
            {
                id: 1,
                korean: "이 책은 제 것입니다.",
                read: "i chaeg-eun je geosimnida.",
                english: "This book is mine.",
                lao: "ໜັງສືເລ່ມນີ້ແມ່ນຂອງຂ້ອຍ.",
            },
        ],
    },
    {
        id: 16,
        korean: "그들의 것",
        read: "geudeurui geot",
        english: "theirs",
        speech: "p",
        lao: "ຂອງພວກເຂົາ",
        examples: [
            {
                id: 1,
                korean: "이 자동차는 그들의 것입니다.",
                read: "i jadongcha-neun geudeurui geosimnida.",
                english: "This car is theirs.",
                lao: "ລົດຄັນນີ້ແມ່ນຂອງພວກເຂົາ.",
            },
        ],
    },
    {
        id: 17,
        korean: "그의",
        read: "geuui",
        english: "his",
        speech: "p",
        lao: "ຂອງລາວ",
        examples: [
            {
                id: 1,
                korean: "그의 방은 깨끗합니다.",
                read: "geuui bang-eun kkaekkeushamnida.",
                english: "His room is clean.",
                lao: "ຫ້ອງຂອງລາວສະອາດ.",
            },
        ],
    },
    {
        id: 18,
        korean: "나의/내",
        read: "naui/nae",
        english: "my",
        speech: "p",
        lao: "ຂອງຂ້ອຍ",
        examples: [
            {
                id: 1,
                korean: "나의 친구",
                read: "naui chingu",
                english: "my friend",
                lao: "ເພື່ອນຂອງຂ້ອຍ",
            },
        ],
    },
    {
        id: 19,
        korean: "그",
        read: "geu",
        english: "he",
        speech: "p",
        lao: "ລາວ",
        examples: [
            {
                id: 1,
                korean: "그는 친절합니다.",
                read: "geuneun chinjeolhamnida.",
                english: "He is kind.",
                lao: "ລາວມີນໍ້າໃຈ.",
            },
        ],
    },
    {
        id: 20,
        korean: "그녀의",
        read: "geunyeoui",
        english: "her",
        speech: "p",
        lao: "ຂອງນາງ",
        examples: [
            {
                id: 1,
                korean: "그녀의 책",
                read: "geunyeoui chaek",
                english: "her book",
                lao: "ໜັງສືຂອງນາງ",
            },
        ],
    },
    {
        id: 21,
        korean: "너의 것",
        read: "neoui geot",
        english: "yours",
        speech: "p",
        lao: "ຂອງເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "이것은 너의 것입니다.",
                read: "igeoseun neoui geosimnida.",
                english: "This is yours.",
                lao: "ມັນແມ່ນຂອງເຈົ້າ.",
            },
        ],
    },
    {
        id: 22,
        korean: "너의",
        read: "neoui",
        english: "your",
        speech: "p",
        lao: "ຂອງເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "너의 가방",
                read: "neoui gabang",
                english: "your bag",
                lao: "ກະເປົາຂອງເຈົ້າ",
            },
        ],
    },
    {
        id: 23,
        korean: "그의 것",
        read: "geuui geot",
        english: "its",
        speech: "p",
        lao: "ຂອງມັນ",
        examples: [
            {
                id: 1,
                korean: "이것은 그의 것입니다.",
                read: "igeoseun geuui geosimnida.",
                english: "This is its.",
                lao: "ມັນແມ່ນຂອງມັນ.",
            },
        ],
    },
    {
        id: 24,
        korean: "그들",
        read: "geudeul",
        english: "them",
        speech: "p",
        lao: "ພວກເຂົາ",
        examples: [
            {
                id: 1,
                korean: "그들은 공원에 있습니다.",
                read: "geudeul-eun gongwon-e iss-eumnida.",
                english: "They are at the park.",
                lao: "ພວກເຂົາຢູ່ທີ່ສວນ.",
            },
        ],
    },
    {
        id: 25,
        korean: "나",
        read: "na",
        english: "me",
        speech: "p",
        lao: "ຂ້ອຍ",
        examples: [
            {
                id: 1,
                korean: "그는 나를 도와줬어요.",
                read: "geuneun nareul dowajwosseoyo.",
                english: "He helped me.",
                lao: "ລາວໄດ້ຊ່ວຍຂ້ອຍ.",
            },
        ],
    },
    {
        id: 26,
        korean: "너",
        read: "neo",
        english: "you",
        speech: "p",
        lao: "ເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "너는 정말 똑똑해요.",
                read: "neoneun jeongmal ttokttokhaeyo.",
                english: "You are really smart.",
                lao: "ເຈົ້າສົມຫຼາດຫຼາຍ.",
            },
        ],
    },
    {
        id: 27,
        korean: "그들의",
        read: "geudeurui",
        english: "their",
        speech: "p",
        lao: "ຂອງພວກເຂົາ",
        examples: [
            {
                id: 1,
                korean: "이것은 그들의 것입니다.",
                read: "igeoseun geudeurui geosimnida.",
                english: "This is their.",
                lao: "ມັນແມ່ນຂອງພວກເຂົາ.",
            },
        ],
    },
    {
        id: 28,
        korean: "너의",
        read: "neoui",
        english: "your",
        speech: "p",
        lao: "ຂອງເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "너의 책",
                read: "neoui chaek",
                english: "your book",
                lao: "ໜັງສືຂອງເຈົ້າ",
            },
        ],
    },
    {
        id: 29,
        korean: "당신",
        read: "dangsin",
        english: "you",
        speech: "p",
        lao: "ເຈົ້າ",
        examples: [
            {
                id: 1,
                korean: "당신은 친절해요.",
                read: "dangsin-eun chinjeolhaeyo.",
                english: "You are kind.",
                lao: "ເຈົ້າມີນໍ້າໃຈ.",
            },
        ],
    },
    {
        id: 30,
        korean: "그것의",
        read: "geugeosui",
        english: "its",
        speech: "p",
        lao: "ຂອງມັນ",
        examples: [
            {
                id: 1,
                korean: "그것의 색깔",
                read: "geugeosui saekkkal",
                english: "its color",
                lao: "ສີຂອງມັນ",
            },
        ],
    },
    {
        id: 31,
        korean: "그것",
        read: "geugeot",
        english: "it",
        speech: "p",
        lao: "ມັນ",
        examples: [
            {
                id: 1,
                korean: "그것은 빨간색입니다.",
                read: "geugeot-eun ppalgansaegimnida.",
                english: "It is red.",
                lao: "ມັນແມ່ນສີແດງ.",
            },
        ],
    },
    {
        id: 32,
        korean: "그의",
        read: "geuui",
        english: "his",
        speech: "p",
        lao: "ຂອງລາວ",
        examples: [
            {
                id: 1,
                korean: "그의 책",
                read: "geuui chaek",
                english: "his book",
                lao: "ໜັງສືຂອງລາວ",
            },
        ],
    },
];
