import type { WordModel } from "~/models";

export const ABOUT_RESTAURANT: WordModel[] = [
    {
        id: 1,
        korean: "식당",
        read: "sik-dang",
        english: "restaurant",
        lao: "ຮ້ານອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 저녁을 식당에서 먹었습니다.",
                read: "Urineun jeonyeog-eul sikdang-eseo meogeossseumnida.",
                english: "We had dinner at a restaurant.",
                lao: "ພວກເຮົາກິນອາຫານແລງຢູ່ຮ້ານອາຫານ.",
            },
        ],
    },
    {
        id: 2,
        korean: "메뉴",
        read: "me-nyu",
        english: "menu",
        lao: "ເມນູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "메뉴를 보고 주문하세요.",
                read: "Menyureul bogo jumunhaseyo.",
                english: "Please look at the menu and order.",
                lao: "ກະລຸນາເບິ່ງເມນູແລະສັ່ງອາຫານ.",
            },
        ],
    },
    {
        id: 3,
        korean: "주문하다",
        read: "ju-mun-ha-da",
        english: "order",
        lao: "ສັ່ງ",
        speech: "v",
        examples: [
            {
                id: 1,
                korean: "저는 피자를 주문했습니다.",
                read: "Jeoneun pija-reul jumunhaessseumnida.",
                english: "I ordered a pizza.",
                lao: "ຂ້ອຍສັ່ງພິດຊາ.",
            },
        ],
    },
    {
        id: 4,
        korean: "웨이터",
        read: "we-i-teo",
        english: "waiter",
        lao: "ພະນັກງານເສີບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "웨이터가 우리에게 물을 가져다 주었습니다.",
                read: "Weiteoga uriege muleul gajyeoda jussseumnida.",
                english: "The waiter brought us water.",
                lao: "ພະນັກງານເສີບໄດ້ນຳນ້ຳມາໃຫ້ພວກເຮົາ.",
            },
        ],
    },
    {
        id: 5,
        korean: "요리사",
        read: "yo-ri-sa",
        english: "chef",
        lao: "ພໍ່ຄົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "요리사는 맛있는 음식을 만들었습니다.",
                read: "Yorisa-neun masinneun eumsig-eul mandeuleossseumnida.",
                english: "The chef made delicious food.",
                lao: "ພໍ່ຄົວໄດ້ເຮັດອາຫານທີ່ອິ່ມອຫຼາຍ.",
            },
        ],
    },
    {
        id: 6,
        korean: "예약하다",
        read: "ye-yak-ha-da",
        english: "reserve",
        lao: "ຈອງ",
        speech: "v",
        examples: [
            {
                id: 1,
                korean: "우리는 저녁 식사를 위해 식당을 예약했습니다.",
                read: "Urineun jeonyeog sigsa-reul wihae sikdang-eul yeyakhaessseumnida.",
                english: "We reserved a restaurant for dinner.",
                lao: "ພວກເຮົາຈອງຮ້ານອາຫານສຳລັບມື້ແລງ.",
            },
        ],
    },
    {
        id: 7,
        korean: "계산서",
        read: "gye-san-seo",
        english: "bill",
        lao: "ໃບບິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "계산서를 주세요.",
                read: "Gyesanseo-reul juseyo.",
                english: "Please give me the bill.",
                lao: "ກະລຸນາໃຫ້ໃບບິນແກ່ຂ້ອຍ.",
            },
        ],
    },
    {
        id: 8,
        korean: "팁",
        read: "tip",
        english: "tip",
        lao: "ທິບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "웨이터에게 팁을 주었습니다.",
                read: "Weiteo-ege tip-eul jussseumnida.",
                english: "I gave a tip to the waiter.",
                lao: "ຂ້ອຍໃຫ້ທິບແກ່ພະນັກງານເສີບ.",
            },
        ],
    },
    {
        id: 9,
        korean: "음식",
        read: "eum-sik",
        english: "food",
        lao: "ອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "음식이 맛있습니다.",
                read: "Eumsig-i mas-issseumnida.",
                english: "The food is delicious.",
                lao: "ອາຫານມີລົດຊາດອິ່ມອຫຼາຍ.",
            },
        ],
    },
    {
        id: 10,
        korean: "음료수",
        read: "eum-ryo-su",
        english: "drink",
        lao: "ເຄື່ອງດື່ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "음료수를 주문했습니다.",
                read: "Eumryosu-reul jumunhaessseumnida.",
                english: "I ordered a drink.",
                lao: "ຂ້ອຍສັ່ງເຄື່ອງດື່ມ.",
            },
        ],
    },
    {
        id: 11,
        korean: "전채 요리",
        read: "jeon-chae yo-ri",
        english: "appetizer",
        lao: "ອາຫານລົບທ້ອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "전채 요리를 먼저 먹었습니다.",
                read: "Jeonchae yori-reul meonjeo meogeossseumnida.",
                english: "We had appetizers first.",
                lao: "ພວກເຮົາກິນອາຫານລົບທ້ອງກ່ອນ.",
            },
        ],
    },
    {
        id: 12,
        korean: "후식",
        read: "hu-sik",
        english: "dessert",
        lao: "ຂອງຫວານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "후식으로 아이스크림을 먹었습니다.",
                read: "Husig-euro aiseukeurim-eul meogeossseumnida.",
                english: "We had ice cream for dessert.",
                lao: "ພວກເຮົາກິນອາຍສະຄີມເປັນຂອງຫວານ.",
            },
        ],
    },
    {
        id: 13,
        korean: "식사",
        read: "sik-sa",
        english: "meal",
        lao: "ອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식사가 맛있었습니다.",
                read: "Siksa-ga mas-issseossseumnida.",
                english: "The meal was delicious.",
                lao: "ອາຫານອິ່ມຫວານຫວານ.",
            },
        ],
    },
    {
        id: 14,
        korean: "음식점",
        read: "eum-sik-jeom",
        english: "eatery",
        lao: "ຮ້ານອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이 음식점은 맛있어요.",
                read: "I eumsikjeom-eun masissseoyo.",
                english: "This eatery is delicious.",
                lao: "ຮ້ານອາຫານນີ້ມີລົດຊາດດີ.",
            },
        ],
    },
    {
        id: 15,
        korean: "고객",
        read: "go-gae",
        english: "customer",
        lao: "ລູກຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "고객이 많습니다.",
                read: "Gogaeg-i manhseumnida.",
                english: "There are many customers.",
                lao: "ມີລູກຄ້າຫຼາຍ.",
            },
        ],
    },
];
