import type { WordModel } from "~/models";

export const ABOUT_HOUSE_BATHROOM: WordModel[] = [
    {
        id: 1,
        korean: "욕실",
        read: "yok-sil",
        english: "bathroom",
        lao: "ຫ້ອງນໍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "욕실을 청소했어요.",
                read: "Yok-sil-eul cheongsohaess-eoyo.",
                english: "I cleaned the bathroom.",
                lao: "ຂ້ອຍທໍາຄວາມສະອາດຫ້ອງນໍ້າ.",
            },
        ],
    },
    {
        id: 2,
        korean: "샤워",
        read: "sya-wo",
        english: "shower",
        lao: "ຝັກບົກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "샤워를 하고 나왔어요.",
                read: "Sya-wo-reul hago nawass-eoyo.",
                english: "I took a shower and came out.",
                lao: "ຂ້ອຍອາບນໍ້າແລະອອກມາ.",
            },
        ],
    },
    {
        id: 3,
        korean: "욕조",
        read: "yok-jo",
        english: "bathtub",
        lao: "ອ່າງນໍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "욕조에 물을 채웠어요.",
                read: "Yok-jo-e mul-eul chae-woss-eoyo.",
                english: "I filled the bathtub with water.",
                lao: "ຂ້ອຍເຕີມນໍ້າໃສ່ອ່າງນໍ້າ.",
            },
        ],
    },
    {
        id: 4,
        korean: "세면대",
        read: "se-myeon-dae",
        english: "sink",
        lao: "ອ່າງລ້າງໜ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "세면대에서 손을 씻었어요.",
                read: "Se-myeon-dae-e-seo son-eul ssiss-eoss-eoyo.",
                english: "I washed my hands in the sink.",
                lao: "ຂ້ອຍລ້າງມືທີ່ອ່າງລ້າງໜ້າ.",
            },
        ],
    },
    {
        id: 5,
        korean: "거울",
        read: "geo-ul",
        english: "mirror",
        lao: "ກະຈົກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거울을 보면서 머리를 빗어요.",
                read: "Geo-ul-eul bo-myeon-seo meo-ri-reul bit-eo-yo.",
                english: "I comb my hair while looking in the mirror.",
                lao: "ຂ້ອຍຫວີຜົມໂດຍເບິ່ງໃນກະຈົກ.",
            },
        ],
    },
    {
        id: 6,
        korean: "화장실",
        read: "hwa-jang-sil",
        english: "toilet",
        lao: "ຫ້ອງສຸກສິ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "화장실에 갔어요.",
                read: "Hwa-jang-sil-e ga-ss-eoyo.",
                english: "I went to the toilet.",
                lao: "ຂ້ອຍໄປຫ້ອງນໍ້າ.",
            },
        ],
    },
    {
        id: 7,
        korean: "변기",
        read: "byeon-gi",
        english: "toilet bowl",
        lao: "ໂຖ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "변기를 청소했어요.",
                read: "Byeon-gi-reul cheongsohaess-eoyo.",
                english: "I cleaned the toilet bowl.",
                lao: "ຂ້ອຍທຳຄວາມສະອາດໂຖ້.",
            },
        ],
    },
    {
        id: 8,
        korean: "수건",
        read: "su-geon",
        english: "towel",
        lao: "ຜ້າເຊັດຕົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수건으로 몸을 닦아요.",
                read: "Su-geon-eu-ro mom-eul takk-ayo.",
                english: "I dry my body with a towel.",
                lao: "ຂ້ອຍເຊັດຕົວດ້ວຍຜ້າເຊັດຕົວ.",
            },
        ],
    },
    {
        id: 9,
        korean: "비누",
        read: "bi-nu",
        english: "soap",
        lao: "ສະບູ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "비누로 손을 씻어요.",
                read: "Bi-nu-ro son-eul ssiss-eo-yo.",
                english: "I wash my hands with soap.",
                lao: "ຂ້ອຍລ້າງມືດ້ວຍສະບູ່.",
            },
        ],
    },
    {
        id: 10,
        korean: "치약",
        read: "chi-yak",
        english: "toothpaste",
        lao: "ຢາສີຟັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "치약을 칫솔에 짜요.",
                read: "Chi-yak-eul chis-sol-e jja-yo.",
                english: "I squeeze toothpaste onto the toothbrush.",
                lao: "ຂ້ອຍບີບຢາສີຟັນໃສ່ແປງສີຟັນ.",
            },
        ],
    },
    {
        id: 11,
        korean: "칫솔",
        read: "chis-sol",
        english: "toothbrush",
        lao: "ແປງສີຟັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "칫솔로 이를 닦아요.",
                read: "Chis-sol-lo il-eul takk-ayo.",
                english: "I brush my teeth with a toothbrush.",
                lao: "ຂ້ອຍແປງຟັນດ້ວຍແປງສີຟັນ.",
            },
        ],
    },
    {
        id: 12,
        korean: "샴푸",
        read: "syam-pu",
        english: "shampoo",
        lao: "ແຊມພູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "샴푸로 머리를 감아요.",
                read: "Syam-pu-ro meo-ri-reul gam-ayo.",
                english: "I wash my hair with shampoo.",
                lao: "ຂ້ອຍສະຜົມດ້ວຍແຊມພູ.",
            },
        ],
    },
    {
        id: 13,
        korean: "컨디셔너",
        read: "keon-di-syeo-neo",
        english: "conditioner",
        lao: "ນໍ້າມັນຫມັກຜົມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "컨디셔너로 머리를 부드럽게 해요.",
                read: "Keon-di-syeo-neo-ro meo-ri-reul bu-deu-reop-ge hae-yo.",
                english: "I soften my hair with conditioner.",
                lao: "ຂ້ອຍຫມັກຜົມດ້ວຍນ້ຳມັນຫມັກຜົມ.",
            },
        ],
    },
    {
        id: 14,
        korean: "드라이어",
        read: "deu-ra-i-eo",
        english: "hair dryer",
        lao: "ໄດຣ໌ເຜົາຜົມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "드라이어로 머리를 말렸어요.",
                read: "Deu-ra-i-eo-ro meo-ri-reul mal-lyeoss-eo-yo.",
                english: "I dried my hair with a hair dryer.",
                lao: "ຂ້ອຍເຜົາຜົມດ້ວຍໄດຣ໌ເຜົາຜົມ.",
            },
        ],
    },
];
