import type { WordModel } from "~/models";

export const ABOUT_BUS_STOP_STATION: WordModel[] = [
    {
        id: 1,
        korean: "버스 정류장",
        read: "beoseu jeong-ryu-jang",
        english: "bus stop",
        lao: "ຈຸດຈອດລົດເມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 정류장에서 기다릴게요.",
                read: "Beoseu jeong-ryu-jang-eseo gida-ril-geyo.",
                english: "I will wait at the bus stop.",
                lao: "ຂ້ອຍຈະລໍຢູ່ຈຸດຈອດລົດເມ.",
            },
        ],
    },
    {
        id: 2,
        korean: "버스 터미널",
        read: "beoseu teo-mi-neol",
        english: "bus terminal",
        lao: "ສະຖານີລົດເມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 터미널로 가야 해요.",
                read: "Beoseu teo-mi-neol-lo ga-ya hae-yo.",
                english: "We need to go to the bus terminal.",
                lao: "ພວກເຮົາຕ້ອງໄປທີ່ສະຖານີລົດເມ.",
            },
        ],
    },
    {
        id: 3,
        korean: "노선도",
        read: "no-seon-do",
        english: "route map",
        lao: "ແຜນທີ່ເສັ້ນທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "노선도를 확인하세요.",
                read: "No-seon-do-reul hwa-gin-ha-se-yo.",
                english: "Check the route map.",
                lao: "ກວດເບິ່ງແຜນທີ່ເສັ້ນທາງ.",
            },
        ],
    },
    {
        id: 4,
        korean: "정류장 시간표",
        read: "jeong-ryu-jang si-gan-pyo",
        english: "bus schedule",
        lao: "ຕາຕະລາງເວລາລົດເມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정류장 시간표를 확인하세요.",
                read: "Jeong-ryu-jang si-gan-pyo-reul hwa-gin-ha-se-yo.",
                english: "Check the bus schedule.",
                lao: "ກວດເບິ່ງຕາຕະລາງເວລາລົດເມ.",
            },
        ],
    },
    {
        id: 5,
        korean: "운행 시간",
        read: "un-haeng si-gan",
        english: "operating hours",
        lao: "ເວລາເດີນລົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "운행 시간을 확인하세요.",
                read: "Un-haeng si-gan-eul hwa-gin-ha-se-yo.",
                english: "Check the operating hours.",
                lao: "ກວດເບິ່ງເວລາເດີນລົດ.",
            },
        ],
    },
    {
        id: 6,
        korean: "티켓",
        read: "ti-ket",
        english: "ticket",
        lao: "ປີ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "티켓을 구매하세요.",
                read: "Ti-ket-eul gu-mae-ha-se-yo.",
                english: "Buy a ticket.",
                lao: "ຊື້ປີ້.",
            },
        ],
    },
    {
        id: 7,
        korean: "요금",
        read: "yo-geum",
        english: "fare",
        lao: "ຄ່າລົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 요금을 지불하세요.",
                read: "Beoseu yo-geum-eul ji-bul-ha-se-yo.",
                english: "Pay the bus fare.",
                lao: "ຈ່າຍຄ່າລົດເມ.",
            },
        ],
    },
    {
        id: 8,
        korean: "하차",
        read: "ha-cha",
        english: "get off",
        lao: "ລົງລົດ",
        speech: "v",
        examples: [
            {
                id: 1,
                korean: "다음 정류장에서 하차하세요.",
                read: "Da-eum jeong-ryu-jang-eseo ha-cha-ha-se-yo.",
                english: "Get off at the next stop.",
                lao: "ລົງລົດເມທີ່ຈຸດຈອດຕໍ່ໄປ.",
            },
        ],
    },
    {
        id: 9,
        korean: "승차",
        read: "seung-cha",
        english: "get on",
        lao: "ຂື້ນລົດ",
        speech: "v",
        examples: [
            {
                id: 1,
                korean: "정류장에서 승차하세요.",
                read: "Jeong-ryu-jang-eseo seung-cha-ha-se-yo.",
                english: "Get on at the bus stop.",
                lao: "ຂື້ນລົດເມທີ່ຈຸດຈອດ.",
            },
        ],
    },
    {
        id: 10,
        korean: "경로",
        read: "gyeong-ro",
        english: "route",
        lao: "ເສັ້ນທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 경로를 확인하세요.",
                read: "Beoseu gyeong-ro-reul hwa-gin-ha-se-yo.",
                english: "Check the bus route.",
                lao: "ກວດເບິ່ງເສັ້ນທາງຂອງລົດເມ.",
            },
        ],
    },
    {
        id: 11,
        korean: "환승",
        read: "hwan-seung",
        english: "transfer",
        lao: "ປ່ຽນລົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "환승을 위해 다음 정류장에서 내리세요.",
                read: "Hwan-seung-eul wi-hae da-eum jeong-ryu-jang-eseo nae-ri-se-yo.",
                english: "Get off at the next stop to transfer.",
                lao: "ລົງລົດເມທີ່ຈຸດຈອດຕໍ່ໄປເພື່ອປ່ຽນລົດ.",
            },
        ],
    },
    {
        id: 12,
        korean: "출발",
        read: "chul-bal",
        english: "departure",
        lao: "ອອກເດີນທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 출발 시간을 확인하세요.",
                read: "Beoseu chul-bal si-gan-eul hwa-gin-ha-se-yo.",
                english: "Check the bus departure time.",
                lao: "ກວດເບິ່ງເວລາອອກເດີນທາງຂອງລົດເມ.",
            },
        ],
    },
    {
        id: 13,
        korean: "도착",
        read: "do-chak",
        english: "arrival",
        lao: "ມາຮອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 도착 시간을 확인하세요.",
                read: "Beoseu do-chak si-gan-eul hwa-gin-ha-se-yo.",
                english: "Check the bus arrival time.",
                lao: "ກວດເບິ່ງເວລາມາຮອດຂອງລົດເມ.",
            },
        ],
    },
    {
        id: 14,
        korean: "승객",
        read: "seung-gaek",
        english: "passenger",
        lao: "ຜູ້ໂດຍສານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "모든 승객은 버스에 타세요.",
                read: "Mo-deun seung-gaek-eun beoseu-e ta-se-yo.",
                english: "All passengers, please board the bus.",
                lao: "ຜູ້ໂດຍສານທຸກຄົນ, ກະລຸນາຂື້ນລົດເມ.",
            },
        ],
    },
    {
        id: 15,
        korean: "운전사",
        read: "un-jeon-sa",
        english: "driver",
        lao: "ຄົນຂັບລົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 운전사에게 인사하세요.",
                read: "Beoseu un-jeon-sa-e-ge in-sa-ha-se-yo.",
                english: "Greet the bus driver.",
                lao: "ສະບາຍດີຄົນຂັບລົດເມ.",
            },
        ],
    },
    {
        id: 16,
        korean: "목적지",
        read: "mok-jeok-ji",
        english: "destination",
        lao: "ຈຸດຫມາຍປາຍທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "목적지에 도착하면 알려주세요.",
                read: "Mok-jeok-ji-e do-chak-ha-myeon al-lyeo-ju-se-yo.",
                english: "Please let me know when we reach the destination.",
                lao: "ກະລຸນາແຈ້ງໃຫ້ຂ້ອຍຮູ້ເມື່ອພວກເຮົາມາຮອດຈຸດຫມາຍປາຍທາງ.",
            },
        ],
    },
    {
        id: 17,
        korean: "운행 거리",
        read: "un-haeng geo-ri",
        english: "route distance",
        lao: "ໄລຍະທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "운행 거리는 얼마나 되나요?",
                read: "Un-haeng geo-ri-neun eol-ma-na doe-na-yo?",
                english: "How long is the route distance?",
                lao: "ໄລຍະທາງເສັ້ນທາງເປັນຍັງໃດ?",
            },
        ],
    },
    {
        id: 18,
        korean: "정류장 번호",
        read: "jeong-ryu-jang beon-ho",
        english: "stop number",
        lao: "ໝາຍເລກຈຸດຈອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정류장 번호를 확인하세요.",
                read: "Jeong-ryu-jang beon-ho-reul hwa-gin-ha-se-yo.",
                english: "Check the stop number.",
                lao: "ກວດເບິ່ງໝາຍເລກຈຸດຈອດ.",
            },
        ],
    },
    {
        id: 19,
        korean: "도착 시간",
        read: "do-chak si-gan",
        english: "arrival time",
        lao: "ເວລາມາຮອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스의 도착 시간을 확인하세요.",
                read: "Beo-seu-ui do-chak si-gan-eul hwa-gin-ha-se-yo.",
                english: "Check the bus arrival time.",
                lao: "ກວດເບິ່ງເວລາມາຮອດຂອງລົດເມ.",
            },
        ],
    },
    {
        id: 20,
        korean: "버스 정류장 위치",
        read: "beoseu jeong-ryu-jang wi-chi",
        english: "bus stop location",
        lao: "ຕໍາແໜ່ງຈຸດຈອດລົດເມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "버스 정류장 위치를 확인하세요.",
                read: "Beoseu jeong-ryu-jang wi-chi-reul hwa-gin-ha-se-yo.",
                english: "Check the bus stop location.",
                lao: "ກວດເບິ່ງຕໍາແໜ່ງຈຸດຈອດລົດເມ.",
            },
        ],
    },
];
