import type { WordModel } from "~/models";

export const ABOUT_FAMILY: WordModel[] = [
    {
        id: 1,
        korean: "가족",
        read: "ga-jok",
        english: "family",
        lao: "ຄອບຄົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "가족이 모여서 식사를 했어요.",
                read: "ga-jok-i mo-yeo-seo sik-sa-reul haess-eo-yo.",
                english: "The family gathered for a meal.",
                lao: "ຄອບຄົວໄດ້ມາພົບກັນເພື່ອກິນເຂົ້າ.",
            },
        ],
    },
    {
        id: 2,
        korean: "어머니",
        read: "eo-meo-ni",
        english: "mother",
        lao: "ແມ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "어머니가 저녁을 준비하고 있어요.",
                read: "eo-meo-ni-ga jeo-nyeog-eul jun-bi-ha-go iss-eo-yo.",
                english: "Mother is preparing dinner.",
                lao: "ແມ່ກຳລັງຈັດຕຽມອາຫານແລງ.",
            },
        ],
    },
    {
        id: 3,
        korean: "아버지",
        read: "a-beo-ji",
        english: "father",
        lao: "ພໍ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아버지가 일을 하고 계세요.",
                read: "a-beo-ji-ga il-eul ha-go gye-se-yo.",
                english: "Father is working.",
                lao: "ພໍ່ກຳລັງເຮັດວຽກ.",
            },
        ],
    },
    {
        id: 4,
        korean: "형제",
        read: "hyeong-je",
        english: "brother",
        lao: "ອ້າຍນ້ອງຊາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "형제들은 사이가 좋아요.",
                read: "hyeong-je-deul-eun sa-i-ga joh-a-yo.",
                english: "The brothers get along well.",
                lao: "ອ້າຍນ້ອງຊາຍມີຄວາມສຳພັນດີ.",
            },
        ],
    },
    {
        id: 5,
        korean: "자매",
        read: "ja-mae",
        english: "sister",
        lao: "ອ້າຍນ້ອງສາວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "자매는 함께 쇼핑을 갔어요.",
                read: "ja-mae-neun ham-kke syo-ping-eul gat-eo-yo.",
                english: "The sisters went shopping together.",
                lao: "ອ້າຍນ້ອງສາວໄປຊື້ເຄື່ອງດ້ວຍກັນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "할머니",
        read: "hal-meo-ni",
        english: "grandmother",
        lao: "ຍ່າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "할머니가 이야기를 들려주셨어요.",
                read: "hal-meo-ni-ga i-ya-gi-reul deul-lyeo-ju-syeoss-eo-yo.",
                english: "Grandmother told us a story.",
                lao: "ຍ່າໄດ້ເລົ່າເລື່ອງລາວໃຫ້ພວກເຮົາຟັງ.",
            },
        ],
    },
    {
        id: 7,
        korean: "할아버지",
        read: "hal-a-beo-ji",
        english: "grandfather",
        lao: "ປູ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "할아버지가 산책을 나가셨어요.",
                read: "hal-a-beo-ji-ga san-chae-g-eul na-ga-syeoss-eo-yo.",
                english: "Grandfather went for a walk.",
                lao: "ປູ່ໄດ້ອອກເດີນຫາຍໃຈ.",
            },
        ],
    },
    {
        id: 8,
        korean: "아들",
        read: "a-deul",
        english: "son",
        lao: "ລູກຊາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아들이 축구를 좋아해요.",
                read: "a-deul-i chug-gu-reul joh-a-hae-yo.",
                english: "The son likes football.",
                lao: "ລູກຊາຍມັກເຕະບານ.",
            },
        ],
    },
    {
        id: 9,
        korean: "딸",
        read: "ttal",
        english: "daughter",
        lao: "ລູກສາວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "딸이 피아노를 치고 있어요.",
                read: "ttal-i pi-a-no-reul chi-go iss-eo-yo.",
                english: "The daughter is playing the piano.",
                lao: "ລູກສາວກຳລັງຕີກິຕ້າ.",
            },
        ],
    },
    {
        id: 10,
        korean: "부모님",
        read: "bu-mo-nim",
        english: "parents",
        lao: "ພໍ່ແມ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "부모님은 항상 우리를 지원해 주셨어요.",
                read: "bu-mo-nim-eun hang-sang u-ri-reul ji-won-hae ju-syeoss-eo-yo.",
                english: "Parents always supported us.",
                lao: "ພໍ່ແມ່ມັກຊ່ວຍເຫຼືອພວກເຮົາຕະຫຼອດ.",
            },
        ],
    },
    {
        id: 11,
        korean: "삼촌",
        read: "sam-chon",
        english: "uncle",
        lao: "ອາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "삼촌이 우리에게 선물을 주셨어요.",
                read: "sam-chon-i u-ri-e-ge seon-mul-eul ju-syeoss-eo-yo.",
                english: "Uncle gave us a gift.",
                lao: "ອາໃຫ້ຂອງຂວັນແກ່ພວກເຮົາ.",
            },
        ],
    },
    {
        id: 12,
        korean: "이모",
        read: "i-mo",
        english: "aunt",
        lao: "ອາປ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이모가 맛있는 음식을 해 주셨어요.",
                read: "i-mo-ga mas-iss-neun eum-sig-eul hae ju-syeoss-eo-yo.",
                english: "Aunt made delicious food for us.",
                lao: "ອາປ້າໄດ້ເຮັດອາຫານອັນແຊບອິ່ມແກ່ພວກເຮົາ.",
            },
        ],
    },
    {
        id: 13,
        korean: "조카",
        read: "jo-ka",
        english: "nephew",
        lao: "ຫລານຊາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "조카가 학교에 다니고 있어요.",
                read: "jo-ka-ga hag-gyo-e da-ni-go iss-eo-yo.",
                english: "Nephew is attending school.",
                lao: "ຫລານຊາຍກຳລັງຮຽນຢູ່ໂຮງຮຽນ.",
            },
        ],
    },
    {
        id: 14,
        korean: "조카딸",
        read: "jo-ka-ttal",
        english: "niece",
        lao: "ຫລານສາວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "조카딸이 춤을 추고 있어요.",
                read: "jo-ka-ttal-i chum-eul chu-go iss-eo-yo.",
                english: "Niece is dancing.",
                lao: "ຫລານສາວກຳລັງເຕັ້ນ.",
            },
        ],
    },
];
