import type { WordModel } from "~/models";

export const ABOUT_PARK: WordModel[] = [
    {
        id: 1,
        korean: "공원",
        read: "gong-won",
        english: "park",
        lao: "ສວນສາທາລະນະ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 공원에서 산책을 했습니다.",
                read: "Urineun gong-won-eseo sanchaeg-eul haessseumnida.",
                english: "We took a walk in the park.",
                lao: "ພວກເຮົາໄດ້ຍ່າງຫຼິ້ນຢູ່ສວນສາທາລະນະ.",
            },
        ],
    },
    {
        id: 2,
        korean: "놀이기구",
        read: "nol-i-gi-gu",
        english: "playground equipment",
        lao: "ເຄື່ອງຫຼິ້ນຢູ່ສະຫນາມຫຼິ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들이 놀이기구에서 놀고 있어요.",
                read: "Aideul-i nol-igi-gu-eseo nolgo iss-eoyo.",
                english: "Children are playing on the playground equipment.",
                lao: "ເດັກນ້ອຍກຳລັງຫຼິ້ນຢູ່ເຄື່ອງຫຼິ້ນໃນສະຫນາມຫຼິ້ນ.",
            },
        ],
    },
    {
        id: 3,
        korean: "벤치",
        read: "ben-chi",
        english: "bench",
        lao: "ມ້ານັ່ງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 벤치에 앉아 쉬었어요.",
                read: "Urineun benchi-e anja swieosseoyo.",
                english: "We sat on the bench and rested.",
                lao: "ພວກເຮົານັ່ງພັກຢູ່ທີ່ມ້ານັ່ງ.",
            },
        ],
    },
    {
        id: 4,
        korean: "연못",
        read: "yeon-mot",
        english: "pond",
        lao: "ສະນໍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "연못에 오리가 많이 있어요.",
                read: "Yeonmot-e origa mani iss-eoyo.",
                english: "There are many ducks in the pond.",
                lao: "ມີເປັດຫຼາຍຢູ່ໃນສະນໍ້າ.",
            },
        ],
    },
    {
        id: 5,
        korean: "산책로",
        read: "san-chaek-ro",
        english: "walking path",
        lao: "ທາງຍ່າງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "산책로를 따라 걸었습니다.",
                read: "Sanchaekro-reul ttara georeossseumnida.",
                english: "We walked along the walking path.",
                lao: "ພວກເຮົາຍ່າງຕາມທາງຍ່າງ.",
            },
        ],
    },
    {
        id: 6,
        korean: "잔디밭",
        read: "jan-di-bat",
        english: "lawn",
        lao: "ທົ່ງຫຍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들이 잔디밭에서 공을 차고 있어요.",
                read: "Aideul-i jandibat-eseo gong-eul chago iss-eoyo.",
                english: "Children are playing ball on the lawn.",
                lao: "ເດັກນ້ອຍກຳລັງຫຼິ້ນບານຢູ່ໃນທົ່ງຫຍ້າ.",
            },
        ],
    },
    {
        id: 7,
        korean: "피크닉",
        read: "pi-keu-nik",
        english: "picnic",
        lao: "ປິກນິກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 공원에서 피크닉을 했습니다.",
                read: "Urineun gongwon-eseo pikeunik-eul haessseumnida.",
                english: "We had a picnic in the park.",
                lao: "ພວກເຮົາໄດ້ໄປປິກນິກຢູ່ສວນສາທາລະນະ.",
            },
        ],
    },
    {
        id: 8,
        korean: "자전거 도로",
        read: "ja-jeon-geo do-ro",
        english: "bike path",
        lao: "ທາງລົດຖີບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이 공원에는 자전거 도로가 있습니다.",
                read: "I gongwon-eneun jajeongeo doro-ga issseumnida.",
                english: "This park has a bike path.",
                lao: "ສວນນີ້ມີທາງລົດຖີບ.",
            },
        ],
    },
    {
        id: 9,
        korean: "정자",
        read: "jeong-ja",
        english: "pavilion",
        lao: "ສາລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 정자에서 휴식을 취했습니다.",
                read: "Urineun jeongja-eseo hyusig-eul chwihassseumnida.",
                english: "We took a rest in the pavilion.",
                lao: "ພວກເຮົາພັກຢູ່ທີ່ສາລາ.",
            },
        ],
    },
    {
        id: 10,
        korean: "분수",
        read: "bun-su",
        english: "fountain",
        lao: "ນ້ຳພຸ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들은 분수에서 물놀이를 즐깁니다.",
                read: "Aideul-eun bunsu-eseo mulnoli-reul jeulgimnida.",
                english: "Children enjoy playing in the fountain.",
                lao: "ເດັກນ້ອຍມັກຫຼິ້ນນ້ຳຢູ່ນ້ຳພຸ.",
            },
        ],
    },
    {
        id: 11,
        korean: "꽃밭",
        read: "kkotbat",
        english: "flower bed",
        lao: "ສວນດອກໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "꽃밭은 다양한 꽃들로 가득 차 있습니다.",
                read: "Kkotbat-eun dayanghan kkotdeul-lo gadeug cha issseumnida.",
                english: "The flower bed is filled with various flowers.",
                lao: "ສວນດອກໄມ້ເຕັມໄປດ້ວຍດອກໄມ້ຕ່າງໆ.",
            },
        ],
    },
    {
        id: 12,
        korean: "놀이터",
        read: "nol-i-teo",
        english: "playground",
        lao: "ສະຫນາມຫຼິ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들은 놀이터에서 즐겁게 놀고 있습니다.",
                read: "Aideul-eun noleiteo-eseo jeulgobge nolgo issseumnida.",
                english: "Children are having fun at the playground.",
                lao: "ເດັກນ້ອຍກຳລັງຫຼິ້ນຢ່າງມ່ວນຊື່ນຢູ່ທີ່ສະຫນາມຫຼິ້ນ.",
            },
        ],
    },
    {
        id: 13,
        korean: "운동장",
        read: "un-dong-jang",
        english: "sports field",
        lao: "ສະຫນາມກິລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "운동장에서 축구 경기를 했습니다.",
                read: "Undongjang-eseo chukgu gyeonggi-reul haessseumnida.",
                english: "We played a soccer game at the sports field.",
                lao: "ພວກເຮົາເຕະບານຢູ່ສະຫນາມກິລາ.",
            },
        ],
    },
    {
        id: 14,
        korean: "호수",
        read: "ho-su",
        english: "lake",
        lao: "ທະເລສາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "호수 주변을 산책했습니다.",
                read: "Hosujubyeon-eul sanchaekhaessseumnida.",
                english: "We took a walk around the lake.",
                lao: "ພວກເຮົາຍ່າງຫຼິ້ນຮອບທະເລສາບ.",
            },
        ],
    },
    {
        id: 15,
        korean: "야외 극장",
        read: "ya-oe geug-jang",
        english: "outdoor theater",
        lao: "ໂຮງຫນັງກາງແຈ້ງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 야외 극장에서 영화를 보았습니다.",
                read: "Urineun yaoe geugjang-eseo yeonghwa-reul boasnida.",
                english: "We watched a movie at the outdoor theater.",
                lao: "ພວກເຮົາເບິ່ງຫນັງຢູ່ໂຮງຫນັງກາງແຈ້ງ.",
            },
        ],
    },
];
