import type { WordModel } from "~/models";

export const ABOUT_HOUSE_LIVING_DINING: WordModel[] = [
    {
        id: 1,
        korean: "거실",
        read: "geo-sil",
        english: "living room",
        lao: "ຫ້ອງນັ່ງຫຼິ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거실에서 가족과 시간을 보냈어요.",
                read: "Geo-sil-e-seo ga-jok-gwa si-gan-eul bo-naess-eo-yo.",
                english: "I spent time with my family in the living room.",
                lao: "ຂ້ອຍໃຊ້ເວລາກັບຄອບຄົວໃນຫ້ອງນັ່ງຫຼິ້ນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "소파",
        read: "so-pa",
        english: "sofa",
        lao: "ໂຊຟາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "소파에 앉아서 책을 읽었어요.",
                read: "So-pa-e an-ja-seo chaek-eul il-geoss-eo-yo.",
                english: "I sat on the sofa and read a book.",
                lao: "ຂ້ອຍນັ່ງໂຊຟາ ແລະ ອ່ານປື້ມ.",
            },
        ],
    },
    {
        id: 3,
        korean: "텔레비전",
        read: "tel-le-bi-jeon",
        english: "television",
        lao: "ໂທລະທັດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "텔레비전에서 뉴스를 봤어요.",
                read: "Tel-le-bi-jeon-e-seo nyu-seu-reul bwass-eo-yo.",
                english: "I watched the news on the television.",
                lao: "ຂ້ອຍເບິ່ງຂ່າວທາງໂທລະທັດ.",
            },
        ],
    },
    {
        id: 4,
        korean: "탁자",
        read: "tak-ja",
        english: "coffee table",
        lao: "ໂຕະເດີ່ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "탁자 위에 잡지를 놓았어요.",
                read: "Tak-ja wi-e jap-ji-reul noh-ass-eo-yo.",
                english: "I placed a magazine on the coffee table.",
                lao: "ຂ້ອຍວາງນິຕະສານໄວ້ບົດໂຕະເດີ່ມ.",
            },
        ],
    },
    {
        id: 5,
        korean: "램프",
        read: "laem-peu",
        english: "lamp",
        lao: "ໂຄມໄຟ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "램프를 켰어요.",
                read: "Laem-peu-reul kyeoss-eo-yo.",
                english: "I turned on the lamp.",
                lao: "ຂ້ອຍເປີດໂຄມໄຟ.",
            },
        ],
    },
    {
        id: 6,
        korean: "커튼",
        read: "keo-teun",
        english: "curtain",
        lao: "ຜ້າມ່ານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "커튼을 열었어요.",
                read: "Keo-teun-eul yeol-eoss-eo-yo.",
                english: "I opened the curtains.",
                lao: "ຂ້ອຍເປີດຜ້າມ່ານ.",
            },
        ],
    },
    {
        id: 7,
        korean: "카펫",
        read: "ka-pet",
        english: "carpet",
        lao: "ພື້ນປູເປົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "카펫을 청소했어요.",
                read: "Ka-pet-eul cheong-so-haess-eo-yo.",
                english: "I cleaned the carpet.",
                lao: "ຂ້ອຍທຳຄວາມສະອາດພື້ນປູເປົ້າ.",
            },
        ],
    },
    {
        id: 8,
        korean: "책장",
        read: "chaek-jang",
        english: "bookshelf",
        lao: "ຊັ້ນວາງປື້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "책을 책장에 정리했어요.",
                read: "Chaek-eul chaek-jang-e jeong-ni-haess-eo-yo.",
                english: "I organized the books on the bookshelf.",
                lao: "ຂ້ອຍຈັດໝູ່ປື້ມຢູ່ຊັ້ນວາງປື້ມ.",
            },
        ],
    },
    {
        id: 9,
        korean: "액자",
        read: "aek-ja",
        english: "picture frame",
        lao: "ກອບຮູບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "사진을 액자에 넣었어요.",
                read: "Sa-jin-eul aek-ja-e neoh-eoss-eo-yo.",
                english: "I put the picture in the frame.",
                lao: "ຂ້ອຍເອົາຮູບໃສ່ກອບ.",
            },
        ],
    },
    {
        id: 10,
        korean: "화분",
        read: "hwa-bun",
        english: "flowerpot",
        lao: "ກະຖາງດອກໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "화분에 물을 주었어요.",
                read: "Hwa-bun-e mul-eul ju-eoss-eo-yo.",
                english: "I watered the flowerpot.",
                lao: "ຂ້ອຍໄດ້ລາດນ້ຳກະຖາງດອກໄມ້.",
            },
        ],
    },
    {
        id: 11,
        korean: "식탁",
        read: "sik-tak",
        english: "dining table",
        lao: "ໂຕະອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 식탁에서 저녁을 먹었어요.",
                read: "U-ri-neun sik-tak-e-seo jeo-nyeog-eul meog-eoss-eo-yo.",
                english: "We ate dinner at the dining table.",
                lao: "ພວກເຮົາກິນມື້ແລງຢູ່ໂຕະອາຫານ.",
            },
        ],
    },
    {
        id: 12,
        korean: "식탁 의자",
        read: "sik-tak ui-ja",
        english: "dining chair",
        lao: "ເກົ້າອີ້ອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식탁 의자에 앉아서 식사를 했어요.",
                read: "Sik-tak ui-ja-e an-ja-seo sik-sa-reul haess-eo-yo.",
                english: "I sat on the dining chair and had a meal.",
                lao: "ຂ້ອຍນັ່ງເກົ້າອີ້ອາຫານແລະກິນເຂົ້າ.",
            },
        ],
    },
    {
        id: 13,
        korean: "식기",
        read: "sik-gi",
        english: "dishes",
        lao: "ຈານເຂົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식기를 설거지했어요.",
                read: "Sik-gi-reul seol-geo-ji-haess-eo-yo.",
                english: "I washed the dishes.",
                lao: "ຂ້ອຍລ້າງຈານເຂົ້າ.",
            },
        ],
    },
    {
        id: 14,
        korean: "식기 세척기",
        read: "sik-gi se-cheog-gi",
        english: "dishwasher",
        lao: "ເຄື່ອງລ້າງຈານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식기 세척기에 식기를 넣었어요.",
                read: "Sik-gi se-cheog-gi-e sik-gi-reul neoh-eoss-eo-yo.",
                english: "I put the dishes in the dishwasher.",
                lao: "ຂ້ອຍເອົາຈານເຂົ້າໃສ່ເຄື່ອງລ້າງຈານ.",
            },
        ],
    },
    {
        id: 15,
        korean: "식탁보",
        read: "sik-tak-bo",
        english: "tablecloth",
        lao: "ຜ້າປູໂຕະ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식탁보를 깔았어요.",
                read: "Sik-tak-bo-reul kkar-ass-eo-yo.",
                english: "I laid out the tablecloth.",
                lao: "ຂ້ອຍປູຜ້າປູໂຕະ.",
            },
        ],
    },
];
