import type { WordModel } from "~/models";

export const ABOUT_POSITION_DIRECTION: WordModel[] = [
    {
        id: 1,
        korean: "위",
        read: "wi",
        english: "above",
        lao: "ເທິງ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "책은 책상 위에 있습니다.",
                read: "Chaekeun chaeksang wie itsseumnida.",
                english: "The book is on the desk.",
                lao: "ປື້ມຢູ່ເທິງໂຕະ.",
            },
        ],
    },
    {
        id: 2,
        korean: "아래",
        read: "arae",
        english: "below",
        lao: "ລຸ່ມ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "고양이가 책상 아래에 있습니다.",
                read: "Goyang-i-ga chaeksang arae-e itsseumnida.",
                english: "The cat is under the desk.",
                lao: "ແມວຢູ່ລຸ່ມໂຕະ.",
            },
        ],
    },
    {
        id: 3,
        korean: "앞",
        read: "ap",
        english: "front",
        lao: "ຫນ້າ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "자동차가 집 앞에 있습니다.",
                read: "Jadongchaga jip ape itsseumnida.",
                english: "The car is in front of the house.",
                lao: "ລົດຢູ່ຫນ້າບ້ານ.",
            },
        ],
    },
    {
        id: 4,
        korean: "뒤",
        read: "dwi",
        english: "behind",
        lao: "ຫລັງ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "개가 나무 뒤에 있습니다.",
                read: "Gaega namu dwie itsseumnida.",
                english: "The dog is behind the tree.",
                lao: "ຫມາຢູ່ຫລັງຕົ້ນໄມ້.",
            },
        ],
    },
    {
        id: 5,
        korean: "옆",
        read: "yeop",
        english: "beside",
        lao: "ຂ້າງ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "의자가 책상 옆에 있습니다.",
                read: "Uijaga chaeksang yeope itsseumnida.",
                english: "The chair is beside the desk.",
                lao: "ເກົ້າອີ້ຢູ່ຂ້າງໂຕະ.",
            },
        ],
    },
    {
        id: 6,
        korean: "안",
        read: "an",
        english: "inside",
        lao: "ຂ້າງໃນ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "고양이가 상자 안에 있습니다.",
                read: "Goyang-i-ga sangja an-e itsseumnida.",
                english: "The cat is inside the box.",
                lao: "ແມວຢູ່ຂ້າງໃນກ່ອງ.",
            },
        ],
    },
    {
        id: 7,
        korean: "밖",
        read: "bak",
        english: "outside",
        lao: "ຂ້າງນອກ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "강아지가 집 밖에 있습니다.",
                read: "Gang-ajiga jip bak-e itsseumnida.",
                english: "The puppy is outside the house.",
                lao: "ໝານ້ອຍຢູ່ຂ້າງນອກບ້ານ.",
            },
        ],
    },
    {
        id: 8,
        korean: "가운데",
        read: "gaunde",
        english: "middle",
        lao: "ກາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "테이블 가운데 꽃이 있습니다.",
                read: "Teibeul gaunde kkochi itsseumnida.",
                english: "There is a flower in the middle of the table.",
                lao: "ມີດອກໄມ້ຢູ່ກາງໂຕະ.",
            },
        ],
    },
    {
        id: 9,
        korean: "왼쪽",
        read: "oenjjok",
        english: "left",
        lao: "ຂ້າງຊ້າຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나무는 길의 왼쪽에 있습니다.",
                read: "Namuneun gil-ui oenjjog-e itsseumnida.",
                english: "The tree is on the left side of the road.",
                lao: "ຕົ້ນໄມ້ຢູ່ຂ້າງຊ້າຍຂອງຖະໜົນ.",
            },
        ],
    },
    {
        id: 10,
        korean: "오른쪽",
        read: "oreunjjok",
        english: "right",
        lao: "ຂ້າງຂວາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우체국은 길의 오른쪽에 있습니다.",
                read: "Uchegug-eun gil-ui oreunjjog-e itsseumnida.",
                english: "The post office is on the right side of the road.",
                lao: "ບໍລິສັດຢູ່ຂ້າງຂວາຂອງຖະໜົນ.",
            },
        ],
    },
    {
        id: 11,
        korean: "북쪽",
        read: "bukjjok",
        english: "north",
        lao: "ເໜືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "산은 도시의 북쪽에 있습니다.",
                read: "Saneun dosi-ui bukjjok-e itsseumnida.",
                english: "The mountain is to the north of the city.",
                lao: "ພູຢູ່ເໜືອຂອງເມືອງ.",
            },
        ],
    },
    {
        id: 12,
        korean: "남쪽",
        read: "namjjok",
        english: "south",
        lao: "ໃຕ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "바다는 마을의 남쪽에 있습니다.",
                read: "Badaneun maeul-ui namjjok-e itsseumnida.",
                english: "The sea is to the south of the village.",
                lao: "ທະເລຢູ່ໃຕ້ຂອງບ້ານ.",
            },
        ],
    },
    {
        id: 13,
        korean: "동쪽",
        read: "dongjjok",
        english: "east",
        lao: "ຕາເວັນອອກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "해는 동쪽에서 뜹니다.",
                read: "Haeneun dongjjok-eseo tteumnida.",
                english: "The sun rises in the east.",
                lao: "ຕາເວັນຂື້ນຢູ່ທາງຕາເວັນອອກ.",
            },
        ],
    },
    {
        id: 14,
        korean: "서쪽",
        read: "seojjok",
        english: "west",
        lao: "ຕາເວັນຕົກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "해는 서쪽으로 집니다.",
                read: "Haeneun seojjog-euro jimnida.",
                english: "The sun sets in the west.",
                lao: "ຕາເວັນຕົກຢູ່ທາງຕາເວັນຕົກ.",
            },
        ],
    },
    {
        id: 15,
        korean: "근처",
        read: "geuncheo",
        english: "near",
        lao: "ໃກ້",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "학교 근처에 공원이 있습니다.",
                read: "Hakgyo geuncheoe gongwoni itsseumnida.",
                english: "There is a park near the school.",
                lao: "ມີສວນຢູ່ໃກ້ໂຮງຮຽນ.",
            },
        ],
    },
    {
        id: 16,
        korean: "멀리",
        read: "meolli",
        english: "far",
        lao: "ໄກ",
        speech: "adv",
        examples: [
            {
                id: 1,
                korean: "도서관은 여기서 멀리 있습니다.",
                read: "Doseogwaneun yeogiseo meolli itsseumnida.",
                english: "The library is far from here.",
                lao: "ຫ້ອງສະໝຸດໄກຈາກທີ່ນີ້.",
            },
        ],
    },
    {
        id: 17,
        korean: "가까이",
        read: "gakkai",
        english: "close",
        lao: "ໃກ້",
        speech: "adv",
        examples: [
            {
                id: 1,
                korean: "우리는 역 가까이에 살고 있습니다.",
                read: "Urineun yeog gakkaie salgo itsseumnida.",
                english: "We live close to the station.",
                lao: "ພວກເຮົາຢູ່ໃກ້ສະຖານີ.",
            },
        ],
    },
    {
        id: 18,
        korean: "바깥",
        read: "bagat",
        english: "outside",
        lao: "ຂ້າງນອກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들이 바깥에서 놀고 있습니다.",
                read: "Aideuli baggat-eseo nolgo itsseumnida.",
                english: "The children are playing outside.",
                lao: "ເດັກໆກຳລັງຫຼິ້ນຢູ່ຂ້າງນອກ.",
            },
        ],
    },
    {
        id: 19,
        korean: "내부",
        read: "naebu",
        english: "inside",
        lao: "ຂ້າງໃນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "건물 내부는 아주 깨끗합니다.",
                read: "Geonmul naebuneun aju kkaekkeutamnida.",
                english: "The inside of the building is very clean.",
                lao: "ຂ້າງໃນອາຄານສະອາດຫຼາຍ.",
            },
        ],
    },
    {
        id: 20,
        korean: "중앙",
        read: "jung-ang",
        english: "center",
        lao: "ກາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도시는 중앙에 큰 공원이 있습니다.",
                read: "Dosineun jung-ange keun gongwoni itsseumnida.",
                english: "The city has a large park in the center.",
                lao: "ເມືອງມີສວນໃຫຍ່ຢູ່ກາງ.",
            },
        ],
    },
    {
        id: 21,
        korean: "위쪽",
        read: "wijjok",
        english: "top",
        lao: "ດ້ານເທິງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "산의 위쪽은 눈으로 덮여 있습니다.",
                read: "San-ui wijjogeun nun-euro deop-yeo itsseumnida.",
                english: "The top of the mountain is covered with snow.",
                lao: "ສວນດ້ານເທິງຂອງພູເປັນຂອງແມ່ນເທົາໃສ່.",
            },
        ],
    },
    {
        id: 22,
        korean: "옆",
        read: "yeop",
        english: "next to",
        lao: "ຂ້າງ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "은행은 가게 옆에 있습니다.",
                read: "Eunhaeng-eun gage yeope itsseumnida.",
                english: "The bank is next to the store.",
                lao: "ທະນາຄານຢູ່ຂ້າງຮ້ານ.",
            },
        ],
    },
    {
        id: 23,
        korean: "아래쪽",
        read: "araejjok",
        english: "down",
        lao: "ລຸ່ມ",
        speech: "prep",
        examples: [
            {
                id: 1,
                korean: "강은 언덕 아래쪽에 있습니다.",
                read: "Gang-eun eondeog araejjog-e itsseumnida.",
                english: "The river is down the hill.",
                lao: "ແມ່ນ້ຳຢູ່ລຸ່ມພູ.",
            },
        ],
    },
];
