import type { WordModel } from "~/models";

export const ABOUT_CLINIC: WordModel[] = [
    {
        id: 1,
        korean: "클리닉",
        read: "keul-li-nik",
        english: "clinic",
        lao: "ຄລີນິກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 클리닉에 갑니다.",
                read: "Jeoneun keul-li-nik-e gamnida.",
                english: "I go to the clinic.",
                lao: "ຂ້ອຍໄປທີ່ຄລີນິກ.",
            },
        ],
    },
    {
        id: 2,
        korean: "의사",
        read: "ui-sa",
        english: "doctor",
        lao: "ທ່ານໝໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사와 상담합니다.",
                read: "Uisa-wa sang-dam-ham-ni-da.",
                english: "I consult with the doctor.",
                lao: "ຂ້ອຍປຶກສາກັບໝໍ.",
            },
        ],
    },
    {
        id: 3,
        korean: "간호사",
        read: "gan-ho-sa",
        english: "nurse",
        lao: "ນາງພະຍາບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "간호사가 도와줍니다.",
                read: "Gan-ho-sa-ga do-wa-jum-ni-da.",
                english: "The nurse helps me.",
                lao: "ນາງພະຍາບານຊ່ວຍຂ້ອຍ.",
            },
        ],
    },
    {
        id: 4,
        korean: "진료실",
        read: "jin-lyo-sil",
        english: "consultation room",
        lao: "ຫ້ອງກວດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "진료실에서 기다립니다.",
                read: "Jin-lyo-sil-e-seo gi-da-rim-ni-da.",
                english: "I wait in the consultation room.",
                lao: "ຂ້ອຍລໍຖ້າຢູ່ຫ້ອງກວດ.",
            },
        ],
    },
    {
        id: 5,
        korean: "예약",
        read: "ye-yak",
        english: "appointment",
        lao: "ນັດໝາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "예약을 합니다.",
                read: "Ye-yak-eul ham-ni-da.",
                english: "I make an appointment.",
                lao: "ຂ້ອຍນັດໝາຍ.",
            },
        ],
    },
    {
        id: 6,
        korean: "진찰",
        read: "jin-chal",
        english: "examination",
        lao: "ການກວດຕ່າງໆ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사가 진찰을 합니다.",
                read: "Ui-sa-ga jin-chal-eul ham-ni-da.",
                english: "The doctor conducts an examination.",
                lao: "ໝໍໄດ້ກວດຕ່າງໆ.",
            },
        ],
    },
    {
        id: 7,
        korean: "진단",
        read: "jin-dan",
        english: "diagnosis",
        lao: "ການວິນິດໄສ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "진단을 받았습니다.",
                read: "Jin-dan-eul bad-ass-eum-ni-da.",
                english: "I received a diagnosis.",
                lao: "ຂ້ອຍໄດ້ຮັບການວິນິດໄສ.",
            },
        ],
    },
    {
        id: 8,
        korean: "치료",
        read: "chi-ryo",
        english: "treatment",
        lao: "ການຮັກສາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "치료가 필요합니다.",
                read: "Chi-ryo-ga pil-yo-ham-ni-da.",
                english: "I need treatment.",
                lao: "ຂ້ອຍຕ້ອງການການຮັກສາ.",
            },
        ],
    },
    {
        id: 9,
        korean: "백신",
        read: "baek-sin",
        english: "vaccine",
        lao: "ວັກຊີນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "백신을 맞았습니다.",
                read: "Baek-sin-eul maj-ass-eum-ni-da.",
                english: "I received a vaccine.",
                lao: "ຂ້ອຍໄດ້ຮັບວັກຊີນ.",
            },
        ],
    },
    {
        id: 10,
        korean: "주사",
        read: "ju-sa",
        english: "injection",
        lao: "ການສັກຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "주사를 맞았습니다.",
                read: "Ju-sa-reul maj-ass-eum-ni-da.",
                english: "I received an injection.",
                lao: "ຂ້ອຍໄດ້ຮັບການສັກຢາ.",
            },
        ],
    },
    {
        id: 11,
        korean: "검사",
        read: "geom-sa",
        english: "test",
        lao: "ການກວດສອບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사가 혈액 검사를 했습니다.",
                read: "Uisa-ga hyeolaek geomsa-reul haesseum-ni-da.",
                english: "The doctor performed a blood test.",
                lao: "ໝໍໄດ້ກວດລອດເລືອດ.",
            },
        ],
    },
    {
        id: 12,
        korean: "건강",
        read: "geon-gang",
        english: "health",
        lao: "ສຸຂະພາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "건강을 유지하세요.",
                read: "Geon-gang-eul yuji-ha-se-yo.",
                english: "Maintain your health.",
                lao: "ຮັກສາສຸຂະພາບຂອງເຈົ້າໄວ້.",
            },
        ],
    },
    {
        id: 13,
        korean: "건강보험",
        read: "geon-gang-bo-heom",
        english: "health insurance",
        lao: "ປະກັນສຸຂະພາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "건강보험이 있나요?",
                read: "Geon-gang-bo-heom-i iss-na-yo?",
                english: "Do you have health insurance?",
                lao: "ເຈົ້າມີປະກັນສຸຂະພາບບໍ?",
            },
        ],
    },
    {
        id: 14,
        korean: "처방전",
        read: "cheo-bang-jeon",
        english: "prescription",
        lao: "ໃບສັ່ງຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사가 처방전을 썼습니다.",
                read: "Uisa-ga cheobangjeon-eul sseoss-eum-ni-da.",
                english: "The doctor wrote a prescription.",
                lao: "ໝໍໄດ້ຂຽນໃບສັ່ງຢາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "접수",
        read: "jeop-su",
        english: "reception",
        lao: "ການຕ້ອນຮັບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "접수에서 안내를 받았습니다.",
                read: "Jeop-su-e-seo an-nae-reul bad-ass-eum-ni-da.",
                english: "I received guidance at the reception.",
                lao: "ຂ້ອຍໄດ້ຮັບການແນະນໍາທີ່ການຕ້ອນຮັບ.",
            },
        ],
    },
];
