import type { WordModel } from "~/models";

export const ABOUT_RIVER_SEA_OCEAN: WordModel[] = [
    {
        id: 1,
        korean: "강",
        read: "gang",
        english: "river",
        lao: "ແມ່ນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "한강은 서울을 흐릅니다.",
                read: "han-gang-eun seo-ul-eul heu-reum-ni-da.",
                english: "The Han River flows through Seoul.",
                lao: "ແມ່ນ້ໍາຮານໄຫຼຜ່ານໂຊລ.",
            },
        ],
    },
    {
        id: 2,
        korean: "강변",
        read: "gangbyeon",
        english: "river bank",
        lao: "ຕີຝັ່ງແມ່ນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "강변에서 산책을 즐겼습니다.",
                read: "gangbyeon-eseo sanchaek-eul jeulgyeossseumnida.",
                english: "I enjoyed a walk along the river bank.",
                lao: "ຂ້ອຍໄດ້ສົນທະນາທີ່ຕີຝັ່ງແມ່ນ້ໍາ.",
            },
        ],
    },
    {
        id: 3,
        korean: "배",
        read: "bae",
        english: "boat",
        lao: "ເຮືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 배를 타고 호수를 건넜습니다.",
                read: "u-ri-neun bae-reul ta-go ho-su-reul geon-neoss-seum-ni-da.",
                english: "We crossed the lake by boat.",
                lao: "ພວກເຮົາໄດ້ນັ່ງເຮືອຂ້າມທະເລສາບ.",
            },
        ],
    },
    {
        id: 4,
        korean: "호수",
        read: "hosu",
        english: "lake",
        lao: "ທະເລສາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "호수는 매우 아름다웠습니다.",
                read: "ho-su-neun mae-u a-reum-da-woss-seum-ni-da.",
                english: "The lake was very beautiful.",
                lao: "ທະເລສາບງາມຫຼາຍ.",
            },
        ],
    },
    {
        id: 5,
        korean: "연못",
        read: "yeonmot",
        english: "pond",
        lao: "ບໍ່ນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "연못에는 물고기가 많습니다.",
                read: "yeonmot-eneun mulgogi-ga manh-seum-ni-da.",
                english: "There are many fish in the pond.",
                lao: "ມີປາຫຼາຍຢູ່ໃນບໍ່ນ້ໍາ.",
            },
        ],
    },
    {
        id: 6,
        korean: "바다",
        read: "ba-da",
        english: "sea",
        lao: "ທະເລ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 여름에 바다로 여행을 갑니다.",
                read: "u-ri-neun yeo-reum-e ba-da-ro yeo-haeng-eul gam-ni-da.",
                english: "We travel to the sea in the summer.",
                lao: "ພວກເຮົາທ່ຽວໄປທະເລໃນລະດູຮ້ອນ.",
            },
        ],
    },
    {
        id: 7,
        korean: "바닷가",
        read: "ba-dat-ga",
        english: "seashore",
        lao: "ຊາຍຫາດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "바닷가에서 산책을 합니다.",
                read: "ba-dat-ga-e-seo san-chaek-eul ham-ni-da.",
                english: "We take a walk on the seashore.",
                lao: "ພວກເຮົາຍ່າງຢູ່ຊາຍຫາດ.",
            },
        ],
    },
    {
        id: 8,
        korean: "해변",
        read: "hae-byeon",
        english: "beach",
        lao: "ຊາຍຫາດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "여름에 해변에서 놀았습니다.",
                read: "yeo-reum-e hae-byeon-e-seo nol-at-seum-ni-da.",
                english: "We played on the beach in the summer.",
                lao: "ພວກເຮົາຫລິ້ນຢູ່ຊາຍຫາດໃນລະດູຮ້ອນ.",
            },
        ],
    },
    {
        id: 9,
        korean: "파도",
        read: "pa-do",
        english: "wave",
        lao: "ເກີດຄື້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "파도가 높이 일렁입니다.",
                read: "pa-do-ga nop-hi il-leong-im-ni-da.",
                english: "The waves are high and rolling.",
                lao: "ຄື້ນນ້ໍາສູງແລະກຳລັງໄຫລ.",
            },
        ],
    },
    {
        id: 10,
        korean: "바다 깊이",
        read: "ba-da gip-hi",
        english: "sea depth",
        lao: "ຄວາມລຶກຂອງທະເລ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "바다 깊이는 매우 깊습니다.",
                read: "ba-da gip-hi-neun mae-u gip-seum-ni-da.",
                english: "The sea depth is very deep.",
                lao: "ຄວາມລຶກຂອງທະເລຫລາຍຫຼາຍ.",
            },
        ],
    },
    {
        id: 11,
        korean: "수영",
        read: "su-yeong",
        english: "swimming",
        lao: "ການລອຍນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "여름에는 바다에서 수영을 즐깁니다.",
                read: "yeo-reum-e-neun ba-da-e-seo su-yeong-eul jeul-gim-ni-da.",
                english: "In the summer, we enjoy swimming in the sea.",
                lao: "ໃນລະດູຮ້ອນ, ພວກເຮົາເພີດເພີນກັບການລອຍນ້ໍາໃນທະເລ.",
            },
        ],
    },
    {
        id: 12,
        korean: "모래",
        read: "mo-rae",
        english: "sand",
        lao: "ຊາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "해변 모래가 부드럽습니다.",
                read: "hae-byeon mo-rae-ga bu-deu-reob-seum-ni-da.",
                english: "The beach sand is soft.",
                lao: "ຊາຍທະເລມີຄວາມນຸ່ມ.",
            },
        ],
    },
    {
        id: 13,
        korean: "조류",
        read: "jo-ryu",
        english: "tide",
        lao: "ກະແສນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "조류가 빠르게 변합니다.",
                read: "jo-ryu-ga ppa-reu-ge byeon-ham-ni-da.",
                english: "The tide changes rapidly.",
                lao: "ກະແສນ້ໍາປ່ຽນຢ່າງໄວວາ.",
            },
        ],
    },
    {
        id: 14,
        korean: "해양",
        read: "hae-yang",
        english: "ocean",
        lao: "ມະຫາສະມຸດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "해양은 지구의 대부분을 차지합니다.",
                read: "hae-yang-eun ji-gu-ui dae-bu-bun-eul cha-ji-ham-ni-da.",
                english: "The ocean covers most of the Earth's surface.",
                lao: "ມະຫາສະມຸດຄອບຄຸມພື້ນທີ່ສ່ວນໃຫຍ່ຂອງໂລກ.",
            },
        ],
    },
];
