import type { WordModel } from "~/models";

export const ABOUT_BUGS_AND_INSECTS: WordModel[] = [
    {
        id: 1,
        korean: "벌레",
        read: "beol-le",
        english: "bug",
        lao: "ແມງ​ໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벌레가 방 안에 있습니다.",
                read: "beol-le-ga bang an-e it-seum-ni-da.",
                english: "There is a bug in the room.",
                lao: "ມີແມງຢູ່ໃນຫ້ອງ.",
            },
        ],
    },
    {
        id: 2,
        korean: "곤충",
        read: "gon-chung",
        english: "insect",
        lao: "ແມງ​ໄມ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "곤충을 관찰하는 것이 재미있어요.",
                read: "gon-chung-eul gwan-chal-ha-neun geo-si jae-mi-it-seo-yo.",
                english: "It's interesting to observe insects.",
                lao: "ການສັງເກດແມງແມ່ນນ່າສົນໃຈ.",
            },
        ],
    },
    {
        id: 3,
        korean: "나비",
        read: "na-bi",
        english: "butterfly",
        lao: "ແມງກະເບື້ອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나비가 꽃 위에 앉아 있습니다.",
                read: "na-bi-ga kkot wi-e an-ja it-seum-ni-da.",
                english: "A butterfly is sitting on the flower.",
                lao: "ແມງກະເບື້ອຢູ່ເທິງດອກໄມ້.",
            },
        ],
    },
    {
        id: 4,
        korean: "벌",
        read: "beol",
        english: "bee",
        lao: "ເຜິ້ງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벌이 꽃에서 꿀을 모으고 있습니다.",
                read: "beol-i kkot-e-seo kkul-eul mo-eu-go it-seum-ni-da.",
                english: "The bee is gathering nectar from the flower.",
                lao: "ເຜິ້ງກຳລັງເກັບນ້ໍາເມົາຈາກດອກໄມ້.",
            },
        ],
    },
    {
        id: 5,
        korean: "개미",
        read: "gae-mi",
        english: "ant",
        lao: "ມົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "개미들이 땅에서 열심히 일하고 있습니다.",
                read: "gae-mi-deul-i ttang-e-seo yeol-sim-hi il-ha-go it-seum-ni-da.",
                english: "The ants are working hard on the ground.",
                lao: "ມົດກຳລັງເຮັດວຽກຢ່າງຂະຫຍັນຢູ່ທີ່ດິນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "파리",
        read: "pa-ri",
        english: "fly",
        lao: "ແມງວັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "파리가 음식 주위에 날아다닙니다.",
                read: "pa-ri-ga eum-sik ju-wi-e nal-a-da-nim-ni-da.",
                english: "The fly is buzzing around the food.",
                lao: "ແມງວັນບິນວຽນໆຢູ່ຮອບອາຫານ.",
            },
        ],
    },
    {
        id: 7,
        korean: "모기",
        read: "mo-gi",
        english: "mosquito",
        lao: "ຍຸງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "모기가 물지 않도록 조심하세요.",
                read: "mo-gi-ga mul-ji an-tok-ro jo-sim-ha-se-yo.",
                english: "Be careful not to get bitten by mosquitoes.",
                lao: "ລະວັງຢ່າໃຫ້ຍຸງກັດ.",
            },
        ],
    },
    {
        id: 8,
        korean: "메뚜기",
        read: "me-ttu-gi",
        english: "grasshopper",
        lao: "ຕັກແຕນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "메뚜기가 풀밭에서 뛰어다니고 있습니다.",
                read: "me-ttu-gi-ga pul-bat-e-seo ttu-i-eo-da-ni-go it-seum-ni-da.",
                english: "The grasshopper is hopping in the meadow.",
                lao: "ຕັກແຕນກຳລັງກະໂດດຢູ່ໃນທົ່ງຫຍ້າ.",
            },
        ],
    },
    {
        id: 9,
        korean: "잠자리",
        read: "jam-ja-ri",
        english: "dragonfly",
        lao: "ແມງປໍ້ງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "잠자리가 연못 위를 날아다니고 있습니다.",
                read: "jam-ja-ri-ga yeon-mot wi-reul nal-a-da-ni-go it-seum-ni-da.",
                english: "The dragonfly is flying over the pond.",
                lao: "ແມງປໍ້ງບິນຢູ່ເທິງສະເໝີ.",
            },
        ],
    },
    {
        id: 10,
        korean: "무당벌레",
        read: "mu-dang-beol-le",
        english: "ladybug",
        lao: "ແມງມຸມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "무당벌레가 잎 위를 기어가고 있습니다.",
                read: "mu-dang-beol-le-ga ip wi-reul gi-eo-ga-go it-seum-ni-da.",
                english: "The ladybug is crawling on the leaf.",
                lao: "ແມງມຸມກຳລັງເດີນຢູ່ເທິງໃບໄມ້.",
            },
        ],
    },
    {
        id: 11,
        korean: "지네",
        read: "ji-ne",
        english: "centipede",
        lao: "ຂີ້ເຂັບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "지네가 빠르게 움직이고 있습니다.",
                read: "ji-ne-ga ppa-reu-ge um-jik-i-go it-seum-ni-da.",
                english: "The centipede is moving quickly.",
                lao: "ເຕິດຕະຈິ້ງກຳລັງເຄື່ອນໄຫວໄວ.",
            },
        ],
    },
    {
        id: 12,
        korean: "거미",
        read: "geo-mi",
        english: "spider",
        lao: "ແມງມຸມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거미가 거미줄을 짓고 있습니다.",
                read: "geo-mi-ga geo-mi-jul-eul jit-go it-seum-ni-da.",
                english: "The spider is spinning a web.",
                lao: "ແມງມຸມກຳລັງທໍ່ໃຍແມງມຸມ.",
            },
        ],
    },
    {
        id: 13,
        korean: "벌레",
        read: "beolle",
        english: "worm",
        lao: "ຮັກກະລີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벌레가 흙에서 기어 나왔어요.",
                read: "beolle-ga heulg-eseo gieo nawasseoyo.",
                english: "The worm crawled out of the dirt.",
                lao: "ຮັກກະລີມອນໃນເຕົາແຕ່ຈີ.",
            },
        ],
    },
    {
        id: 14,
        korean: "전갈",
        read: "jeongal",
        english: "scorpion",
        lao: "ແມງງອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "전갈은 독을 가지고 있습니다.",
                read: "jeongal-eun dog-eul gajigo issseumnida.",
                english: "Scorpions have venom.",
                lao: "ແມງງອດມີນົມ.",
            },
        ],
    },
    {
        id: 15,
        korean: "바퀴벌레",
        read: "bakwi-beolle",
        english: "cockroach",
        lao: "ນົມເຂົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "바퀴벌레가 부엌에 나왔어요.",
                read: "bakwi-beolle-ga bu-eok-e nawasseoyo.",
                english: "A cockroach came out in the kitchen.",
                lao: "ນົມເຂົ້າມອນທີ່ຄອມໂກ.",
            },
        ],
    },
];
