import type { WordModel } from "~/models";

export const ABOUT_FOOTBALL: WordModel[] = [
    {
        id: 1,
        korean: "골키퍼",
        read: "gol-ki-peo",
        english: "Goalkeeper",
        lao: "ຜູ້ຮັກສາປະຕູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "골키퍼가 공을 막았어요.",
                read: "Gol-ki-peo-ga gong-eul mag-ass-eo-yo.",
                english: "The goalkeeper saved the ball.",
                lao: "ຜູ້ຮັກສາປະຕູໄດ້ປ້ອງກັນລູກບານ.",
            },
        ],
    },
    {
        id: 2,
        korean: "수비수",
        read: "su-bi-su",
        english: "Defender",
        lao: "ຜູ້ຫລີ້ນກອງຫລັງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수비수가 상대 팀의 공격을 막았어요.",
                read: "Su-bi-su-ga sang-dae tim-ui gong-gyeok-eul mag-ass-eo-yo.",
                english: "The defender blocked the opposing team's attack.",
                lao: "ຜູ້ຫລີ້ນກອງຫລັງໄດ້ປ້ອງກັນການໂຈມຕີຂອງທີມຄູ່ຕໍ່ສູ້.",
            },
        ],
    },
    {
        id: 3,
        korean: "미드필더",
        read: "mi-deu-pil-deo",
        english: "Midfielder",
        lao: "ຜູ້ຫລີ້ນກອງກາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "미드필더가 패스를 잘 했어요.",
                read: "Mi-deu-pil-deo-ga pae-seu-reul jal haess-eo-yo.",
                english: "The midfielder made a great pass.",
                lao: "ຜູ້ຫລີ້ນກອງກາງສົ່ງບານໄດ້ດີ",
            },
        ],
    },
    {
        id: 4,
        korean: "공격수",
        read: "gong-gyeok-su",
        english: "Forward",
        lao: "ຜູ້ຫລີ້ນກອງຫນ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "공격수가 골을 넣었어요.",
                read: "Gong-gyeok-su-ga gol-eul neo-eoss-eo-yo.",
                english: "The forward scored a goal.",
                lao: "ຜູ້ຫລີ້ນກອງຫນ້າຍິ່ງໄດ້ເຕະປະຕູ.",
            },
        ],
    },
    {
        id: 5,
        korean: "코치",
        read: "ko-chi",
        english: "Coach",
        lao: "ຄູຝຶກສອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "코치가 팀을 지도해요.",
                read: "Ko-chi-ga tim-eul ji-do-hae-yo.",
                english: "The coach guides the team.",
                lao: "ຄູຝຶກສອນໄດ້ຊີ້ນຳທີມ.",
            },
        ],
    },
    {
        id: 6,
        korean: "주장",
        read: "ju-jang",
        english: "Captain",
        lao: "ຫົວໜ້າທີມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "주장이 팀을 이끌어요.",
                read: "Ju-jang-i tim-eul i-kkeul-eo-yo.",
                english: "The captain leads the team.",
                lao: "ຫົວໜ້າທີມໄດ້ນຳທີມ.",
            },
        ],
    },
    {
        id: 7,
        korean: "심판",
        read: "sim-pan",
        english: "Referee",
        lao: "ຜູ້ຕັດສິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "심판이 경기를 주재해요.",
                read: "Sim-pan-i gyeong-gi-reul ju-jae-hae-yo.",
                english: "The referee oversees the match.",
                lao: "ຜູ້ຕັດສິນໄດ້ຄຸ້ມເກມການແຂ່ງຂັນ.",
            },
        ],
    },
    {
        id: 8,
        korean: "경기장",
        read: "gyeong-gi-jang",
        english: "Stadium",
        lao: "ສະຫນາມກິລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "경기장에서 경기를 봤어요.",
                read: "Gyeong-gi-jang-e-seo gyeong-gi-reul bwass-eo-yo.",
                english: "I watched the match at the stadium.",
                lao: "ຂ້ອຍໄດ້ເບິ່ງການແຂ່ງຂັນທີ່ສະຫນາມກິລາ.",
            },
        ],
    },
    {
        id: 9,
        korean: "골",
        read: "gol",
        english: "Goal",
        lao: "ປະຕູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그가 골을 넣었어요.",
                read: "Geu-ga gol-eul neo-eoss-eo-yo.",
                english: "He scored a goal.",
                lao: "ລາວຍິ່ງໄດ້ເຕະປະຕູ.",
            },
        ],
    },
    {
        id: 10,
        korean: "패널티",
        read: "pae-neol-ti",
        english: "Penalty",
        lao: "ຈຸດໂທດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "패널티 킥을 얻었어요.",
                read: "Pae-neol-ti kig-eul eod-eoss-eo-yo.",
                english: "We got a penalty kick.",
                lao: "ພວກເຮົາໄດ້ເຕະຈຸດໂທດ.",
            },
        ],
    },
    {
        id: 11,
        korean: "코너킥",
        read: "ko-neo-kig",
        english: "Corner",
        lao: "ເຕະມຸມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "코너킥 기회를 얻었어요.",
                read: "Ko-neo-kig gi-hoe-reul eod-eoss-eo-yo.",
                english: "We got a corner kick opportunity.",
                lao: "ພວກເຮົາໄດ້ໂອກາດເຕະມຸມ.",
            },
        ],
    },
    {
        id: 12,
        korean: "오프사이드",
        read: "o-peu-sa-i-deu",
        english: "Offside",
        lao: "ລໍາໜ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그 선수는 오프사이드에 걸렸어요.",
                read: "Geu seon-su-neun o-peu-sa-i-deu-e geol-lyeoss-eo-yo.",
                english: "That player was caught offside.",
                lao: "ນັກກິລານັ້ນຖືກຈັບໄດ້ລໍາໜ້າ.",
            },
        ],
    },
    {
        id: 13,
        korean: "태클",
        read: "tae-keul",
        english: "Tackle",
        lao: "ແທກເກີນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 상대 선수에게 태클을 걸었어요.",
                read: "Geu-neun sang-dae seon-su-e-ge tae-keul-eul geol-eoss-eo-yo.",
                english: "He made a tackle on the opposing player.",
                lao: "ລາວໄດ້ແທກເກີນນັກກິລາຝ່າຍຄູ່ແຂ່ງ.",
            },
        ],
    },
    {
        id: 14,
        korean: "드리블",
        read: "deu-ri-beul",
        english: "Dribble",
        lao: "ລ້ຽມບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 공을 드리블했어요.",
                read: "Geu-neun gong-eul deu-ri-beul-haess-eo-yo.",
                english: "He dribbled the ball.",
                lao: "ລາວລ້ຽມບານ.",
            },
        ],
    },
    {
        id: 15,
        korean: "패스",
        read: "pae-seu",
        english: "Pass",
        lao: "ສົ່ງບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 팀 동료에게 패스를 했어요.",
                read: "Geu-neun tim dong-ryo-e-ge pae-seu-reul haess-eo-yo.",
                english: "He passed the ball to a teammate.",
                lao: "ລາວໄດ້ສົ່ງບານໃຫ້ກັບເພື່ອນຮ່ວມທີມ.",
            },
        ],
    },
    {
        id: 16,
        korean: "헤더",
        read: "he-deo",
        english: "Header",
        lao: "ໂຫຼດບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 코너킥을 헤더로 연결했어요.",
                read: "Geu-neun ko-neo-kig-eul he-deo-ro yeon-gyeol-haess-eo-yo.",
                english: "He connected the corner kick with a header.",
                lao: "ລາວໄດ້ໂຫຼດບານຈາກການເຕະມຸມ.",
            },
        ],
    },
    {
        id: 17,
        korean: "교체",
        read: "gyo-che",
        english: "Substitution",
        lao: "ການເປີ່ຍນຕົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "후반전에 교체가 있었어요.",
                read: "Hu-ban-jeon-e gyo-che-ga iss-eoss-eo-yo.",
                english: "There was a substitution in the second half.",
                lao: "ມີການເປີ່ຍນຕົວໃນຄອງຫລັງ.",
            },
        ],
    },
    {
        id: 18,
        korean: "경기",
        read: "gyeong-gi",
        english: "Match",
        lao: "ການແຂ່ງຂັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "경기가 시작되었어요.",
                read: "Gyeong-gi-ga si-jag-dwaess-eo-yo.",
                english: "The match has started.",
                lao: "ການແຂ່ງຂັນໄດ້ເລີ່ມແລ້ວ.",
            },
        ],
    },
    {
        id: 19,
        korean: "팬",
        read: "paen",
        english: "Fans",
        lao: "ແຟນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "팬들이 경기장에서 응원하고 있어요.",
                read: "Paen-deul-i gyeong-gi-jang-e-seo eung-won-ha-go iss-eo-yo.",
                english: "The fans are cheering in the stadium.",
                lao: "ແຟນໄດ້ເຊຍຊູ່ຢູ່ໃນສະຫນາມກິລາ.",
            },
        ],
    },
    {
        id: 20,
        korean: "트로피",
        read: "teu-ro-pi",
        english: "Trophy",
        lao: "ຖ້ວຍລາງວັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우승 팀은 트로피를 받았어요.",
                read: "U-seung tim-eun teu-ro-pi-reul bad-ass-eo-yo.",
                english: "The winning team received the trophy.",
                lao: "ທີມທີ່ຊະນະໄດ້ຮັບຖ້ວຍລາງວັນ.",
            },
        ],
    },
];
