import type { WordModel } from "~/models";

export const ABOUT_FOOD: WordModel[] = [
    {
        id: 1,
        korean: "음식",
        read: "eum-sik",
        english: "food",
        lao: "ອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "음식이 맛있습니다.",
                read: "Eumsig-i masissseumnida.",
                english: "The food is delicious.",
                lao: "ອາຫານອິ່ມຫວານຫວານ.",
            },
        ],
    },
    {
        id: 2,
        korean: "생선",
        read: "saeng-seon",
        english: "fish",
        lao: "ປາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 생선을 좋아합니다.",
                read: "Jeoneun saengseon-eul joahamnida.",
                english: "I like fish.",
                lao: "ຂ້ອຍມັກປາ.",
            },
        ],
    },
    {
        id: 3,
        korean: "빵",
        read: "ppang",
        english: "bread",
        lao: "ເຂົ້າຈີ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 빵을 먹었습니다.",
                read: "Achim-e ppang-eul meogeossseumnida.",
                english: "I ate bread in the morning.",
                lao: "ຂ້ອຍກິນເຂົ້າຈີ່ໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 4,
        korean: "밥",
        read: "bap",
        english: "rice",
        lao: "ເຂົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 매일 밥을 먹습니다.",
                read: "Jeoneun mae-il bap-eul meogseumnida.",
                english: "I eat rice every day.",
                lao: "ຂ້ອຍກິນເຂົ້າທຸກມື້.",
            },
        ],
    },
    {
        id: 5,
        korean: "국",
        read: "guk",
        english: "soup",
        lao: "ແກງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "추운 날에 국이 좋습니다.",
                read: "Chuun nal-e gugi johseumnida.",
                english: "Soup is good on a cold day.",
                lao: "ແກງເປັນຜົນດີໃນວັນຫນາວ.",
            },
        ],
    },
    {
        id: 6,
        korean: "치즈",
        read: "chi-jeu",
        english: "cheese",
        lao: "ຊີດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "피자에 치즈를 많이 넣었습니다.",
                read: "Pija-e chijeu-reul manh-i neohseumnida.",
                english: "I added a lot of cheese to the pizza.",
                lao: "ຂ້ອຍໃສ່ຊີດຫລາຍໆໃນພິຊຊ່າ.",
            },
        ],
    },
    {
        id: 7,
        korean: "버터",
        read: "beo-teo",
        english: "butter",
        lao: "ເນີຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "빵에 버터를 발랐습니다.",
                read: "Ppang-e beo-teo-reul ballatseumnida.",
                english: "I spread butter on the bread.",
                lao: "ຂ້ອຍປາຍເນີຍໃສ່ເຂົ້າຈີ່.",
            },
        ],
    },
    {
        id: 8,
        korean: "우유",
        read: "u-yu",
        english: "milk",
        lao: "ນົມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 아침에 우유를 마십니다.",
                read: "Jeoneun achim-e uyureul masimnida.",
                english: "I drink milk in the morning.",
                lao: "ຂ້ອຍດື່ມນົມໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 9,
        korean: "커피",
        read: "keo-pi",
        english: "coffee",
        lao: "ກາເຟ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 아침에 커피를 마십니다.",
                read: "Jeoneun achim-e keopi-reul masimnida.",
                english: "I drink coffee in the morning.",
                lao: "ຂ້ອຍດື່ມກາເຟໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 10,
        korean: "차",
        read: "cha",
        english: "tea",
        lao: "ຊາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 저녁에 차를 마십니다.",
                read: "Jeoneun jeonyeog-e cha-reul masimnida.",
                english: "I drink tea in the evening.",
                lao: "ຂ້ອຍດື່ມຊາໃນຕອນແລງ.",
            },
        ],
    },
    {
        id: 11,
        korean: "김치",
        read: "gimchi",
        english: "kimchi",
        lao: "ກິມຈິ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 매일 김치를 먹습니다.",
                read: "Jeoneun maeil gimchi-reul meokseumnida.",
                english: "I eat kimchi every day.",
                lao: "ຂ້ອຍກິນກິມຈິທຸກມື້.",
            },
        ],
    },
    {
        id: 12,
        korean: "피자",
        read: "pija",
        english: "pizza",
        lao: "ພິດຊາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 주말에 피자를 먹습니다.",
                read: "Jeoneun jumal-e pijareul meokseumnida.",
                english: "I eat pizza on weekends.",
                lao: "ຂ້ອຍກິນພິດຊາໃນວັນສຸດທິດ.",
            },
        ],
    },
    {
        id: 13,
        korean: "국수",
        read: "guksu",
        english: "noodle soup",
        lao: "ເສັ້ນນໍ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 점심에 국수를 먹습니다.",
                read: "Jeoneun jeomsim-e guksu-reul meokseumnida.",
                english: "I eat noodle soup for lunch.",
                lao: "ຂ້ອຍກິນເສັ້ນນໍ້າໃນມື້ທ່ຽງ.",
            },
        ],
    },
    {
        id: 14,
        korean: "샌드위치",
        read: "saendeuwichi",
        english: "sandwich",
        lao: "ແຊນດວິດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 점심으로 샌드위치를 먹습니다.",
                read: "Jeoneun jeomsim-eulo saendeuwichi-reul meogseumnida.",
                english: "I eat a sandwich for lunch.",
                lao: "ຂ້ອຍກິນແຊນດວິດໃນມື້ທ່ຽງ.",
            },
        ],
    },
];
