import type { WordModel } from "~/models";

export const ABOUT_AIRPORT: WordModel[] = [
    {
        id: 1,
        korean: "공항",
        read: "gonghang",
        english: "airport",
        lao: "ສະຫນາມບິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "공항에서 출발할 거예요.",
                read: "Gonghangeseo chulbalhal geoyeyo.",
                english: "I will depart from the airport.",
                lao: "ຂ້ອຍຈະອອກເດີນທາງຈາກສະຫນາມບິນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "비행기",
        read: "bihaenggi",
        english: "airplane",
        lao: "ເຮືອບິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "비행기가 이륙하고 있어요.",
                read: "Bihaenggiga iryukago isseoyo.",
                english: "The airplane is taking off.",
                lao: "ເຮືອບິນກໍາລັງທະຍານຂຶ້ນ.",
            },
        ],
    },
    {
        id: 3,
        korean: "항공권",
        read: "hanggonggwon",
        english: "airline ticket",
        lao: "ປີ້ເຮືອບິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "항공권을 예약했어요.",
                read: "Hang-gong-gwoneul yeyayakhaesseoyo.",
                english: "I booked an airline ticket.",
                lao: "ຂ້ອຍໄດ້ຈອງປີ້ເຮືອບິນແລ້ວ.",
            },
        ],
    },
    {
        id: 4,
        korean: "수하물",
        read: "suhamul",
        english: "baggage",
        lao: "ສຳພາລະ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수하물을 찾으세요.",
                read: "Suhamureul chajeuseyo.",
                english: "Please collect your baggage.",
                lao: "ກະລຸນາຮັບສຳພາລະຂອງທ່ານ.",
            },
        ],
    },
    {
        id: 5,
        korean: "체크인",
        read: "chekeu-in",
        english: "check-in",
        lao: "ເຊັກອິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "체크인 시간이 되었어요.",
                read: "Chekeuin sigani doeeosseoyo.",
                english: "It's time to check in.",
                lao: "ເວລາເຊັກອິນແລ້ວ.",
            },
        ],
    },
    {
        id: 6,
        korean: "보안 검사",
        read: "boan geomsa",
        english: "security check",
        lao: "ການກວດກາລະບົບປອດໄພ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "보안 검사를 통과하세요.",
                read: "Boan geomsa-reul tong-gwahaseyo.",
                english: "Please pass through security check.",
                lao: "ກະລຸນາຜ່ານການກວດກາລະບົບປອດໄພ.",
            },
        ],
    },
    {
        id: 7,
        korean: "게이트",
        read: "geiteu",
        english: "gate",
        lao: "ປະຕູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "게이트 번호를 확인하세요.",
                read: "Geiteu beonhoreul hwaginhaseyo.",
                english: "Check your gate number.",
                lao: "ກວດເບິ່ງໝາຍເລກປະຕູຂອງທ່ານ.",
            },
        ],
    },
    {
        id: 8,
        korean: "탑승구",
        read: "tap-seung-gu",
        english: "boarding gate",
        lao: "ປະຕູຂື້ນເຮືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "탑승구로 이동하세요.",
                read: "Tapsseung-guro idonghaseyo.",
                english: "Proceed to the boarding gate.",
                lao: "ກະລຸນາເດີນທາງໄປປະຕູຂື້ນເຮືອ.",
            },
        ],
    },
    {
        id: 9,
        korean: "출발",
        read: "chulbal",
        english: "departure",
        lao: "ການອອກເດີນທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "출발 시간이 가까워지고 있어요.",
                read: "Chulbal sigani gakkawojigo isseoyo.",
                english: "The departure time is approaching.",
                lao: "ເວລາອອກເດີນທາງກໍາລັງເຂົ້າມາໃກ້.",
            },
        ],
    },
    {
        id: 10,
        korean: "도착",
        read: "dochag",
        english: "arrival",
        lao: "ການມາຮອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도착 시간이 언제인가요?",
                read: "Dochag sigani eonjengayo?",
                english: "When is the arrival time?",
                lao: "ເວລາມາຮອດເມື່ອໃດ?",
            },
        ],
    },
    {
        id: 11,
        korean: "탑승권",
        read: "tapseung-gwon",
        english: "boarding pass",
        lao: "ປີ້ຂື້ນເຮືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "탑승권을 준비하세요.",
                read: "Tapseunggwon-eul junbihaseyo.",
                english: "Please prepare your boarding pass.",
                lao: "ກະລຸນາຈັດເຕຽມປີ້ຂື້ນເຮືອຂອງທ່ານ.",
            },
        ],
    },
    {
        id: 12,
        korean: "여권",
        read: "yeogwon",
        english: "passport",
        lao: "ໜັງສືເດີນທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "여권을 확인하세요.",
                read: "Yeogwon-eul hwaginhaseyo.",
                english: "Please check your passport.",
                lao: "ກະລຸນາກວດເບິ່ງໜັງສືເດີນທາງຂອງທ່ານ.",
            },
        ],
    },
    {
        id: 13,
        korean: "세관",
        read: "segwan",
        english: "customs",
        lao: "ດ່ານສຸລະກາກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "세관 신고서를 작성하세요.",
                read: "Segwan singoseoreul jakseonghaseyo.",
                english: "Please fill out the customs declaration form.",
                lao: "ກະລຸນາກອກແບບຟອມການແຈ້ງສຸລະກາກ.",
            },
        ],
    },
    {
        id: 14,
        korean: "환전",
        read: "hwanjeon",
        english: "currency exchange",
        lao: "ການແລກປ່ຽນເງິນຕາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "환전소를 이용하세요.",
                read: "Hwanjeon-soreul iyonghaseyo.",
                english: "Please use the currency exchange office.",
                lao: "ກະລຸນາໃຊ້ບໍລິການສຳຫຼັບການແລກປ່ຽນເງິນຕາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "출국",
        read: "chulguk",
        english: "departure",
        lao: "ການອອກຈາກປະເທດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "출국 심사를 받으세요.",
                read: "Chulguk simsareul badeuseyo.",
                english: "Please undergo departure screening.",
                lao: "ກະລຸນາຜ່ານການກວດກາການອອກຈາກປະເທດ.",
            },
        ],
    },
    {
        id: 16,
        korean: "도착지",
        read: "dochagji",
        english: "destination",
        lao: "ຈຸດໝາຍປາຍທາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "당신의 도착지는 어디인가요?",
                read: "Dangsin-ui dochagjineun eodiingayo?",
                english: "What is your destination?",
                lao: "ທ່ານຈະໄປທີ່ໃດ?",
            },
        ],
    },
    {
        id: 17,
        korean: "환승",
        read: "hwanseung",
        english: "transfer",
        lao: "ການປ່ຽນເຄື່ອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "다음 비행기로 환승하세요.",
                read: "Daeum bihaenggiro hwanseunghaseyo.",
                english: "Transfer to the next flight.",
                lao: "ກະລຸນາປ່ຽນໄປເຮືອບິນລໍາຕໍ່ໄປ.",
            },
        ],
    },
    {
        id: 18,
        korean: "승무원",
        read: "seungmuwon",
        english: "crew",
        lao: "ລູກເຮືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "승무원에게 도움을 요청하세요.",
                read: "Seungmuwonege doum-eul yocheonghaseyo.",
                english: "Ask the crew for assistance.",
                lao: "ຂໍຄວາມຊ່ວຍເຫຼືອຈາກລູກເຮືອ.",
            },
        ],
    },
    {
        id: 19,
        korean: "연착",
        read: "yeonchak",
        english: "delay",
        lao: "ການລ່າຊ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "비행기가 연착되었습니다.",
                read: "Bihaenggiga yeonchakdoeeotseumnida.",
                english: "The flight has been delayed.",
                lao: "ເຮືອບິນລ່າຊ້າ.",
            },
        ],
    },
    {
        id: 20,
        korean: "기내식",
        read: "ginaesik",
        english: "in-flight meal",
        lao: "ອາຫານໃນເຮືອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "기내식을 선택하세요.",
                read: "Ginaesigeul seontaekhaseyo.",
                english: "Choose your in-flight meal.",
                lao: "ເລືອກອາຫານໃນເຮືອຂອງທ່ານ.",
            },
        ],
    },
];
