import type { WordModel } from "~/models";

export const ABOUT_PHARMACY: WordModel[] = [
    {
        id: 1,
        korean: "약국",
        read: "yak-guk",
        english: "pharmacy",
        lao: "ໂຮງຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "약국에서 약을 삽니다.",
                read: "Yak-guk-eseo yag-eul samnida.",
                english: "I buy medicine at the pharmacy.",
                lao: "ຂ້ອຍຊື້ຢາຢູ່ໂຮງຢາ.",
            },
        ],
    },
    {
        id: 2,
        korean: "약사",
        read: "yak-sa",
        english: "pharmacist",
        lao: "ເພຊັດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "약사에게 질문을 합니다.",
                read: "Yak-sa-e-ge jil-mun-eul hamnida.",
                english: "I ask the pharmacist a question.",
                lao: "ຂ້ອຍຖາມຄໍາຖາມແກ່ເພຊັດ.",
            },
        ],
    },
    {
        id: 3,
        korean: "처방전",
        read: "cheo-bang-jeon",
        english: "prescription",
        lao: "ໃບສັ່ງຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사의 처방전을 받았습니다.",
                read: "Uisa-ui cheo-bang-jeon-eul bad-ass-eum-ni-da.",
                english: "I received a prescription from the doctor.",
                lao: "ຂ້ອຍໄດ້ຮັບໃບສັ່ງຢາຈາກໝໍ.",
            },
        ],
    },
    {
        id: 4,
        korean: "약",
        read: "yak",
        english: "medicine",
        lao: "ຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "매일 약을 먹어요.",
                read: "Maeil yag-eul meog-eoyo.",
                english: "I take medicine every day.",
                lao: "ຂ້ອຍກິນຢາທຸກມື້.",
            },
        ],
    },
    {
        id: 5,
        korean: "진통제",
        read: "jin-tong-je",
        english: "painkiller",
        lao: "ຢາແກ້ປວດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "두통이 있을 때 진통제를 먹습니다.",
                read: "Dutong-i iss-eul ttae jin-tong-je-reul meog-seum-ni-da.",
                english: "I take a painkiller when I have a headache.",
                lao: "ຂ້ອຍກິນຢາແກ້ປວດເມື່ອຂ້ອຍມີອາການເຈັບຫົວ.",
            },
        ],
    },
    {
        id: 6,
        korean: "항생제",
        read: "hang-saeng-je",
        english: "antibiotic",
        lao: "ຢາຕ້ານເຊື້ອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "항생제는 박테리아 감염에 사용됩니다.",
                read: "Hang-saeng-je-neun bag-te-ri-a gam-yeom-e sa-yong-doemnida.",
                english: "Antibiotics are used for bacterial infections.",
                lao: "ຢາຕ້ານເຊື້ອໃຊ້ເພື່ອການຕິດເຊື້ອບາດທີເລຍ.",
            },
        ],
    },
    {
        id: 7,
        korean: "비타민",
        read: "bi-ta-min",
        english: "vitamin",
        lao: "ວິຕາມິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "비타민을 매일 복용하세요.",
                read: "Bi-ta-min-eul mae-il bo-gyong-ha-se-yo.",
                english: "Take your vitamins every day.",
                lao: "ກິນວິຕາມິນທຸກມື້.",
            },
        ],
    },
    {
        id: 8,
        korean: "알약",
        read: "al-yak",
        english: "pill",
        lao: "ເມັດຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "알약을 삼키기 어려워요.",
                read: "Al-yak-eul sam-ki-gi eo-ryeo-weo-yo.",
                english: "It's hard to swallow pills.",
                lao: "ການກືນເມັດຢາຍາກ.",
            },
        ],
    },
    {
        id: 9,
        korean: "액체약",
        read: "aek-che-yak",
        english: "liquid medicine",
        lao: "ຢານ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들은 액체약을 더 쉽게 복용합니다.",
                read: "Ai-deul-eun aek-che-yak-eul deo swip-ge bo-gyong-ham-ni-da.",
                english: "Children find it easier to take liquid medicine.",
                lao: "ເດັກນ້ອຍກິນຢານ້ໍາງ່າຍກວ່າ.",
            },
        ],
    },
    {
        id: 10,
        korean: "연고",
        read: "yeon-go",
        english: "ointment",
        lao: "ຢາທາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "상처에 연고를 발라주세요.",
                read: "Sang-cheo-e yeon-go-reul bal-la-ju-se-yo.",
                english: "Please apply ointment to the wound.",
                lao: "ກະລຸນາທາຢາບ່ວງທີ່ແຜ.",
            },
        ],
    },
    {
        id: 11,
        korean: "처방전 없이",
        read: "cheo-bang-jeon eob-si",
        english: "over-the-counter",
        lao: "ຍາທີ່ຊື້ໄດ້ບໍ່ຕ້ອງໃຊ້ໃບສັ່ງຢາ",
        speech: "adj",
        examples: [
            {
                id: 1,
                korean: "처방전 없이 살 수 있는 약이에요.",
                read: "Cheo-bang-jeon eob-si sal su it-neun yag-ie-yo.",
                english: "This is an over-the-counter medicine.",
                lao: "ນີ້ເປັນຢາທີ່ຊື້ໄດ້ບໍ່ຕ້ອງໃຊ້ໃບສັ່ງຢາ.",
            },
        ],
    },
    {
        id: 12,
        korean: "부작용",
        read: "bu-ja-gyong",
        english: "side effect",
        lao: "ຜົນຂ້າງເຄຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이 약의 부작용은 무엇인가요?",
                read: "I yag-ui bu-ja-gyong-eun mu-eo-sin-ga-yo?",
                english: "What are the side effects of this medicine?",
                lao: "ຜົນຂ້າງເຄຽງຂອງຢານີ້ແມ່ນຫຍັງ?",
            },
        ],
    },
    {
        id: 13,
        korean: "복용량",
        read: "bo-gyong-ryang",
        english: "dosage",
        lao: "ປະລິມານການກິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사에게 정확한 복용량을 물어보세요.",
                read: "Uisa-e-ge jeong-hwag-han bo-gyong-ryang-eul mu-reo-bo-se-yo.",
                english: "Ask the doctor for the correct dosage.",
                lao: "ຖາມໝໍສໍາລັບປະລິມານການກິນທີ່ຖືກຕ້ອງ.",
            },
        ],
    },
    {
        id: 14,
        korean: "약용 크림",
        read: "yak-yong keurim",
        english: "medicated cream",
        lao: "ຄຣີມຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이 약용 크림을 하루 두 번 발라주세요.",
                read: "I yak-yong keurim-eul haru du beon bal-la-ju-se-yo.",
                english: "Apply this medicated cream twice a day.",
                lao: "ທາຄຣີມຢານີ້ສອງຄັ້ງຕໍ່ມື້.",
            },
        ],
    },
    {
        id: 15,
        korean: "구급상자",
        read: "gu-geub-sang-ja",
        english: "first aid kit",
        lao: "ກ່ອງປະຖົມພະຍາບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "구급상자는 항상 준비되어 있어야 합니다.",
                read: "Gu-geub-sang-ja-neun hangsang jun-bi-doe-eo iss-eo-ya ham-ni-da.",
                english: "A first aid kit should always be ready.",
                lao: "ກ່ອງປະຖົມພະຍາບານຄວນຕຽມພ້ອມຢູ່ເມື່ອໃດກໍຕາມ.",
            },
        ],
    },
];
