import type { WordModel } from "~/models";

export const ABOUT_MARKET: WordModel[] = [
    {
        id: 1,
        korean: "시장",
        read: "si-jang",
        english: "market",
        lao: "ຕະຫຼາດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시장에서 신선한 야채를 샀습니다.",
                read: "si-jang-e-seo sin-seon-han ya-chae-reul sat-seum-ni-da.",
                english: "I bought fresh vegetables at the market.",
                lao: "ຂ້ອຍໄດ້ຊື້ຜັກສົດທີ່ຕະຫຼາດ.",
            },
        ],
    },
    {
        id: 2,
        korean: "가게",
        read: "ga-ge",
        english: "shop",
        lao: "ຮ້ານຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "가게에서 과일을 샀습니다.",
                read: "ga-ge-e-seo gwa-il-eul sat-seum-ni-da.",
                english: "I bought fruit at the shop.",
                lao: "ຂ້ອຍຊື້ຜົມໄມ້ຢູ່ຮ້ານຄ້າ.",
            },
        ],
    },
    {
        id: 3,
        korean: "상인",
        read: "sang-in",
        english: "merchant",
        lao: "ພໍ່ຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "상인은 시장에서 물건을 팝니다.",
                read: "sang-in-eun si-jang-e-seo mul-geon-eul pam-ni-da.",
                english: "The merchant sells goods at the market.",
                lao: "ພໍ່ຄ້າຂາຍສິນຄ້າຢູ່ຕະຫຼາດ.",
            },
        ],
    },
    {
        id: 4,
        korean: "고객",
        read: "go-gaek",
        english: "customer",
        lao: "ລູກຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "고객이 물건을 찾고 있습니다.",
                read: "go-gaek-i mul-geon-eul chat-go it-seum-ni-da.",
                english: "The customer is looking for goods.",
                lao: "ລູກຄ້າກຳລັງຫາສິນຄ້າ.",
            },
        ],
    },
    {
        id: 5,
        korean: "가격",
        read: "ga-gyeok",
        english: "price",
        lao: "ລາຄາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이 물건의 가격은 얼마입니까?",
                read: "i mul-geon-eui ga-gyeok-eun eol-ma-im-ni-kka?",
                english: "What is the price of this item?",
                lao: "ລາຄາຂອງສິນຄ້ານີ້ເທົ່າໃດ?",
            },
        ],
    },
    {
        id: 6,
        korean: "물건",
        read: "mul-geon",
        english: "goods",
        lao: "ສິນຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시장에서 다양한 물건을 팔아요.",
                read: "si-jang-e-seo da-yang-han mul-geon-eul pal-a-yo.",
                english: "They sell various goods at the market.",
                lao: "ພວກເຂົາຂາຍສິນຄ້າຫລາກຫລາຍຢູ່ຕະຫຼາດ.",
            },
        ],
    },
    {
        id: 7,
        korean: "할인",
        read: "hal-in",
        english: "discount",
        lao: "ຫລຸດລາຄາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "할인 가격으로 이 물건을 샀습니다.",
                read: "hal-in ga-gyeok-eu-ro i mul-geon-eul sat-seum-ni-da.",
                english: "I bought this item at a discounted price.",
                lao: "ຂ້ອຍຊື້ສິນຄ້ານີ້ທີ່ລາຄາຫລຸດ.",
            },
        ],
    },
    {
        id: 8,
        korean: "거래",
        read: "geo-rae",
        english: "trade",
        lao: "ການຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시장에서 많은 거래가 이루어집니다.",
                read: "si-jang-e-seo manh-eun geo-rae-ga i-ru-eo-jip-ni-da.",
                english: "Many trades are made at the market.",
                lao: "ມີການຄ້າຫລາຍຢູ່ຕະຫຼາດ.",
            },
        ],
    },
    {
        id: 9,
        korean: "지불",
        read: "ji-bul",
        english: "payment",
        lao: "ການຈ່າຍເງິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "고객이 지불을 마쳤습니다.",
                read: "go-gaek-i ji-bul-eul ma-chyeot-seum-ni-da.",
                english: "The customer has completed the payment.",
                lao: "ລູກຄ້າໄດ້ຈ່າຍເງິນແລ້ວ.",
            },
        ],
    },
    {
        id: 10,
        korean: "거래처",
        read: "geo-rae-cheo",
        english: "vendor",
        lao: "ຜູ້ຂາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거래처와 좋은 관계를 유지하세요.",
                read: "geo-rae-cheo-wa jo-eun gwang-gye-reul yu-ji-ha-se-yo.",
                english: "Maintain good relations with the vendor.",
                lao: "ຮັກສາຄວາມສຳພັນທີ່ດີກັບຜູ້ຂາຍ.",
            },
        ],
    },
    {
        id: 11,
        korean: "현금",
        read: "hyeon-geum",
        english: "cash",
        lao: "ເງິນສົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시장에서는 현금만 받습니다.",
                read: "si-jang-e-seo hyeon-geum-man bat-seum-ni-da.",
                english: "They only accept cash at the market.",
                lao: "ພວກເຂົາຮັບເງິນສົດເທົ່ານັ້ນຢູ່ຕະຫຼາດ.",
            },
        ],
    },
    {
        id: 12,
        korean: "신용카드",
        read: "sin-yong-ka-deu",
        english: "credit card",
        lao: "ບັດເຄຣດິດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "여기서는 신용카드 사용이 가능합니다.",
                read: "yeo-gi-seo-neun sin-yong-ka-deu sa-yong-i ga-neung-ham-ni-da.",
                english: "You can use credit cards here.",
                lao: "ທ່ານສາມາດໃຊ້ບັດເຄຣດິດໄດ້ທີ່ນີ້.",
            },
        ],
    },
    {
        id: 13,
        korean: "계산대",
        read: "gye-san-dae",
        english: "cash register",
        lao: "ເຄື່ອງບັນທຶກເງິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "계산대에서 지불을 합니다.",
                read: "gye-san-dae-e-seo ji-bul-eul ham-ni-da.",
                english: "I make a payment at the cash register.",
                lao: "ຂ້ອຍຈ່າຍເງິນຢູ່ເຄື່ອງບັນທຶກເງິນ.",
            },
        ],
    },
    {
        id: 14,
        korean: "교환",
        read: "gyo-hwan",
        english: "exchange",
        lao: "ການແລກປ່ຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "물건을 교환할 수 있습니까?",
                read: "mul-geon-eul gyo-hwan-hal su its-seum-ni-kka?",
                english: "Can I exchange this item?",
                lao: "ຂ້ອຍສາມາດແລກປ່ຽນສິນຄ້ານີ້ໄດ້ບໍ?",
            },
        ],
    },
    {
        id: 15,
        korean: "반품",
        read: "ban-pum",
        english: "return",
        lao: "ການຄືນສິນຄ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "물건을 반품할 수 있습니까?",
                read: "mul-geon-eul ban-pum-hal su its-seum-ni-kka?",
                english: "Can I return this item?",
                lao: "ຂ້ອຍສາມາດຄືນສິນຄ້ານີ້ໄດ້ບໍ?",
            },
        ],
    },
];
