import type { WordModel } from "~/models";

export const ABOUT_RENTING_APARTMENT: WordModel[] = [
    {
        id: 1,
        korean: "아파트",
        read: "apateu",
        english: "apartment",
        lao: "ອາພາດເມັ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "새 아파트를 찾고 있어요.",
                read: "Sae apateureul chatgo isseoyo.",
                english: "I am looking for a new apartment.",
                lao: "ຂ້ອຍກໍາລັງຫາອາພາດເມັ້ນໃຫມ່.",
            },
        ],
    },
    {
        id: 2,
        korean: "임대",
        read: "imdae",
        english: "rent",
        lao: "ເຊົ່າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "임대 계약을 맺었어요.",
                read: "Imdae gyeyageul maej-eosseoyo.",
                english: "I signed a rental agreement.",
                lao: "ຂ້ອຍໄດ້ເຊັນສັນຍາເຊົ່າ.",
            },
        ],
    },
    {
        id: 3,
        korean: "계약",
        read: "gyeyak",
        english: "contract",
        lao: "ສັນຍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "계약을 주의 깊게 읽어야 합니다.",
                read: "Gyeyageul juui gipge ilgeoya hamnida.",
                english: "You should read the contract carefully.",
                lao: "ທ່ານຄວນອ່ານສັນຍາໃຫ້ລະມັດລະວັງ.",
            },
        ],
    },
    {
        id: 4,
        korean: "보증금",
        read: "bojeung-geum",
        english: "deposit",
        lao: "ເງິນຄ້າມປະກັນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "보증금을 미리 준비해야 해요.",
                read: "Bojeung-geumeul miri junbihaeya haeyo.",
                english: "You need to prepare the deposit in advance.",
                lao: "ທ່ານຕ້ອງການຈັດເຕຽມເງິນຄ້າມປະກັນລ່ວງໜ້າ.",
            },
        ],
    },
    {
        id: 5,
        korean: "임대료",
        read: "imdaeryo",
        english: "rent fee",
        lao: "ຄ່າເຊົ່າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "임대료는 매달 내야 해요.",
                read: "Imdaeryoneun maedal naeya haeyo.",
                english: "The rent fee must be paid every month.",
                lao: "ຄ່າເຊົ່າຕ້ອງຈ່າຍທຸກເດືອນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "부동산 중개인",
        read: "budongsan junggae-in",
        english: "real estate agent",
        lao: "ນາຍໜ້າອສັງຫາລິມະຊັບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "부동산 중개인을 통해 아파트를 찾았어요.",
                read: "Budongsan junggae-in-eul tonghae apateureul chajasseoyo.",
                english: "I found the apartment through a real estate agent.",
                lao: "ຂ້ອຍພົບອາພາດເມັ້ນຜ່ານນາຍໜ້າອສັງຫາລິມະຊັບ.",
            },
        ],
    },
    {
        id: 7,
        korean: "관리비",
        read: "gwanlibi",
        english: "maintenance fee",
        lao: "ຄ່າບໍລິການບໍລິຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "관리비는 매달 지불해야 해요.",
                read: "Gwanlibineun maedal jibulhaeya haeyo.",
                english: "The maintenance fee must be paid monthly.",
                lao: "ຄ່າບໍລິການບໍລິຫານຕ້ອງຈ່າຍທຸກເດືອນ.",
            },
        ],
    },
    {
        id: 8,
        korean: "전기 요금",
        read: "jeongi yogeum",
        english: "electricity bill",
        lao: "ໃບບິນໄຟຟ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "전기 요금은 매달 내야 해요.",
                read: "Jeongi yogeumeun maedal naeya haeyo.",
                english: "The electricity bill must be paid every month.",
                lao: "ໃບບິນໄຟຟ້າຕ້ອງຈ່າຍທຸກເດືອນ.",
            },
        ],
    },
    {
        id: 9,
        korean: "수도 요금",
        read: "sudo yogeum",
        english: "water bill",
        lao: "ໃບບິນນ້ໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수도 요금은 매달 내야 해요.",
                read: "Sudo yogeumeun maedal naeya haeyo.",
                english: "The water bill must be paid every month.",
                lao: "ໃບບິນນ້ໍາຕ້ອງຈ່າຍທຸກເດືອນ.",
            },
        ],
    },
    {
        id: 10,
        korean: "인터넷 요금",
        read: "inteonet yogeum",
        english: "internet bill",
        lao: "ໃບບິນອິນເຕີເນັດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "인터넷 요금은 매달 내야 해요.",
                read: "Inteonet yogeumeun maedal naeya haeyo.",
                english: "The internet bill must be paid every month.",
                lao: "ໃບບິນອິນເຕີເນັດຕ້ອງຈ່າຍທຸກເດືອນ.",
            },
        ],
    },
    {
        id: 11,
        korean: "이사",
        read: "isa",
        english: "move",
        lao: "ຍ້າຍບ້ານ",
        speech: "v",
        examples: [
            {
                id: 1,
                korean: "이사는 큰 일이에요.",
                read: "Isaneun keun irieyo.",
                english: "Moving is a big task.",
                lao: "ການຍ້າຍບ້ານເປັນວຽກໃຫຍ່.",
            },
        ],
    },
    {
        id: 12,
        korean: "수리",
        read: "suri",
        english: "repair",
        lao: "ການສ້ອມແປງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수리가 필요할 때는 주인에게 연락하세요.",
                read: "Suriga pillyohal ttaeneun juinege yeollakaseyo.",
                english: "Contact the owner when repairs are needed.",
                lao: "ຕິດຕໍ່ຜູ້ເປັນເຈົ້າເມື່ອຈຳເປັນຕ້ອງສ້ອມແປງ.",
            },
        ],
    },
    {
        id: 13,
        korean: "이웃",
        read: "iut",
        english: "neighbor",
        lao: "ເພື່ອນບ້ານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이웃과 좋은 관계를 유지하세요.",
                read: "Iutgwa joeun gwangyerul yujihaseyo.",
                english: "Maintain good relations with your neighbors.",
                lao: "ຮັກສາຄວາມສຳພັນທີ່ດີກັບເພື່ອນບ້ານ.",
            },
        ],
    },
    {
        id: 14,
        korean: "쓰레기",
        read: "sseuregi",
        english: "trash",
        lao: "ຂີ້ເຫຍື້ອ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "쓰레기는 정해진 장소에 버리세요.",
                read: "Sseuregineun jeonghaejin jangsoe beorisaeyo.",
                english: "Throw the trash in designated areas.",
                lao: "ຖີ້ມຂີ້ເຫຍື້ອໃນບ່ອນທີ່ກຳນົດໄວ້.",
            },
        ],
    },
    {
        id: 15,
        korean: "애완동물",
        read: "aewan-dongmul",
        english: "pet",
        lao: "ສັດລ້ຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "애완동물을 키워도 되나요?",
                read: "Aewan-dongmuleul kiwodo doenayo?",
                english: "Can I have a pet?",
                lao: "ຂ້ອຍສາມາດມີສັດລ້ຽງໄດ້ບໍ?",
            },
        ],
    },
    {
        id: 16,
        korean: "엘리베이터",
        read: "ellibeiteo",
        english: "elevator",
        lao: "ລິບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "엘리베이터를 이용하세요.",
                read: "Ellibeiteoreul iyonghaseyo.",
                english: "Please use the elevator.",
                lao: "ກະລຸນາໃຊ້ລິບ.",
            },
        ],
    },
    {
        id: 17,
        korean: "계단",
        read: "gyedan",
        english: "stairs",
        lao: "ຂັ້ນໄດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "계단을 이용하세요.",
                read: "Gyedaneul iyonghaseyo.",
                english: "Please use the stairs.",
                lao: "ກະລຸນາໃຊ້ຂັ້ນໄດ.",
            },
        ],
    },
    {
        id: 18,
        korean: "층",
        read: "cheung",
        english: "floor",
        lao: "ຊັ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 5층에 살아요.",
                read: "Jeoneun 5cheunge sarayo.",
                english: "I live on the 5th floor.",
                lao: "ຂ້ອຍອາໄສຢູ່ຊັ້ນທີ 5.",
            },
        ],
    },
];
