import type { WordModel } from "~/models";

export const ABOUT_TIMING: WordModel[] = [
    {
        id: 1,
        korean: "시계",
        read: "si-gye",
        english: "clock",
        lao: "ນາລິກາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벽에 시계가 걸려 있어요.",
                read: "Byeog-e si-gye-ga geol-lyeo iss-eo-yo.",
                english: "The clock is hanging on the wall.",
                lao: "ນາລິກາແຂວນຢູ່ກຳແພງ.",
            },
        ],
    },
    {
        id: 2,
        korean: "알람 시계",
        read: "al-ram si-gye",
        english: "alarm clock",
        lao: "ນາລິກາປຸກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 알람 시계가 울렸어요.",
                read: "A-chim-e al-ram si-gye-ga ul-lyeoss-eo-yo.",
                english: "The alarm clock rang in the morning.",
                lao: "ນາລິກາປຸກດັງໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 3,
        korean: "손목 시계",
        read: "son-mok si-gye",
        english: "wristwatch",
        lao: "ນາລິກາຂໍ້ມື",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "손목 시계를 차고 있어요.",
                read: "Son-mok si-gye-reul cha-go iss-eo-yo.",
                english: "I am wearing a wristwatch.",
                lao: "ຂ້ອຍສວມນາລິກາຂໍ້ມື.",
            },
        ],
    },
    {
        id: 4,
        korean: "시간",
        read: "si-gan",
        english: "time",
        lao: "ເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시간을 맞춰서 출발했어요.",
                read: "Si-gan-eul maj-chweo-seo chul-bal-haess-eo-yo.",
                english: "We left on time.",
                lao: "ພວກເຮົາອອກເດີນທາງຕາມເວລາ.",
            },
        ],
    },
    {
        id: 5,
        korean: "초",
        read: "cho",
        english: "second",
        lao: "ວິນາທີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "3초 동안 기다렸어요.",
                read: "Sam-cho dong-an gi-da-ryeoss-eo-yo.",
                english: "I waited for 3 seconds.",
                lao: "ຂ້ອຍລໍຖ້າ 3 ວິນາທີ.",
            },
        ],
    },
    {
        id: 6,
        korean: "분",
        read: "bun",
        english: "minute",
        lao: "ນາທີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "10분 동안 쉬었어요.",
                read: "Sip-bun dong-an swi-eoss-eo-yo.",
                english: "I rested for 10 minutes.",
                lao: "ຂ້ອຍພັກ 10 ນາທີ.",
            },
        ],
    },
    {
        id: 7,
        korean: "시간",
        read: "sigan",
        english: "hour",
        lao: "ເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "한 시간 동안 공부했습니다.",
                read: "han sigan dong-an gongbuhaetsseumnida.",
                english: "I studied for one hour.",
                lao: "ຂ້າພະເຈົ້າໄດ້ສົບຜົນສອນຢູ່ເວລາ.",
            },
        ],
    },
    {
        id: 8,
        korean: "시간대",
        read: "si-gan-dae",
        english: "time zone",
        lao: "ເຂດເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리나라와 다른 시간대에 있어요.",
                read: "U-ri-na-ra-wa da-reun si-gan-dae-e iss-eo-yo.",
                english: "It's in a different time zone from our country.",
                lao: "ມັນຢູ່ໃນເຂດເວລາທີ່ແຕກຕ່າງຈາກປະເທດຂອງພວກເຮົາ.",
            },
        ],
    },
    {
        id: 9,
        korean: "정각",
        read: "jeong-gak",
        english: "o'clock",
        lao: "ໂມງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 3시 정각에 만나요.",
                read: "U-ri-neun sam-si jeong-gak-e man-na-yo.",
                english: "We meet at 3 o'clock.",
                lao: "ພວກເຮົາພົບກັນຕອນ 3 ໂມງ.",
            },
        ],
    },
    {
        id: 10,
        korean: "반",
        read: "ban",
        english: "half past",
        lao: "ຄືງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 5시 반에 출발했어요.",
                read: "U-ri-neun daseot-si ban-e chul-bal-haess-eo-yo.",
                english: "We left at half past five.",
                lao: "ພວກເຮົາອອກເດີນທາງເວລາ 5 ໂມງຄືງ.",
            },
        ],
    },
    {
        id: 11,
        korean: "일정",
        read: "il-jeong",
        english: "schedule",
        lao: "ຕາຕະລາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오늘 일정이 빡빡해요.",
                read: "O-neul il-jeong-i ppak-ppak-hae-yo.",
                english: "Today's schedule is tight.",
                lao: "ຕາຕະລາງມື້ນີ້ຕຶບຕັນ.",
            },
        ],
    },
    {
        id: 12,
        korean: "알람",
        read: "al-ram",
        english: "alarm",
        lao: "ແອລາມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "알람을 맞춰 놓았어요.",
                read: "Al-ram-eul maj-chweo no-ass-eo-yo.",
                english: "I set the alarm.",
                lao: "ຂ້ອຍໄດ້ຕັ້ງແອລາມໄວ້.",
            },
        ],
    },
    {
        id: 13,
        korean: "타이머",
        read: "ta-i-meo",
        english: "timer",
        lao: "ເຄື່ອງຕັ້ງເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "타이머를 사용해서 요리했어요.",
                read: "Ta-i-meo-reul sa-yong-hae-seo yo-ri-haess-eo-yo.",
                english: "I used a timer to cook.",
                lao: "ຂ້ອຍໃຊ້ເຄື່ອງຕັ້ງເວລາໃນການປຸງອາຫານ.",
            },
        ],
    },
    {
        id: 14,
        korean: "정시",
        read: "jeong-si",
        english: "on time",
        lao: "ຕາມເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정시에 도착했어요.",
                read: "Jeong-si-e do-chak-haess-eo-yo.",
                english: "I arrived on time.",
                lao: "ຂ້ອຍມາຮອດຕາມເວລາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "연체",
        read: "yeon-che",
        english: "late",
        lao: "ຊ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "회의에 연체되었어요.",
                read: "Hwi-ui-e yeon-che-dweo-sseo-yo.",
                english: "I was late for the meeting.",
                lao: "ຂ້ອຍມາຊ້າສຳລັບການປະຊຸມ.",
            },
        ],
    },
    {
        id: 16,
        korean: "오전 여덟 시",
        read: "ojeon yeodeol si",
        english: "08:00 AM",
        lao: "8 ໂມງເຊົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오전 여덟 시에 일어났어요.",
                read: "ojeon yeodeol si-e ileonasseoyo.",
                english: "I woke up at 08:00 AM.",
                lao: "ຂ້ອຍຕື່ນນອນ 8 ໂມງເຊົ້າ.",
            },
        ],
    },
    {
        id: 17,
        korean: "아홉시 십오분",
        read: "a-hop-si sip-o-bun",
        english: "09:15 AM",
        lao: "09:15 AM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 09:15 AM에 회의를 시작했어요.",
                read: "Uri-neun a-hop-si sip-o-bun-e hwi-ui-reul sijakhaesseoyo.",
                english: "We started the meeting at 09:15 AM.",
                lao: "ພວກເຮົາເລີ່ມການປະຊຸມເວລາ 09:15 AM.",
            },
        ],
    },
    {
        id: 18,
        korean: "열두시",
        read: "yeol-du-si",
        english: "12:00 PM",
        lao: "12:00 PM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 12:00 PM에 점심을 먹었어요.",
                read: "Uri-neun yeol-du-si-e jeomsim-eul meogeosseoyo.",
                english: "We had lunch at 12:00 PM.",
                lao: "ພວກເຮົາກິນເຂົ້າທ່ຽງເວລາ 12:00 PM.",
            },
        ],
    },
    {
        id: 19,
        korean: "열 시",
        read: "yeol si",
        english: "10:00",
        lao: "ສິ້ນສຸດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오늘 밤 열 시에 집에 도착할 거예요.",
                read: "oneul bam yeol si-e jibe dochakhal geoyeyo.",
                english: "I will arrive home at ten o'clock tonight.",
                lao: "ຂອງວັນນີ້ເຈົ້າຈອນໄດ້ໃນສິ້ນສຸດວນ.",
            },
        ],
    },
    {
        id: 20,
        korean: "아침",
        read: "achim",
        english: "morning",
        lao: "ເຊົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침 일찍 일어나서 준비를 해야 해요.",
                read: "achim iljjig ileonaseo junbireul haeya haeyo.",
                english:
                    "You need to wake up early in the morning and get ready.",
                lao: "ທ່ານຕ້ອງການການລົງຊື້ວ່າໄດ້ໃນເຊົ້າແລະປະຕິທິນມ່ວນ.",
            },
        ],
    },
    {
        id: 21,
        korean: "저녁",
        read: "jeonyeok",
        english: "evening",
        lao: "ຕອນຕາມຫຼັງກາຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저녁 식사 후에 걷기 좋은 시간이에요.",
                read: "jeonyeok siksa hue geotgi joheun sigani-e-yo.",
                english: "Evening is a good time for a walk after dinner.",
                lao: "ເດີນຕອນຕາມຫຼັງກາຍແລ້ວເມື່ອກິນ.",
            },
        ],
    },
    {
        id: 22,
        korean: "낮",
        read: "nat",
        english: "daytime",
        lao: "ເຊົ້າທີ່ມື້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "낮에는 일하기 바쁘다.",
                read: "nat-eneun ilhagi bappuda.",
                english: "It's busy working during the daytime.",
                lao: "ມື້ມອນມີຄວາມຮັ່ງທັມ.",
            },
        ],
    },
    {
        id: 23,
        korean: "밤",
        read: "bam",
        english: "nighttime",
        lao: "ເບັມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "밤에는 별들이 아름답게 빛납니다.",
                read: "bam-eneun byeol-deuri areumdapge binnapnida.",
                english: "Stars shine beautifully at nighttime.",
                lao: "ແນວມອນມີຕາມກັນຈະປະເສີດຫນ້າກາຍ.",
            },
        ],
    },
    {
        id: 24,
        korean: "오전",
        read: "ojeon",
        english: "AM",
        lao: "ກ່ອນຕອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오전 10시에 회의가 있습니다.",
                read: "ojeon sip-shi-e ho-ui-ga issseumnida.",
                english: "There is a meeting at 10 AM.",
                lao: "ມື້ເມື່ອເວລາມອງຕອນ 10 ຊີ້ນ.",
            },
        ],
    },
    {
        id: 25,
        korean: "오후",
        read: "ohu",
        english: "PM",
        lao: "ຫຼັງທ່ຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오후 3시에 회의가 있습니다.",
                read: "ohu sam-shi-e ho-ui-ga issseumnida.",
                english: "There is a meeting at 3 PM.",
                lao: "ມື້ເວລາຫຼັງທ່ຽງ 3 ຊີ້ນ.",
            },
        ],
    },
];
