import type { WordModel } from "~/models";

export const ABOUT_HOUSE: WordModel[] = [
    {
        id: 1,
        korean: "문",
        read: "mun",
        english: "door",
        lao: "ປະຕູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "문을 열어주세요.",
                read: "Mun-eul yeoreojuseyo.",
                english: "Please open the door.",
                lao: "ກະລຸນາເປີດປະຕູ.",
            },
        ],
    },
    {
        id: 2,
        korean: "창문",
        read: "chang-mun",
        english: "window",
        lao: "ປ່ອງຢ້ຽມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "창문을 닫아주세요.",
                read: "Chang-mun-eul dad-ajuseyo.",
                english: "Please close the window.",
                lao: "ກະລຸນາປິດປ່ອງຢ້ຽມ.",
            },
        ],
    },
    {
        id: 3,
        korean: "부엌",
        read: "bu-eok",
        english: "kitchen",
        lao: "ຫ້ອງຄົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "부엌에서 요리해요.",
                read: "Bu-eok-e-seo yo-ri-hae-yo.",
                english: "I cook in the kitchen.",
                lao: "ຂ້ອຍປຸງອາຫານຢູ່ຫ້ອງຄົວ.",
            },
        ],
    },
    {
        id: 4,
        korean: "거실",
        read: "geo-sil",
        english: "living room",
        lao: "ຫ້ອງນັ່ງເລ່ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거실에서 TV를 봐요.",
                read: "Geo-sil-e-seo TV-reul bwa-yo.",
                english: "I watch TV in the living room.",
                lao: "ຂ້ອຍເບິ່ງທີວີຢູ່ຫ້ອງນັ່ງເລ່ນ.",
            },
        ],
    },
    {
        id: 5,
        korean: "침실",
        read: "chim-sil",
        english: "bedroom",
        lao: "ຫ້ອງນອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "침실에서 잠을 자요.",
                read: "Chim-sil-e-seo jam-eul ja-yo.",
                english: "I sleep in the bedroom.",
                lao: "ຂ້ອຍນອນຢູ່ຫ້ອງນອນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "화장실",
        read: "hwa-jang-sil",
        english: "bathroom",
        lao: "ຫ້ອງນ້ຳ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "화장실을 청소해요.",
                read: "Hwa-jang-sil-eul cheong-so-hae-yo.",
                english: "I clean the bathroom.",
                lao: "ຂ້ອຍທຳຄວາມສະອາດຫ້ອງນ້ຳ.",
            },
        ],
    },
    {
        id: 7,
        korean: "식당",
        read: "sik-dang",
        english: "dining room",
        lao: "ຫ້ອງກິນເຂົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "식당에서 저녁을 먹어요.",
                read: "Sik-dang-e-seo jeo-nyeog-eul meog-eo-yo.",
                english: "I eat dinner in the dining room.",
                lao: "ຂ້ອຍກິນອາຫານແລງຢູ່ຫ້ອງກິນເຂົ້າ.",
            },
        ],
    },
    {
        id: 8,
        korean: "베란다",
        read: "be-ran-da",
        english: "balcony",
        lao: "ລະບຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "베란다에서 책을 읽어요.",
                read: "Be-ran-da-e-seo chaeg-eul ilg-eo-yo.",
                english: "I read a book on the balcony.",
                lao: "ຂ້ອຍອ່ານປື້ມຢູ່ລະບຽງ.",
            },
        ],
    },
    {
        id: 9,
        korean: "정원",
        read: "jeong-won",
        english: "garden",
        lao: "ສວນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정원에 꽃을 심었어요.",
                read: "Jeong-won-e kkoch-eul sim-eoss-eo-yo.",
                english: "I planted flowers in the garden.",
                lao: "ຂ້ອຍປູກດອກໄມ້ໃນສວນ.",
            },
        ],
    },
    {
        id: 10,
        korean: "차고",
        read: "cha-go",
        english: "garage",
        lao: "ໂຮງລົດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "차고에 차를 주차했어요.",
                read: "Cha-go-e cha-reul ju-cha-haess-eo-yo.",
                english: "I parked the car in the garage.",
                lao: "ຂ້ອຍຈອດລົດໃນໂຮງລົດ.",
            },
        ],
    },
    {
        id: 11,
        korean: "현관",
        read: "hyeon-gwan",
        english: "entrance",
        lao: "ທາງເຂົ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "현관에서 신발을 벗어요.",
                read: "Hyeon-gwan-e-seo sin-bal-eul beos-eo-yo.",
                english: "I take off my shoes at the entrance.",
                lao: "ຂ້ອຍຖອດລອງເທົາຢູ່ທາງເຂົ້າ.",
            },
        ],
    },
    {
        id: 12,
        korean: "지하실",
        read: "ji-ha-sil",
        english: "basement",
        lao: "ຫ້ອງຊັ້ນໃຕ້ດິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "지하실에 저장고가 있어요.",
                read: "Ji-ha-sil-e jeo-jang-go-ga iss-eo-yo.",
                english: "There is a storage room in the basement.",
                lao: "ມີຫ້ອງເກັບຂອງຢູ່ໃນຫ້ອງຊັ້ນໃຕ້ດິນ.",
            },
        ],
    },
    {
        id: 13,
        korean: "옥상",
        read: "ok-sang",
        english: "roof",
        lao: "ຫົວຫນ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "옥상에서 별을 봐요.",
                read: "Ok-sang-e-seo byeol-eul bwa-yo.",
                english: "I watch the stars from the roof.",
                lao: "ຂ້ອຍເບິ່ງດາວຈາກຫົວຫນ້າ.",
            },
        ],
    },
    {
        id: 14,
        korean: "벽",
        read: "byeok",
        english: "wall",
        lao: "ກໍແພ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벽에 그림을 걸었어요.",
                read: "Byeog-e geurim-eul geol-eoss-eo-yo.",
                english: "I hung a picture on the wall.",
                lao: "ຂ້ອຍແຂວນຮູບຢູ່ກໍແພ.",
            },
        ],
    },
    {
        id: 15,
        korean: "천장",
        read: "cheon-jang",
        english: "ceiling",
        lao: "ຝ້າເພດານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "천장에 등이 달려 있어요.",
                read: "Cheon-jang-e deung-i dal-lyeo iss-eo-yo.",
                english: "There is a light on the ceiling.",
                lao: "ມີໄຟຢູ່ເທິງຝ້າເພດານ.",
            },
        ],
    },
    {
        id: 16,
        korean: "바닥",
        read: "ba-dak",
        english: "floor",
        lao: "ພື້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "바닥을 청소해요.",
                read: "Ba-dak-eul cheong-so-hae-yo.",
                english: "I clean the floor.",
                lao: "ຂ້ອຍຖູພື້ນ.",
            },
        ],
    },
];
