import type { WordModel } from "~/models";

export const ABOUT_HOSPITAL: WordModel[] = [
    {
        id: 1,
        korean: "병원",
        read: "byeong-won",
        english: "hospital",
        lao: "ໂຮງໝໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 병원에 갑니다.",
                read: "Jeoneun byeong-won-e gamnida.",
                english: "I go to the hospital.",
                lao: "ຂ້ອຍໄປໂຮງໝໍ.",
            },
        ],
    },
    {
        id: 2,
        korean: "의사",
        read: "ui-sa",
        english: "doctor",
        lao: "ທ່ານໝໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사와 상담합니다.",
                read: "Uisa-wa sangdamhamnida.",
                english: "I consult with the doctor.",
                lao: "ຂ້ອຍປຶກສາກັບໝໍ.",
            },
        ],
    },
    {
        id: 3,
        korean: "간호사",
        read: "gan-ho-sa",
        english: "nurse",
        lao: "ນາງພະຍາບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "간호사가 도와줍니다.",
                read: "Gan-ho-sa-ga dowajumnida.",
                english: "The nurse helps me.",
                lao: "ນາງພະຍາບານຊ່ວຍຂ້ອຍ.",
            },
        ],
    },
    {
        id: 4,
        korean: "응급실",
        read: "eung-geup-sil",
        english: "emergency room",
        lao: "ຫ້ອງສຸກເສີນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "저는 응급실에 갑니다.",
                read: "Jeoneun eung-geup-sil-e gamnida.",
                english: "I go to the emergency room.",
                lao: "ຂ້ອຍໄປຫ້ອງສຸກເສີນ.",
            },
        ],
    },
    {
        id: 5,
        korean: "수술",
        read: "su-sul",
        english: "surgery",
        lao: "ການຜ່າຕັດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "수술이 필요합니다.",
                read: "Susul-i pilyohamnida.",
                english: "I need surgery.",
                lao: "ຂ້ອຍຕ້ອງການການຜ່າຕັດ.",
            },
        ],
    },
    {
        id: 6,
        korean: "입원",
        read: "ip-won",
        english: "hospitalization",
        lao: "ການເຂົ້າໂຮງໝໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "입원이 필요합니다.",
                read: "Ipwon-i pilyohamnida.",
                english: "Hospitalization is necessary.",
                lao: "ການເຂົ້າໂຮງໝໍແມ່ນຈໍາເປັນ.",
            },
        ],
    },
    {
        id: 7,
        korean: "퇴원",
        read: "toe-won",
        english: "discharge",
        lao: "ອອກໂຮງໝໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "퇴원을 합니다.",
                read: "Toewon-eul hamnida.",
                english: "I am being discharged.",
                lao: "ຂ້ອຍກຳລັງອອກໂຮງໝໍ.",
            },
        ],
    },
    {
        id: 8,
        korean: "병실",
        read: "byeong-sil",
        english: "ward",
        lao: "ຫ້ອງຜູ້ປ່ວຍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "병실은 깨끗합니다.",
                read: "Byeongsil-eun kkaekkeushamnida.",
                english: "The ward is clean.",
                lao: "ຫ້ອງຜູ້ປ່ວຍສະອາດ.",
            },
        ],
    },
    {
        id: 9,
        korean: "진단서",
        read: "jin-dan-seo",
        english: "medical certificate",
        lao: "ໃບຮັບຮອງທາງການແພດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사가 진단서를 작성했습니다.",
                read: "Uisa-ga jindanseo-reul jakseonghaesseumnida.",
                english: "The doctor wrote a medical certificate.",
                lao: "ໝໍໄດ້ຂຽນໃບຮັບຮອງທາງການແພດ.",
            },
        ],
    },
    {
        id: 10,
        korean: "약",
        read: "yak",
        english: "medicine",
        lao: "ຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "약을 복용합니다.",
                read: "Yag-eul bog-yong-ham-ni-da.",
                english: "I take medicine.",
                lao: "ຂ້ອຍກິນຢາ.",
            },
        ],
    },
    {
        id: 11,
        korean: "주사",
        read: "ju-sa",
        english: "injection",
        lao: "ການສັກຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "주사를 맞았습니다.",
                read: "Jusa-reul maj-ass-eum-ni-da.",
                english: "I received an injection.",
                lao: "ຂ້ອຍໄດ້ຮັບການສັກຢາ.",
            },
        ],
    },
    {
        id: 12,
        korean: "응급차",
        read: "eung-geup-cha",
        english: "ambulance",
        lao: "ລົດພະຍາບານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "응급차가 도착했습니다.",
                read: "Eung-geup-cha-ga dochak-haesseum-ni-da.",
                english: "The ambulance has arrived.",
                lao: "ລົດພະຍາບານໄດ້ມາຮອດແລ້ວ.",
            },
        ],
    },
    {
        id: 13,
        korean: "건강보험",
        read: "geon-gang-bo-heom",
        english: "health insurance",
        lao: "ປະກັນສຸຂະພາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "건강보험이 있나요?",
                read: "Geon-gang-bo-heom-i iss-na-yo?",
                english: "Do you have health insurance?",
                lao: "ເຈົ້າມີປະກັນສຸຂະພາບບໍ?",
            },
        ],
    },
    {
        id: 14,
        korean: "처방전",
        read: "cheo-bang-jeon",
        english: "prescription",
        lao: "ໃບສັ່ງຢາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "의사가 처방전을 썼습니다.",
                read: "Uisa-ga cheobangjeon-eul sseoss-eum-ni-da.",
                english: "The doctor wrote a prescription.",
                lao: "ໝໍໄດ້ຂຽນໃບສັ່ງຢາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "접수",
        read: "jeop-su",
        english: "reception",
        lao: "ການຕ້ອນຮັບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "접수에서 안내를 받았습니다.",
                read: "Jeop-su-e-seo an-nae-reul bad-ass-eum-ni-da.",
                english: "I received guidance at the reception.",
                lao: "ຂ້ອຍໄດ້ຮັບການແນະນໍາທີ່ການຕ້ອນຮັບ.",
            },
        ],
    },
];
