import type { WordModel } from "~/models";

export const ABOUT_DAILY_LIFE: WordModel[] = [
    {
        id: 1,
        korean: "meoktta",
        read: "먹다",
        english: "eat",
        lao: "ເຮັດ",
        speech: "v",
    },
    {
        id: 2,
        korean: "yorihada",
        read: "요리하다",
        english: "cook",
        lao: "ກິນ",
        speech: "v",
    },
    {
        id: 3,
        korean: "gage",
        read: "가게",
        english: "shop",
        lao: "ຮ່າງການຂາຍ",
        speech: "n",
    },
    {
        id: 4,
        korean: "syawoereul hada",
        read: "샤워를 하다",
        english: "shower",
        lao: "ສະໂຫລະ",
        speech: "v",
    },
    {
        id: 5,
        korean: "nagada",
        read: "나가다",
        english: "go out",
        lao: "ໄປຫາຫົວ",
        speech: "v",
    },
    {
        id: 6,
        korean: "ilhada",
        read: "일하다",
        english: "work",
        lao: "ຈັດລາວ",
        speech: "v",
    },
    {
        id: 7,
        korean: "swida",
        read: "쉬다",
        english: "rest",
        lao: "ພັນ",
        speech: "v",
    },
    {
        id: 8,
        korean: "kkumeul kkuda",
        read: "꿈을 꾸다",
        english: "dream",
        lao: "ຂຸມ",
        speech: "v",
    },
    {
        id: 9,
        korean: "doraoda",
        read: "돌아오다",
        english: "return",
        lao: "ກັບຄືນ",
        speech: "v",
    },
    {
        id: 10,
        korean: "sinmuneul iktta",
        read: "신문을 읽다",
        english: "read the paper",
        lao: "ອ່ານພື້ນ",
        speech: "v",
    },
];
