import type { WordModel } from "~/models";

export const ABOUT_COLORS: WordModel[] = [
    {
        id: 1,
        korean: "빨간색",
        read: "ppal-gan-saek",
        english: "Red",
        lao: "ສີແດງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "빨간색 꽃이 아름다워요.",
                read: "Ppal-gan-saek kko-chi a-reum-da-weo-yo.",
                english: "The red flower is beautiful.",
                lao: "ດອກໄມ້ສີແດງງາມ.",
            },
        ],
    },
    {
        id: 2,
        korean: "파란색",
        read: "pa-ran-saek",
        english: "Blue",
        lao: "ສີຟ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "파란색 하늘이 맑아요.",
                read: "Pa-ran-saek ha-neu-ri mal-ga-yo.",
                english: "The blue sky is clear.",
                lao: "ຟ້າສີຟ້າໃສ.",
            },
        ],
    },
    {
        id: 3,
        korean: "초록색",
        read: "cho-rok-saek",
        english: "Green",
        lao: "ສີຂຽວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "초록색 잔디가 푸르러요.",
                read: "Cho-rok-saek jan-di-ga pu-reu-reo-yo.",
                english: "The green grass is lush.",
                lao: "ຫຍ້າສີຂຽວຊື່ນ.",
            },
        ],
    },
    {
        id: 4,
        korean: "노란색",
        read: "no-ran-saek",
        english: "Yellow",
        lao: "ສີເຫລືອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "노란색 해바라기가 피었어요.",
                read: "No-ran-saek hae-ba-ra-gi-ga pi-eo-sseo-yo.",
                english: "The yellow sunflower has bloomed.",
                lao: "ດອກທານຕາເວັນສີເຫລືອງບານແລ້ວ.",
            },
        ],
    },
    {
        id: 5,
        korean: "주황색",
        read: "ju-hwang-saek",
        english: "Orange",
        lao: "ສີສົ້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "주황색 과일이 달아요.",
                read: "Ju-hwang-saek gwa-il-i da-ra-yo.",
                english: "The orange fruit is sweet.",
                lao: "ໝາກໄມ້ສີສົ້ມຫວານ.",
            },
        ],
    },
    {
        id: 6,
        korean: "보라색",
        read: "bo-ra-saek",
        english: "Purple",
        lao: "ສີມ່ວງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "보라색 꽃이 피었어요.",
                read: "Bo-ra-saek kkot-i pi-eo-sseo-yo.",
                english: "The purple flower has bloomed.",
                lao: "ດອກໄມ້ສີມ່ວງບານແລ້ວ.",
            },
        ],
    },
    {
        id: 7,
        korean: "분홍색",
        read: "bun-hong-saek",
        english: "Pink",
        lao: "ສີບົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "분홍색 장미가 예뻐요.",
                read: "Bun-hong-saek jang-mi-ga ye-ppeo-yo.",
                english: "The pink rose is pretty.",
                lao: "ກຸຫຼາບສີບົວງາມ.",
            },
        ],
    },
    {
        id: 8,
        korean: "갈색",
        read: "gal-saek",
        english: "Brown",
        lao: "ສີນ້ໍາຕານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "갈색 나무가 튼튼해 보여요.",
                read: "Gal-saek na-mu-ga teun-teun-hae bo-yeo-yo.",
                english: "The brown tree looks sturdy.",
                lao: "ໄມ້ສີນ້ໍາຕານເບິ່ງແຂງແຮງ.",
            },
        ],
    },
    {
        id: 9,
        korean: "검은색",
        read: "geo-meun-saek",
        english: "Black",
        lao: "ສີດໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "검은색 고양이가 귀여워요.",
                read: "Geo-meun-saek go-yang-i-ga gwi-yeo-wo-yo.",
                english: "The black cat is cute.",
                lao: "ແມວສີດໍານ່າຮັກ.",
            },
        ],
    },
    {
        id: 10,
        korean: "하얀색",
        read: "ha-yan-saek",
        english: "White",
        lao: "ສີຂາວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "하얀색 눈이 내려요.",
                read: "Ha-yan-saek nun-i nae-ryeo-yo.",
                english: "The white snow is falling.",
                lao: "ຫິມະສີຂາວກໍາລັງຕົກ.",
            },
        ],
    },
    {
        id: 11,
        korean: "회색",
        read: "hoe-saek",
        english: "Gray",
        lao: "ສີເທົາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "회색 구름이 많아요.",
                read: "Hoe-saek gu-reum-i man-a-yo.",
                english: "There are many gray clouds.",
                lao: "ມີເມກສີເທົາຫລາຍ.",
            },
        ],
    },
    {
        id: 12,
        korean: "은색",
        read: "eun-saek",
        english: "Silver",
        lao: "ສີເງິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "은색 반지가 반짝여요.",
                read: "Eun-saek ban-ji-ga ban-jjak-yeo-yo.",
                english: "The silver ring sparkles.",
                lao: "ວົງແຫວນສີເງິນປະກາຍ.",
            },
        ],
    },
    {
        id: 13,
        korean: "금색",
        read: "geum-saek",
        english: "Gold",
        lao: "ສີຄໍາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "금색 열쇠가 빛나요.",
                read: "Geum-saek yeol-soe-ga bit-na-yo.",
                english: "The gold key shines.",
                lao: "ກະແຈສີຄໍາສອ່ງແສງ.",
            },
        ],
    },
    {
        id: 14,
        korean: "터키옥색",
        read: "teo-ki-ok-saek",
        english: "Turquoise",
        lao: "ສີຟ້າເຂັມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "터키옥색 바다가 아름다워요.",
                read: "Teo-ki-ok-saek ba-da-ga a-reum-da-weo-yo.",
                english: "The turquoise sea is beautiful.",
                lao: "ທະເລສີຟ້າເຂັມງາມ.",
            },
        ],
    },
    {
        id: 15,
        korean: "남색",
        read: "nam-saek",
        english: "Indigo",
        lao: "ສີນ້ໍາເງິນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "남색 하늘이 깊어요.",
                read: "Nam-saek ha-neu-ri gi-peo-yo.",
                english: "The indigo sky is deep.",
                lao: "ທ້ອງຟ້າສີນ້ໍາເງິນລືກ.",
            },
        ],
    },
    {
        id: 16,
        korean: "고동색",
        read: "go-dong-saek",
        english: "Maroon",
        lao: "ສີມ່ວງແດງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "고동색 나무가 멋져요.",
                read: "Go-dong-saek na-mu-ga meot-jjeo-yo.",
                english: "The maroon tree looks great.",
                lao: "ໄມ້ສີມ່ວງແດງເບິ່ງດີ.",
            },
        ],
    },
    {
        id: 17,
        korean: "연보라색",
        read: "yeon-bo-ra-saek",
        english: "Lavender",
        lao: "ສີມ່ວງອ່ອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "연보라색 꽃이 예뻐요.",
                read: "Yeon-bo-ra-saek kkot-i ye-ppeo-yo.",
                english: "The lavender flower is pretty.",
                lao: "ດອກໄມ້ສີມ່ວງອ່ອນງາມ.",
            },
        ],
    },
    {
        id: 18,
        korean: "복숭아색",
        read: "bok-sung-a-saek",
        english: "Peach",
        lao: "ສີບົວອ່ອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "복숭아색 하늘이 아름다워요.",
                read: "Bok-sung-a-saek ha-neu-ri a-reum-da-weo-yo.",
                english: "The peach-colored sky is beautiful.",
                lao: "ຟ້າສີບົວອ່ອນງາມ.",
            },
        ],
    },
    {
        id: 19,
        korean: "청록색",
        read: "cheong-rok-saek",
        english: "Cyan",
        lao: "ສີຟ້າຂຽວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "청록색 바다가 맑아요.",
                read: "Cheong-rok-saek ba-da-ga mal-ga-yo.",
                english: "The cyan sea is clear.",
                lao: "ທະເລສີຟ້າຂຽວໃສ.",
            },
        ],
    },
    {
        id: 20,
        korean: "자홍색",
        read: "ja-hong-saek",
        english: "Magenta",
        lao: "ສີບົວແກ້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "자홍색 꽃이 피었어요.",
                read: "Ja-hong-saek kkot-i pi-eo-sseo-yo.",
                english: "The magenta flower has bloomed.",
                lao: "ດອກໄມ້ສີບົວແກ້ມບານແລ້ວ.",
            },
        ],
    },
];
