import type { WordModel } from "~/models";

export const ABOUT_SCHOOLS: WordModel[] = [
    {
        id: 1,
        korean: "교실",
        read: "gyo-sil",
        english: "Classroom",
        lao: "ຫ້ອງຮຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 교실에서 공부하고 있습니다.",
                read: "hak-saeng-deu-li gyo-sil-e-seo gong-bu-ha-go it-seum-ni-da.",
                english: "The students are studying in the classroom.",
                lao: "ນັກຮຽນກຳລັງຮຽນຢູ່ໃນຫ້ອງຮຽນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "선생님",
        read: "seon-saeng-nim",
        english: "Teacher",
        lao: "ຄູສອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "선생님이 수업을 하고 있습니다.",
                read: "seon-saeng-nim-i su-eop-eul ha-go it-seum-ni-da.",
                english: "The teacher is teaching a class.",
                lao: "ຄູກຳລັງສອນຢູ່ໃນຫ້ອງຮຽນ.",
            },
        ],
    },
    {
        id: 3,
        korean: "학생",
        read: "hak-saeng",
        english: "Student",
        lao: "ນັກຮຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 교실에서 공부하고 있습니다.",
                read: "hak-saeng-deu-li gyo-sil-e-seo gong-bu-ha-go it-seum-ni-da.",
                english: "The students are studying in the classroom.",
                lao: "ນັກຮຽນກຳລັງຮຽນຢູ່ໃນຫ້ອງຮຽນ.",
            },
        ],
    },
    {
        id: 4,
        korean: "교장",
        read: "gyo-jang",
        english: "Principal",
        lao: "ຜູ້ອໍານວຍການ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "교장이 학교를 둘러보고 있습니다.",
                read: "gyo-jang-i hak-gyo-reul dul-leo-bo-go it-seum-ni-da.",
                english: "The principal is inspecting the school.",
                lao: "ຜູ້ອໍານວຍການກຳລັງກວດສອບໂຮງຮຽນ.",
            },
        ],
    },
    {
        id: 5,
        korean: "책상",
        read: "chaek-sang",
        english: "Desk",
        lao: "ໂຕະ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생의 책상이 깔끔합니다.",
                read: "hak-saeng-ui chaek-sang-i kkal-kkeum-ham-ni-da.",
                english: "The student's desk is neat.",
                lao: "ໂຕະຂອງນັກຮຽນມີຄວາມສະອາດ.",
            },
        ],
    },
    {
        id: 6,
        korean: "테이블",
        read: "te-i-beul",
        english: "Table",
        lao: "ໂຕະ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도서관에는 많은 테이블이 있습니다.",
                read: "do-seo-gwan-e-neun manh-eun te-i-beul-i it-seum-ni-da.",
                english: "There are many tables in the library.",
                lao: "ມີໂຕະຫລາຍໃນຫ້ອງສະໝຸດ.",
            },
        ],
    },
    {
        id: 7,
        korean: "의자",
        read: "ui-ja",
        english: "Chair",
        lao: "ເກົ້າອີ້",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "교실에 의자가 많이 있습니다.",
                read: "gyo-sil-e ui-ja-ga manh-i it-seum-ni-da.",
                english: "There are many chairs in the classroom.",
                lao: "ມີເກົ້າອີ້ຫລາຍຢູ່ໃນຫ້ອງຮຽນ.",
            },
        ],
    },
    {
        id: 8,
        korean: "칠판",
        read: "chil-pan",
        english: "Board",
        lao: "ກະດານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "선생님이 칠판에 글씨를 쓰고 있습니다.",
                read: "seon-saeng-nim-i chil-pan-e geul-ssi-reul sseu-go it-seum-ni-da.",
                english: "The teacher is writing on the board.",
                lao: "ຄູກຳລັງຂຽນບົດຮຽນຢູ່ທີ່ກະດານ.",
            },
        ],
    },
    {
        id: 9,
        korean: "도서관",
        read: "do-seo-gwan",
        english: "Library",
        lao: "ຫ້ອງສະໝຸດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도서관에서 책을 읽고 있습니다.",
                read: "do-seo-gwan-e-seo chaek-eul ilk-go it-seum-ni-da.",
                english: "I am reading a book in the library.",
                lao: "ຂ້ອຍກຳລັງອ່ານປື້ມຢູ່ໃນຫ້ອງສະໝຸດ.",
            },
        ],
    },
    {
        id: 10,
        korean: "교과서",
        read: "gyo-gwa-seo",
        english: "Textbook",
        lao: "ປື້ມຮຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 교과서를 읽고 있습니다.",
                read: "hak-saeng-deul-i gyo-gwa-seo-reul ilk-go it-seum-ni-da.",
                english: "The students are reading their textbooks.",
                lao: "ນັກຮຽນກຳລັງອ່ານປື້ມຮຽນຂອງພວກເຂົາ.",
            },
        ],
    },
    {
        id: 11,
        korean: "연필",
        read: "yeon-pil",
        english: "Pencil",
        lao: "ສໍດຳ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "연필로 글씨를 씁니다.",
                read: "yeon-pil-lo geul-ssi-reul sseum-ni-da.",
                english: "I write with a pencil.",
                lao: "ຂ້ອຍຂຽນດ້ວຍສໍດຳ.",
            },
        ],
    },
    {
        id: 12,
        korean: "펜",
        read: "pen",
        english: "Pen",
        lao: "ປາກກາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "펜으로 노트를 씁니다.",
                read: "pen-eu-ro no-teu-reul sseum-ni-da.",
                english: "I write notes with a pen.",
                lao: "ຂ້ອຍຂຽນໂນດດ້ວຍປາກກາ.",
            },
        ],
    },
    {
        id: 13,
        korean: "공책",
        read: "gong-chaek",
        english: "Notebook",
        lao: "ສົມຸດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "노트에 중요한 것을 적었습니다.",
                read: "no-teu-e jung-yo-han geo-seul jeo-geot-seum-ni-da.",
                english: "I wrote down important things in my notebook.",
                lao: "ຂ້ອຍຈົດສິ່ງທີ່ສຳຄັນໄວ້ໃນສົມຸດ.",
            },
        ],
    },
    {
        id: 14,
        korean: "숙제",
        read: "suk-je",
        english: "Homework",
        lao: "ວຽກບ້ານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "숙제를 다 했습니다.",
                read: "suk-je-reul da haet-seum-ni-da.",
                english: "I finished all my homework.",
                lao: "ຂ້ອຍເຮັດວຽກບ້ານສຳເລັດແລ້ວ.",
            },
        ],
    },
    {
        id: 15,
        korean: "시험",
        read: "si-heom",
        english: "Exam",
        lao: "ການສອບເສັງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "다음 주에 시험이 있습니다.",
                read: "da-eum ju-e si-heom-i it-seum-ni-da.",
                english: "There is an exam next week.",
                lao: "ມີການສອບເສັງໃນອາທິດໜ້າ.",
            },
        ],
    },
    {
        id: 16,
        korean: "학교 버스",
        read: "hak-gyo beos",
        english: "School bus",
        lao: "ລົດໂຮງຮຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 학교 버스를 탑니다.",
                read: "hak-saeng-deul-i hak-gyo beos-reul tam-ni-da.",
                english: "The students ride the school bus.",
                lao: "ນັກຮຽນນັ່ງລົດໂຮງຮຽນ.",
            },
        ],
    },
    {
        id: 17,
        korean: "운동장",
        read: "un-dong-jang",
        english: "Playground",
        lao: "ສະຫນາມກິລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아이들이 운동장에서 놀고 있습니다.",
                read: "a-i-deul-i un-dong-jang-e-seo nol-go it-seum-ni-da.",
                english: "The children are playing in the playground.",
                lao: "ເດັກໆກຳລັງຫລີ້ນຢູ່ໃນສະຫນາມກິລາ.",
            },
        ],
    },
    {
        id: 18,
        korean: "급식실",
        read: "geup-sik-sil",
        english: "Cafeteria",
        lao: "ຫ້ອງອາຫານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 급식실에서 점심을 먹습니다.",
                read: "hak-saeng-deul-i geup-sik-sil-e-seo jeom-sim-eul meok-seum-ni-da.",
                english: "The students are having lunch in the cafeteria.",
                lao: "ນັກຮຽນກຳລັງກີນເຂົ້າສວຍໃນຫ້ອງອາຫານ.",
            },
        ],
    },
    {
        id: 19,
        korean: "체육관",
        read: "che-yuk-gwan",
        english: "Gymnasium",
        lao: "ສະຫນາມກິລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 체육관에서 농구를 하고 있습니다.",
                read: "hak-saeng-deul-i che-yuk-gwan-e-seo nong-gu-reul ha-go it-seum-ni-da.",
                english:
                    "The students are playing basketball in the gymnasium.",
                lao: "ນັກຮຽນກຳລັງຫລິ້ນບານບ້ວງຢູ່ໃນສະຫນາມກິລາ.",
            },
        ],
    },
    {
        id: 20,
        korean: "컴퓨터실",
        read: "keom-pyu-teo-sil",
        english: "Computer room",
        lao: "ຫ້ອງຄອມພິວເຕີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "학생들이 컴퓨터실에서 수업을 듣고 있습니다.",
                read: "hak-saeng-deul-i keom-pyu-teo-sil-e-seo su-eop-eul deud-go it-seum-ni-da.",
                english:
                    "The students are attending a class in the computer room.",
                lao: "ນັກຮຽນກຳລັງຮຽນຢູ່ໃນຫ້ອງຄອມພິວເຕີ.",
            },
        ],
    },
    {
        id: 21,
        korean: "동기",
        read: "donggi",
        english: "classmate",
        lao: "ເພື່ອຮ່ວມຫ້ອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 내 동기입니다.",
                read: "geu-neun nae donggi-imnida.",
                english: "He is my classmate.",
                lao: "ລາວເປັນເພື່ອຮ່ວມຫ້ອງຂອງຂ້ອຍ.",
            },
        ],
    },
    {
        id: 22,
        korean: "자",
        read: "ja",
        english: "ruler",
        lao: "ໄມ້ບັນທັກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "자로 길이를 잰다.",
                read: "ja-ro giri-reul jaenda.",
                english: "Measure the length with a ruler.",
                lao: "ແທັກຄວາມຄວາມຍາວດ້ວຍໄມ້ບັນທັກ.",
            },
        ],
    },
    {
        id: 23,
        korean: "지우개",
        read: "jiugae",
        english: "eraser",
        lao: "ຢາງລຶບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "지우개로 실수를 지웠다.",
                read: "jiugae-ro silsureul jiweotda.",
                english: "Erased the mistake with an eraser.",
                lao: "ລຶບຂໍ້ຜິດພາດດ້ວຍຢາງລຶບ",
            },
        ],
    },
    {
        id: 24,
        korean: "분필",
        read: "bunpil",
        english: "chalk",
        lao: "ສໍຂາວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "분필로 칠했다.",
                read: "bunpil-ro chilhaetda.",
                english: "Wrote with chalk.",
                lao: "ຂຽນດ້ວຍສໍຂາວ.",
            },
        ],
    },
    {
        id: 25,
        korean: "교복",
        read: "gyobok",
        english: "school uniform",
        lao: "ເຄື່ອງແບບນັກຮຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 학교 교복을 입었다.",
                read: "geuneun hakgyo gyobok-eul ibeotda.",
                english: "He wore the school uniform.",
                lao: "ເປັນໂປຣແກມຊື່ຮັກຂອງໂມງ.",
            },
        ],
    },
    {
        id: 26,
        korean: "도서관",
        read: "do-seo-gwan",
        english: "library",
        lao: "ຫ້ອງສະໝຸດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도서관에서 책을 읽고 있습니다.",
                read: "do-seo-gwan-e-seo chaek-eul ilk-go it-seum-ni-da.",
                english: "I am reading a book in the library.",
                lao: "ຂ້ອຍກຳລັງອ່ານປື້ມຢູ່ໃນຫ້ອງສະໝຸດ.",
            },
        ],
    },
    {
        id: 27,
        korean: "사서",
        read: "sa-seo",
        english: "librarian",
        lao: "ບິບລິຣາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "사서가 책을 정리하고 있습니다.",
                read: "sa-seo-ga chaek-eul jeong-ri-ha-go it-seum-ni-da.",
                english: "The librarian is organizing books.",
                lao: "ບິບລິຣາກຳລັງຈັດເລຂົ້າ.",
            },
        ],
    },
    {
        id: 28,
        korean: "책",
        read: "chaek",
        english: "book",
        lao: "ປື້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 흥미로운 책을 읽고 있습니다.",
                read: "na-neun heung-mi-ro-un chaek-eul ilk-go it-seum-ni-da.",
                english: "I am reading an interesting book.",
                lao: "ຂ້ອຍກຳລັງອ່ານປື້ມທີ່ມີຄວາມນົດຫຼົ້ມ.",
            },
        ],
    },
    {
        id: 29,
        korean: "책꽂이",
        read: "chaek-ggot-ji",
        english: "bookshelf",
        lao: "ຊັ້ນວາງປື້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "책꽂이에 많은 책들이 있습니다.",
                read: "chaek-ggot-ji-e manh-eun chaek-deul-i it-seum-ni-da.",
                english: "There are many books on the bookshelf.",
                lao: "ມີປື້ມຫລາຍຢູ່ຊັ້ນວາງປື້ມ.",
            },
        ],
    },
    {
        id: 30,
        korean: "잡지",
        read: "jab-ji",
        english: "magazine",
        lao: "ນິຕະສານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 도서관에서 잡지를 읽었습니다.",
                read: "na-neun do-seo-gwan-e-seo jab-ji-reul ilk-eoss-seum-ni-da.",
                english: "I read a magazine in the library.",
                lao: "ຂ້ອຍອ່ານນິຕະສານຢູ່ໃນຫ້ອງສະໝຸດ.",
            },
        ],
    },
    {
        id: 31,
        korean: "열람실",
        read: "yeol-lam-sil",
        english: "reading room",
        lao: "ຫ້ອງອ່ານປື້ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "도서관 열람실은 공부하기에 좋습니다.",
                read: "do-seo-gwan yeol-lam-sil-eun gong-bu-ha-gi-e joh-seum-ni-da.",
                english:
                    "The reading room in the library is good for studying.",
                lao: "ຫ້ອງອ່ານປື້ມໃນຫ້ອງສະໝຸດເຫມາະສົມສຳລັບການຮຽນ.",
            },
        ],
    },
];
