import type { WordModel } from "~/models";

export const ABOUT_HOUSE_BEDROOM: WordModel[] = [
    {
        id: 1,
        korean: "침대",
        read: "chim-dae",
        english: "bed",
        lao: "ຕຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "침대에서 잠을 자요.",
                read: "Chim-dae-e-seo jam-eul ja-yo.",
                english: "I sleep in the bed.",
                lao: "ຂ້ອຍນອນຢູ່ໃນຕຽງ.",
            },
        ],
    },
    {
        id: 2,
        korean: "베개",
        read: "be-gae",
        english: "pillow",
        lao: "ໝອນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "베개를 베고 자요.",
                read: "Be-gae-reul be-go ja-yo.",
                english: "I sleep with my head on the pillow.",
                lao: "ຂ້ອຍນອນໜຸນໝອນ.",
            },
        ],
    },
    {
        id: 3,
        korean: "이불",
        read: "i-bul",
        english: "blanket",
        lao: "ຜ້າຫົ່ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이불을 덮고 자요.",
                read: "I-bul-eul deop-go ja-yo.",
                english: "I sleep with a blanket.",
                lao: "ຂ້ອຍນອນຫົ່ມຜ້າ.",
            },
        ],
    },
    {
        id: 4,
        korean: "옷장",
        read: "ot-jang",
        english: "closet",
        lao: "ຕູ້ເສື້ອຜ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "옷장에 옷을 걸어요.",
                read: "Ot-jang-e ot-eul geol-eo-yo.",
                english: "I hang clothes in the closet.",
                lao: "ຂ້ອຍແຂວນເສື້ອຜ້າໃນຕູ້.",
            },
        ],
    },
    {
        id: 5,
        korean: "화장대",
        read: "hwa-jang-dae",
        english: "vanity",
        lao: "ໂຕະແຕ່ງໜ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "화장대 앞에서 화장을 해요.",
                read: "Hwa-jang-dae ap-e-seo hwa-jang-eul hae-yo.",
                english: "I do my makeup at the vanity.",
                lao: "ຂ້ອຍແຕ່ງໜ້າຢູ່ໂຕະແຕ່ງໜ້າ.",
            },
        ],
    },
    {
        id: 6,
        korean: "서랍장",
        read: "seo-rab-jang",
        english: "dresser",
        lao: "ຕູ້ເກັບເຄື່ອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "서랍장에 옷을 정리해요.",
                read: "Seo-rab-jang-e ot-eul jeong-ri-hae-yo.",
                english: "I organize clothes in the dresser.",
                lao: "ຂ້ອຍຈັດເສື້ອຜ້າໃນຕູ້ເກັບເຄື່ອງ.",
            },
        ],
    },
    {
        id: 7,
        korean: "전등",
        read: "jeon-deung",
        english: "lamp",
        lao: "ໄຟສ້ອງສະຫວ່າງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "전등을 켜요.",
                read: "Jeon-deung-eul kyeo-yo.",
                english: "I turn on the lamp.",
                lao: "ຂ້ອຍເປີດໄຟສ້ອງສະຫວ່າງ.",
            },
        ],
    },
    {
        id: 8,
        korean: "카펫",
        read: "ka-pet",
        english: "carpet",
        lao: "ພື້ນພາບ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "침실에 카펫을 깔았어요.",
                read: "Chim-sil-e ka-pet-eul kkal-ass-eo-yo.",
                english: "I laid a carpet in the bedroom.",
                lao: "ຂ້ອຍປູພື້ນພາບໃນຫ້ອງນອນ.",
            },
        ],
    },
    {
        id: 9,
        korean: "커튼",
        read: "keo-teun",
        english: "curtain",
        lao: "ຜ້າມ່ານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "커튼을 닫아요.",
                read: "Keo-teun-eul dad-a-yo.",
                english: "I close the curtains.",
                lao: "ຂ້ອຍປິດຜ້າມ່ານ.",
            },
        ],
    },
    {
        id: 10,
        korean: "거울",
        read: "geo-ul",
        english: "mirror",
        lao: "ກະຈົກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "거울을 보며 머리를 빗어요.",
                read: "Geo-ul-eul bo-myeo meo-ri-reul bit-eo-yo.",
                english: "I comb my hair while looking in the mirror.",
                lao: "ຂ້ອຍຫວີຜົມໂດຍເບິ່ງໃນກະຈົກ.",
            },
        ],
    },
    {
        id: 11,
        korean: "책장",
        read: "chaek-jang",
        english: "bookshelf",
        lao: "ຕູ້ໜັງສື",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "책장에 책을 꽂아요.",
                read: "Chaek-jang-e chaeg-eul kkoj-a-yo.",
                english: "I put books on the bookshelf.",
                lao: "ຂ້ອຍສຽບໜັງສືໃນຕູ້ໜັງສື.",
            },
        ],
    },
    {
        id: 12,
        korean: "알람 시계",
        read: "al-lam si-gye",
        english: "alarm clock",
        lao: "ໂມງປຸກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 알람 시계가 울렸어요.",
                read: "A-chim-e al-lam si-gye-ga ul-lyeoss-eo-yo.",
                english: "The alarm clock went off in the morning.",
                lao: "ໂມງປຸກດັງໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 13,
        korean: "서랍",
        read: "seo-rab",
        english: "drawer",
        lao: "ລິ້ນຊັກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "서랍에 옷을 넣어요.",
                read: "Seo-rab-e ot-eul neoeo-yo.",
                english: "I put clothes in the drawer.",
                lao: "ຂ້ອຍເອົາເສື້ອຜ້າໃສ່ໃນລິ້ນຊັກ.",
            },
        ],
    },
    {
        id: 14,
        korean: "침대 시트",
        read: "chim-dae si-teu",
        english: "bed sheet",
        lao: "ຜ້າປູຕຽງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "침대 시트를 바꿨어요.",
                read: "Chim-dae si-teu-reul bakkwoss-eo-yo.",
                english: "I changed the bed sheets.",
                lao: "ຂ້ອຍປ່ຽນຜ້າປູຕຽງ.",
            },
        ],
    },
    {
        id: 15,
        korean: "이불 덮개",
        read: "i-bul deop-gae",
        english: "duvet cover",
        lao: "ຜ້າຫົ່ມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "이불 덮개를 씌웠어요.",
                read: "I-bul deop-gae-reul ssiwoss-eo-yo.",
                english: "I put on the duvet cover.",
                lao: "ຂ້ອຍປູຜ້າຫົ່ມ.",
            },
        ],
    },
];
