import type { WordModel } from "~/models";

export const ABOUT_BODY: WordModel[] = [
    {
        id: 1,
        korean: "머리",
        read: "meo-ri",
        english: "head",
        lao: "ຫົວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 머리를 흔들었다.",
                read: "Geuneun meorireul heundeureotda.",
                english: "He shook his head.",
                lao: "ລາວໄດ້ສັ່ນຫົວຂອງລາວ.",
            },
        ],
    },
    {
        id: 2,
        korean: "눈",
        read: "nun",
        english: "eye",
        lao: "ຕາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 큰 눈을 가지고 있다.",
                read: "Geunyeoneun keun nuneul gajigo itda.",
                english: "She has big eyes.",
                lao: "ນາງມີຕາໃຫຍ່.",
            },
        ],
    },
    {
        id: 3,
        korean: "귀",
        read: "gwi",
        english: "ear",
        lao: "ຫູ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나는 그녀의 속삭임을 들었다.",
                read: "Naneun geunyeoui soksagimeul deureotda.",
                english: "I heard her whisper.",
                lao: "ຂ້ອຍໄດ້ຍິນນາງກະຊິບ.",
            },
        ],
    },
    {
        id: 4,
        korean: "코",
        read: "ko",
        english: "nose",
        lao: "ດັງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀의 코는 작다.",
                read: "Geunyeoui koneun jagda.",
                english: "Her nose is small.",
                lao: "ດັງຂອງນາງເປັນແຫຼມ.",
            },
        ],
    },
    {
        id: 5,
        korean: "입",
        read: "ib",
        english: "mouth",
        lao: "ປາກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 입을 크게 벌렸다.",
                read: "Geuneun ibeul keuge beollyeotda.",
                english: "He opened his mouth wide.",
                lao: "ລາວເປີດປາກກວ້າງ.",
            },
        ],
    },
    {
        id: 6,
        korean: "치아",
        read: "chi-a",
        english: "teeth",
        lao: "ແຂ້ວ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 하얀 치아를 가지고 있다.",
                read: "Geunyeoneun hayan chi-areul gajigo itda.",
                english: "She has white teeth.",
                lao: "ນາງມີແຂ້ວສີຂາວ.",
            },
        ],
    },
    {
        id: 7,
        korean: "혀",
        read: "hyeo",
        english: "tongue",
        lao: "ລີ້ນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 혀로 아이스크림을 핥았다.",
                read: "Geuneun hyeoro aiseukeurimeul halatda.",
                english: "He licked the ice cream with his tongue.",
                lao: "ລາວໄດ້ລີ້ນໄອສະກຣີມດ້ວຍລີ້ນ.",
            },
        ],
    },
    {
        id: 8,
        korean: "목",
        read: "mok",
        english: "neck",
        lao: "ຄໍ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 목걸이를 하고 있다.",
                read: "Geunyeoneun mokgeorireul hago itda.",
                english: "She is wearing a necklace.",
                lao: "ນາງໄດ້ສວມສາຍຄໍ.",
            },
        ],
    },
    {
        id: 9,
        korean: "어깨",
        read: "eo-kkae",
        english: "shoulder",
        lao: "ໄຫຼ່",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 나의 어깨를 두드렸다.",
                read: "Geuneun naui eokkaereul dudeureotda.",
                english: "He patted my shoulder.",
                lao: "ລາວຕົບໄຫຼ່ຂອງຂ້ອຍ.",
            },
        ],
    },
    {
        id: 10,
        korean: "팔",
        read: "pal",
        english: "arm",
        lao: "ແຂນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 팔에 문신이 있다.",
                read: "Geunyeoneun pare munshini itda.",
                english: "She has a tattoo on her arm.",
                lao: "ນາງມີຮອຍສັກຢູ່ແຂນ.",
            },
        ],
    },
    {
        id: 11,
        korean: "손",
        read: "son",
        english: "hand",
        lao: "ມື",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 손을 씻었다.",
                read: "Geuneun soneul ssiseotda.",
                english: "He washed his hands.",
                lao: "ລາວລ້າງມືຂອງລາວ.",
            },
        ],
    },
    {
        id: 12,
        korean: "손가락",
        read: "son-ga-rak",
        english: "finger",
        lao: "ນິ້ວມື",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 손가락으로 가리켰다.",
                read: "Geunyeoneun songarageuro garikyeotda.",
                english: "She pointed with her finger.",
                lao: "ນາງຊີ້ດ້ວຍນິ້ວມື.",
            },
        ],
    },
    {
        id: 13,
        korean: "다리",
        read: "da-ri",
        english: "leg",
        lao: "ຂາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 다리를 다쳤다.",
                read: "Geuneun darireul dachyeotda.",
                english: "He hurt his leg.",
                lao: "ລາວໄດ້ບາດແຜທີ່ຂາ.",
            },
        ],
    },
    {
        id: 14,
        korean: "무릎",
        read: "mu-reup",
        english: "knee",
        lao: "ຂໍເຂົາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 무릎을 꿇었다.",
                read: "Geunyeoneun mureupeul kkureotda.",
                english: "She knelt down.",
                lao: "ນາງຄຸກເຂົ່າລົງ.",
            },
        ],
    },
    {
        id: 15,
        korean: "발",
        read: "bal",
        english: "foot",
        lao: "ຕີນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 발을 다쳤다.",
                read: "Geuneun bareul dachyeotda.",
                english: "He hurt his foot.",
                lao: "ລາວໄດ້ບາດແຜທີ່ຕີນ.",
            },
        ],
    },
    {
        id: 16,
        korean: "발가락",
        read: "bal-ga-rak",
        english: "toe",
        lao: "ນິ້ວຕີນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 발가락을 다쳤다.",
                read: "Geunyeoneun balgarageul dachyeotda.",
                english: "She hurt her toe.",
                lao: "ນາງໄດ້ບາດແຜທີ່ນິ້ວຕີນ.",
            },
        ],
    },
    {
        id: 17,
        korean: "등",
        read: "deung",
        english: "back",
        lao: "ຫລັງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그는 등을 긁었다.",
                read: "Geuneun deungeul geulgeotda.",
                english: "He scratched his back.",
                lao: "ລາວຂີດຫລັງຂອງລາວ.",
            },
        ],
    },
    {
        id: 18,
        korean: "배",
        read: "bae",
        english: "stomach",
        lao: "ທ້ອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그녀는 배가 아팠다.",
                read: "Geunyeoneun baega apatda.",
                english: "She had a stomachache.",
                lao: "ນາງປວດທ້ອງ.",
            },
        ],
    },
    {
        id: 19,
        korean: "심장",
        read: "sim-jang",
        english: "heart",
        lao: "ຫົວໃຈ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그의 심장은 빠르게 뛰고 있었다.",
                read: "Geuui simjangeun ppareuge ttwiggo ittda.",
                english: "His heart was beating fast.",
                lao: "ຫົວໃຈຂອງລາວເຕັ້ນໄວ.",
            },
        ],
    },
    {
        id: 20,
        korean: "피",
        read: "pi",
        english: "blood",
        lao: "ເລືອດ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "그의 손에서 피가 나고 있다.",
                read: "Geuui soneseo piga nago itda.",
                english: "His hand is bleeding.",
                lao: "ເລືອດກຳລັງໄຫລຈາກມືຂອງລາວ.",
            },
        ],
    },
];
