import type { WordModel } from "~/models";

export const ABOUT_TIMING: WordModel[] = [
    {
        id: 1,
        korean: "시계",
        read: "si-gye",
        english: "clock",
        lao: "ນາລິກາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "벽에 시계가 걸려 있어요.",
                read: "Byeog-e si-gye-ga geol-lyeo iss-eo-yo.",
                english: "The clock is hanging on the wall.",
                lao: "ນາລິກາແຂວນຢູ່ກຳແພງ.",
            },
        ],
    },
    {
        id: 2,
        korean: "알람 시계",
        read: "al-ram si-gye",
        english: "alarm clock",
        lao: "ນາລິກາປຸກ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "아침에 알람 시계가 울렸어요.",
                read: "A-chim-e al-ram si-gye-ga ul-lyeoss-eo-yo.",
                english: "The alarm clock rang in the morning.",
                lao: "ນາລິກາປຸກດັງໃນຕອນເຊົ້າ.",
            },
        ],
    },
    {
        id: 3,
        korean: "손목 시계",
        read: "son-mok si-gye",
        english: "wristwatch",
        lao: "ນາລິກາຂໍ້ມື",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "손목 시계를 차고 있어요.",
                read: "Son-mok si-gye-reul cha-go iss-eo-yo.",
                english: "I am wearing a wristwatch.",
                lao: "ຂ້ອຍສວມນາລິກາຂໍ້ມື.",
            },
        ],
    },
    {
        id: 4,
        korean: "시간",
        read: "si-gan",
        english: "time",
        lao: "ເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "시간을 맞춰서 출발했어요.",
                read: "Si-gan-eul maj-chweo-seo chul-bal-haess-eo-yo.",
                english: "We left on time.",
                lao: "ພວກເຮົາອອກເດີນທາງຕາມເວລາ.",
            },
        ],
    },
    {
        id: 5,
        korean: "초",
        read: "cho",
        english: "second",
        lao: "ວິນາທີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "3초 동안 기다렸어요.",
                read: "Sam-cho dong-an gi-da-ryeoss-eo-yo.",
                english: "I waited for 3 seconds.",
                lao: "ຂ້ອຍລໍຖ້າ 3 ວິນາທີ.",
            },
        ],
    },
    {
        id: 6,
        korean: "분",
        read: "bun",
        english: "minute",
        lao: "ນາທີ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "10분 동안 쉬었어요.",
                read: "Sip-bun dong-an swi-eoss-eo-yo.",
                english: "I rested for 10 minutes.",
                lao: "ຂ້ອຍພັກ 10 ນາທີ.",
            },
        ],
    },
    {
        id: 7,
        korean: "시간대",
        read: "si-gan-dae",
        english: "time zone",
        lao: "ເຂດເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리나라와 다른 시간대에 있어요.",
                read: "U-ri-na-ra-wa da-reun si-gan-dae-e iss-eo-yo.",
                english: "It's in a different time zone from our country.",
                lao: "ມັນຢູ່ໃນເຂດເວລາທີ່ແຕກຕ່າງຈາກປະເທດຂອງພວກເຮົາ.",
            },
        ],
    },
    {
        id: 8,
        korean: "정각",
        read: "jeong-gak",
        english: "o'clock",
        lao: "ໂມງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 3시 정각에 만나요.",
                read: "U-ri-neun sam-si jeong-gak-e man-na-yo.",
                english: "We meet at 3 o'clock.",
                lao: "ພວກເຮົາພົບກັນຕອນ 3 ໂມງ.",
            },
        ],
    },
    {
        id: 9,
        korean: "반",
        read: "ban",
        english: "half past",
        lao: "ຄືງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 5시 반에 출발했어요.",
                read: "U-ri-neun daseot-si ban-e chul-bal-haess-eo-yo.",
                english: "We left at half past five.",
                lao: "ພວກເຮົາອອກເດີນທາງເວລາ 5 ໂມງຄືງ.",
            },
        ],
    },
    {
        id: 10,
        korean: "일정",
        read: "il-jeong",
        english: "schedule",
        lao: "ຕາຕະລາງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "오늘 일정이 빡빡해요.",
                read: "O-neul il-jeong-i ppak-ppak-hae-yo.",
                english: "Today's schedule is tight.",
                lao: "ຕາຕະລາງມື້ນີ້ຕຶບຕັນ.",
            },
        ],
    },
    {
        id: 11,
        korean: "알람",
        read: "al-ram",
        english: "alarm",
        lao: "ແອລາມ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "알람을 맞춰 놓았어요.",
                read: "Al-ram-eul maj-chweo no-ass-eo-yo.",
                english: "I set the alarm.",
                lao: "ຂ້ອຍໄດ້ຕັ້ງແອລາມໄວ້.",
            },
        ],
    },
    {
        id: 12,
        korean: "타이머",
        read: "ta-i-meo",
        english: "timer",
        lao: "ເຄື່ອງຕັ້ງເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "타이머를 사용해서 요리했어요.",
                read: "Ta-i-meo-reul sa-yong-hae-seo yo-ri-haess-eo-yo.",
                english: "I used a timer to cook.",
                lao: "ຂ້ອຍໃຊ້ເຄື່ອງຕັ້ງເວລາໃນການປຸງອາຫານ.",
            },
        ],
    },
    {
        id: 13,
        korean: "예약",
        read: "ye-yak",
        english: "reservation",
        lao: "ການຈອງ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "예약을 미리 해 두었어요.",
                read: "Ye-yak-eul mi-ri hae du-eoss-eo-yo.",
                english: "I made a reservation in advance.",
                lao: "ຂ້ອຍໄດ້ຈອງໄວ້ລ່ວງໜ້າ.",
            },
        ],
    },
    {
        id: 14,
        korean: "정시",
        read: "jeong-si",
        english: "on time",
        lao: "ຕາມເວລາ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "정시에 도착했어요.",
                read: "Jeong-si-e do-chak-haess-eo-yo.",
                english: "I arrived on time.",
                lao: "ຂ້ອຍມາຮອດຕາມເວລາ.",
            },
        ],
    },
    {
        id: 15,
        korean: "연체",
        read: "yeon-che",
        english: "late",
        lao: "ຊ້າ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "회의에 연체되었어요.",
                read: "Hwi-ui-e yeon-che-dweo-sseo-yo.",
                english: "I was late for the meeting.",
                lao: "ຂ້ອຍມາຊ້າສຳລັບການປະຊຸມ.",
            },
        ],
    },
    {
        id: 16,
        korean: "여덟시",
        read: "yeo-deol-si",
        english: "08:00 AM",
        lao: "08:00 AM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 08:00 AM에 아침을 먹었어요.",
                read: "Uri-neun yeo-deol-si-e achim-eul meogeosseoyo.",
                english: "We had breakfast at 08:00 AM.",
                lao: "ພວກເຮົາກິນເຂົ້າເຊົ້າເວລາ 08:00 AM.",
            },
        ],
    },
    {
        id: 17,
        korean: "아홉시 십오분",
        read: "a-hop-si sip-o-bun",
        english: "09:15 AM",
        lao: "09:15 AM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 09:15 AM에 회의를 시작했어요.",
                read: "Uri-neun a-hop-si sip-o-bun-e hwi-ui-reul sijakhaesseoyo.",
                english: "We started the meeting at 09:15 AM.",
                lao: "ພວກເຮົາເລີ່ມການປະຊຸມເວລາ 09:15 AM.",
            },
        ],
    },
    {
        id: 18,
        korean: "열두시",
        read: "yeol-du-si",
        english: "12:00 PM",
        lao: "12:00 PM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 12:00 PM에 점심을 먹었어요.",
                read: "Uri-neun yeol-du-si-e jeomsim-eul meogeosseoyo.",
                english: "We had lunch at 12:00 PM.",
                lao: "ພວກເຮົາກິນເຂົ້າທ່ຽງເວລາ 12:00 PM.",
            },
        ],
    },
    {
        id: 19,
        korean: "다섯시 삼십분",
        read: "daseot-si sam-sip-bun",
        english: "05:30 PM",
        lao: "05:30 PM",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "우리는 05:30 PM에 저녁을 먹었어요.",
                read: "Uri-neun daseot-si sam-sip-bun-e jeonyeog-eul meogeosseoyo.",
                english: "We had dinner at 05:30 PM.",
                lao: "ພວກເຮົາກິນເຂົ້າແລງເວລາ 05:30 PM.",
            },
        ],
    },
];
