import type { WordModel } from "~/models";

export const ANIMALS: WordModel[] = [
    {
        id: 1,
        korean: "닭",
        read: "dalg",
        english: "chicken",
        lao: "ໄກ່",
        speech: "n",
        emoji: "🐓",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 2,
        korean: "개",
        read: "gae",
        english: "dog",
        lao: "ໝາ",
        speech: "n",
        emoji: "🐕",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 3,
        korean: "고양이",
        read: "go-yan-gi",
        english: "cat",
        lao: "ແມວ",
        speech: "n",
        emoji: "🐈",
        examples: [
            {
                id: 1,
                korean: "검고 하얀 고양이",
                read: "geomggo hayan goyangi",
                english: "black and white cat",
                lao: "ແມວສີດໍາແລະສີຂາວ",
            },
        ],
    },
    {
        id: 4,
        korean: "오리",
        read: "o-li",
        english: "duck",
        lao: "ເປັດ",
        speech: "n",
        emoji: "🪿",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 5,
        korean: "돼지",
        read: "dwae-ji",
        english: "pig",
        lao: "ຫມູ",
        speech: "n",
        emoji: "🐖",
        examples: [
            {
                id: 1,
                korean: "돼지들은 영리한 동물입니다.",
                read: "Dwaejideureun yeongnihan dongmurimnida.",
                english: "Pigs are intelligent animals.",
                lao: "ຫມູເປັນສັດທີ່ສະຫຼາດ.",
            },
        ],
    },
    {
        id: 6,
        korean: "염소",
        read: "yeom-so",
        english: "pig",
        lao: "ແບ້",
        speech: "n",
        emoji: "🐐",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 7,
        korean: "말",
        read: "mal",
        english: "horse",
        lao: "ມ້າ",
        speech: "n",
        emoji: "🐎",
        examples: [
            {
                id: 1,
                korean: "여자가 말 위에 있습니다.",
                read: "Yeojaga mal wie itsseumnida.",
                english: "The woman is on the horse.",
                lao: "ຜູ້ຍິງຢູ່ເທິງມ້າ.",
            },
        ],
    },
    {
        id: 8,
        korean: "암소",
        read: "am-so",
        english: "cow",
        lao: "ງົວ",
        speech: "n",
        emoji: "🐂",
        examples: [
            {
                id: 1,
                korean: "소들이 들판에서 풀을 뜯고 있습니다.",
                read: "Sodeuri deulpaneseo pureul tteutkko itsseumnida.",
                english: "The cows are grazing in the field.",
                lao: "ງົວ​ຢູ່​ທົ່ງ​ຫຍ້າ.",
            },
        ],
    },
    {
        id: 9,
        korean: "물소",
        read: " mul-so",
        english: "buffalo",
        lao: "ຄວາຍ",
        speech: "n",
        emoji: "🐃",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 10,
        korean: "칠면조",
        read: "chil-myeon-jo",
        english: "turkey",
        lao: "ໄກ່ງວງ",
        speech: "n",
        emoji: "🦃",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 11,
        korean: "새",
        read: "sae",
        english: "bird",
        lao: "ນົກ",
        speech: "n",
        emoji: "🐦‍⬛",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 12,
        korean: "원숭이",
        read: "won-sung-i",
        english: "monkey",
        lao: "ລິງ",
        speech: "n",
        emoji: "🐒",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 13,
        korean: "호랑이",
        read: "ho-lang-i",
        english: "tiger",
        lao: "ເສືອ",
        speech: "n",
        emoji: "🐅",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 14,
        korean: "코끼리",
        read: "kok-ki-li",
        english: "elephant",
        lao: "ຊ້າງ",
        speech: "n",
        emoji: "🐘",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 15,
        korean: "기린",
        read: "gilin",
        english: "giraffe",
        lao: "ຈີຣາຟ",
        speech: "n",
        emoji: "🦒",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 16,
        korean: "캥거루",
        read: "kaeng-geolu",
        english: "kangaroo",
        lao: "ຈິງໂຈ້",
        speech: "n",
        emoji: "🦘",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 17,
        korean: "양",
        read: "yang",
        english: "sheep",
        lao: "ແກະ",
        speech: "n",
        emoji: "🐑",
        examples: [
            {
                id: 1,
                korean: "양이 풀을 먹고 있습니다.",
                read: "Yangi pureul meokko itsseumnida.",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 18,
        korean: "생쥐",
        read: "saeng-jwi",
        english: "mouse",
        lao: "ແກະ",
        speech: "n",
        emoji: "🐁",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 19,
        korean: "올빼미",
        read: "olp-pae-mi",
        english: "owl",
        lao: "ນົກເຄົ້າ",
        speech: "n",
        emoji: "🦉",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 20,
        korean: "토끼",
        read: "tok-ki",
        english: "rabbit",
        lao: "ກະຕ່າຍ",
        speech: "n",
        emoji: "🐇",
        examples: [
            {
                id: 1,
                korean: "하얀 토끼가 풀밭에 있습니다.",
                read: "hayan tokkiga pulbate itsseumnida.",
                english: "white rabbit in the green grass",
                lao: "ກະຕ່າຍສີຂາວຢູ່ໃນຫຍ້າສີຂຽວ",
            },
        ],
    },
    {
        id: 21,
        korean: "사자",
        read: "sa-ja",
        english: "lion",
        lao: "ສິງ",
        speech: "n",
        emoji: "🦁",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 22,
        korean: "사슴",
        read: "sa-seum",
        english: "deer",
        lao: "ກວາງ",
        speech: "n",
        emoji: "🦌",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 23,
        korean: "악어",
        read: "ag-eo",
        english: "crocodile",
        lao: "ແຂ້",
        speech: "n",
        emoji: "🐊",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 24,
        korean: "거북이",
        read: "geobug-i",
        english: "crocodile",
        lao: "ເຕົ່າ",
        speech: "n",
        emoji: "🐢",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 25,
        korean: "뱀",
        read: "baem",
        english: "snake",
        lao: "ງູ",
        speech: "n",
        emoji: "🐍",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
];
