import type { WordModel } from "~/models";

export const CLOTHING: WordModel[] = [
    {
        id: 1,
        korean: "옷",
        read: "ot",
        english: "clothes",
        lao: "ເຄື່ອງນຸ່ງ",
        speech: "n",
        emoji: "👘",
        examples: [
            {
                id: 1,
                korean: "바닥에 있는 옷은 더럽습니다.",
                read: "Badage inneun oseun deoreopsseumnida.",
                english: "The clothes on the floor are dirty.",
                lao: "ເຄື່ອງນຸ່ງຢູ່ເທິງພື້ນແມ່ນເປື້ອນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "재킷",
        read: "jaekit",
        english: "jacket",
        lao: "ເສື້ອກັນໜາວ",
        speech: "n",
        emoji: "🧥",
        examples: [
            {
                id: 1,
                korean: "무거운 재킷",
                read: "mugeoun jaekit",
                english: "heavy jacket",
                lao: "ເສື້ອກັນໜາວຫນັກ",
            },
        ],
    },
    {
        id: 3,
        korean: "셔츠",
        read: "syeocheu",
        english: "shirt",
        lao: "ເສື້ອ",
        speech: "n",
        emoji: "👔",
        examples: [
            {
                id: 1,
                korean: "남자는 셔츠를 다림질하고 있습니다.",
                read: "Namjaneun syeocheureul darimjilhago itsseumnida.",
                english: "The man is ironing the shirt.",
                lao: "ຜູ້ຊາຍກໍາລັງລີດເສື້ອ.",
            },
        ],
    },
    {
        id: 4,
        korean: "바지",
        read: "baji",
        english: "pants",
        lao: "ໂສ້ງ",
        speech: "n",
        emoji: "👖",
        examples: [
            {
                id: 1,
                korean: "저는 바지를 벗었습니다.",
                read: "Jeoneun bajireul beoseotsseumnida.",
                english: "I took off my pants.",
                lao: "ຂ້ອຍຖອດໂສ້ງຂອງຂ້ອຍອອກ.",
            },
        ],
    },
    {
        id: 5,
        korean: "드레스",
        read: "deureseu",
        english: "dress",
        lao: "ກະໂປ່ງ",
        speech: "n",
        emoji: "👗",
        examples: [
            {
                id: 1,
                korean: "오늘은 빨간 드레스를 입고 내일은 파란 드레스를 입을 것입니다.",
                read: "Oneureun ppalgan deureseureul ipkko naeireun paran deuresseureul ibeul ggeosimnida.",
                english:
                    "I'll wear the red dress today, and the blue one tomorrow.",
                lao: "ຂ້ອຍຈະໃສ່ຊຸດສີແດງໃນມື້ນີ້ ແລະ ສີຟ້າໃນມື້ອື່ນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "청바지",
        read: "cheongbaji",
        english: "jeans",
        lao: "ໂສ້ງຢີນ",
        speech: "n",
        emoji: "👖",
        examples: [
            {
                id: 1,
                korean: "물이 빠진 청바지",
                read: "muri ppajin cheongbaji",
                english: "faded jeans",
                lao: "ໂສ້ງຢີນຈືດໆ",
            },
        ],
    },
    {
        id: 7,
        korean: "티셔츠",
        read: "tisyeocheu",
        english: "T-shirt",
        lao: "ເສື້ອຍືດ",
        speech: "n",
        emoji: "👕",
        examples: [
            {
                id: 1,
                korean: "파란 티셔츠",
                read: "paran tisyeocheu",
                english: "blue T-shirt",
                lao: "ເສື້ອຍືດສີຟ້າ",
            },
        ],
    },
    {
        id: 8,
        korean: "짧은",
        read: "danlag",
        english: "short",
        lao: "ໂສ້ງຂາສັ້ນ",
        speech: "n",
        emoji: "🩳",
        examples: [
            {
                id: 1,
                korean: "그는 빨간색 반바지를 입는다.",
                read: "Geuneun ppalgansaeg banbajileul ibneunda.",
                english: "The cows are grazing in the field.",
                lao: "ລາວນຸ່ງໂສ້ງຂາສັ້ນສີແດງ.",
            },
        ],
    },
    {
        id: 9,
        korean: "구두",
        read: "gudu",
        english: "shoe",
        lao: "ເກີບ",
        speech: "n",
        emoji: "👟",
        examples: [
            {
                id: 1,
                korean: "나는 새 신발을 산다.",
                read: "Naneun sae sinbal-eul sanda.",
                english: "I buy a new shoe.",
                lao: "ຂ້ອຍຊື້ເກີບໃຫມ່.",
            },
        ],
    },
    {
        id: 10,
        korean: "양말",
        read: "yang-mal",
        english: "socks",
        lao: "ຖົງຕີນ",
        speech: "n",
        emoji: "🧦",
        examples: [
            {
                id: 1,
                korean: "나는 새 신발을 산다.",
                read: "Na-neun sae sin-bal-eul san-da.",
                english: "I buy a new shoe.",
                lao: "ຂ້ອຍຊື້ເກີບໃຫມ່.",
            },
        ],
    },
    {
        id: 11,
        korean: "장갑",
        read: "jang-gab",
        english: "gloves",
        lao: "ຖົງມື",
        speech: "n",
        emoji: "🧤",
        examples: [
            {
                id: 1,
                korean: "괜찮아요, 이 장갑을 끼세요.",
                read: "Gwaen-chanh-ayo, i jang-gab-eul kkiseyo.",
                english: "It's cool, please wear this gloves.",
                lao: "ມັນເຢັນ, ກະລຸນາໃສ່ຖົງມືນີ້.",
            },
        ],
    },
    {
        id: 12,
        korean: "슬리퍼",
        read: "seullipeo",
        english: "slippers",
        lao: "ເກີບແຕະ",
        speech: "n",
        emoji: "🩴",
        examples: [
            {
                id: 1,
                korean: "괜찮아요, 이 장갑을 끼세요.",
                read: "Gwaenchanh-ayo, i jang-gab-eul kkiseyo.",
                english: "It's cool, please wear this gloves.",
                lao: "ມັນເຢັນ, ກະລຸນາໃສ່ຖົງມືນີ້.",
            },
        ],
    },
    {
        id: 13,
        korean: "하이힐",
        read: "haihil",
        english: "high-heels",
        lao: "ເກີບສົ້ນ​ສູງ",
        speech: "n",
        emoji: "👠",
        examples: [
            {
                id: 1,
                korean: "괜찮아요, 이 장갑을 끼세요.",
                read: "gwaenchanh-ayo, i jang-gab-eul kkiseyo.",
                english: "It's cool, please wear this gloves.",
                lao: "ມັນເຢັນ, ກະລຸນາໃສ່ຖົງມືນີ້.",
            },
        ],
    },
    {
        id: 14,
        korean: "모자",
        read: "moja",
        english: "hat",
        lao: "ໝວກ",
        speech: "n",
        emoji: "🎩",
        examples: [
            {
                id: 1,
                korean: "괜찮아요, 이 장갑을 끼세요.",
                read: "gwaenchanh-ayo, i jang-gab-eul kkiseyo.",
                english: "It's cool, please wear this gloves.",
                lao: "ມັນເຢັນ, ກະລຸນາໃສ່ຖົງມືນີ້.",
            },
        ],
    },
    {
        id: 14,
        korean: "캡",
        read: "kaeb",
        english: "cap",
        lao: "ໝວກ",
        speech: "n",
        emoji: "🧢",
        examples: [
            {
                id: 1,
                korean: "나는 새 모자를 쓴다.",
                read: "Naneun sae mojaleul sseunda.",
                english: "I wear my new cap.",
                lao: "ຂ້ອຍໃສ່ໝວກໃໝ່ຂອງຂ້ອຍ.",
            },
        ],
    },
    {
        id: 14,
        korean: "우산",
        read: "usan",
        english: "umbrella",
        lao: "ຄັນຮົ່ມ",
        speech: "n",
        emoji: "🌂",
        examples: [
            {
                id: 1,
                korean: "비가 온다, 우산을 가지고 가세요.",
                read: "Biga onda, usan-eul gajigo gaseyo.",
                english: "It's raining, take a umbrella with you.",
                lao: "ຝົນຕົກເອົາຄັນຮົ່ມໄປນຳເຈົ້າ.",
            },
        ],
    },
    {
        id: 15,
        korean: "가방",
        read: "gabang",
        english: "bag",
        lao: "ກະເປົ໋າ",
        speech: "n",
        emoji: "🎒",
        examples: [
            {
                id: 1,
                korean: "비가 온다, 우산을 가지고 가세요.",
                read: "Biga onda, usan-eul gajigo gaseyo.",
                english: "It's raining, take a umbrella with you.",
                lao: "ຝົນຕົກເອົາຄັນຮົ່ມໄປນຳເຈົ້າ.",
            },
        ],
    },
    {
        id: 16,
        korean: "스카프",
        read: "seukapeu",
        english: "scarf",
        lao: "ຜ້າພັນຄໍ",
        speech: "n",
        emoji: "🧣",
        examples: [
            {
                id: 1,
                korean: "비가 온다, 우산을 가지고 가세요.",
                read: "Biga onda, usan-eul gajigo gaseyo.",
                english: "It's raining, take a umbrella with you.",
                lao: "ຝົນຕົກເອົາຄັນຮົ່ມໄປນຳເຈົ້າ.",
            },
        ],
    },
    {
        id: 17,
        korean: "색안경",
        read: "saeg-angyeong",
        english: "sunglasses",
        lao: "ແວ່ນຕາກັນແດດ",
        speech: "n",
        emoji: "🕶",
        examples: [
            {
                id: 1,
                korean: "비가 온다, 우산을 가지고 가세요.",
                read: "Biga onda, usan-eul gajigo gaseyo.",
                english: "It's raining, take a umbrella with you.",
                lao: "ຝົນຕົກເອົາຄັນຮົ່ມໄປນຳເຈົ້າ.",
            },
        ],
    },
    {
        id: 18,
        korean: "비키니",
        read: "bikini",
        english: "bikini",
        lao: "ເສື້ອອາບນໍ້າ",
        speech: "n",
        emoji: "👙",
        examples: [
            {
                id: 1,
                korean: "비키니 상의.",
                read: "bikini tab",
                english: "A bikini top",
                lao: "ລາວມີກະທູ້ວ່າງໃສ່ເສື້ອຂອງລາວ.",
            },
        ],
    },
    {
        id: 19,
        korean: "실",
        read: "sil",
        english: "thread",
        lao: "ເສັ້ນດ້າຍ",
        speech: "n",
        emoji: "🧵",
        examples: [
            {
                id: 1,
                korean: "그 사람 셔츠에 실이 헐거워졌어.",
                read: "Geu salam syeocheue sil-i heolgeowojyeoss-eo.",
                english: "He had a loose thread on his shirt.",
                lao: "ລາວມີກະທູ້ວ່າງໃສ່ເສື້ອຂອງລາວ.",
            },
        ],
    },
    {
        id: 20,
        korean: "재봉 바늘",
        read: "jaebong baneul",
        english: "sewing needle",
        lao: "ເຂັມຫຍິບ",
        speech: "n",
        emoji: "🪡",
        examples: [
            {
                id: 1,
                korean: "그 사람 셔츠에 실이 헐거워졌어.",
                read: "Geu salam syeocheue sil-i heolgeowojyeoss-eo.",
                english: "He had a loose thread on his shirt.",
                lao: "ລາວມີກະທູ້ວ່າງໃສ່ເສື້ອຂອງລາວ.",
            },
        ],
    },
];
