import type { WordModel } from "~/models";

export const CLOTHING: WordModel[] = [
    {
        id: 1,
        korean: "옷",
        read: "ot",
        english: "clothes",
        lao: "ເຄື່ອງນຸ່ງ",
        speech: "n",
        emoji: "🐓",
        examples: [
            {
                id: 1,
                korean: "바닥에 있는 옷은 더럽습니다.",
                read: "Badage inneun oseun deoreopsseumnida.",
                english: "The clothes on the floor are dirty.",
                lao: "ເຄື່ອງນຸ່ງຢູ່ເທິງພື້ນແມ່ນເປື້ອນ.",
            },
        ],
    },
    {
        id: 2,
        korean: "재킷",
        read: "jaekit",
        english: "jacket",
        lao: "ເສື້ອກັນໜາວ",
        speech: "n",
        emoji: "🧥",
        examples: [
            {
                id: 1,
                korean: "무거운 재킷",
                read: "mugeoun jaekit",
                english: "heavy jacket",
                lao: "ເສື້ອກັນໜາວຫນັກ",
            },
        ],
    },
    {
        id: 3,
        korean: "셔츠",
        read: "syeocheu",
        english: "shirt",
        lao: "ເສື້ອ",
        speech: "n",
        emoji: "🐈",
        examples: [
            {
                id: 1,
                korean: "남자는 셔츠를 다림질하고 있습니다.",
                read: "Namjaneun syeocheureul darimjilhago itsseumnida.",
                english: "The man is ironing the shirt.",
                lao: "ຜູ້ຊາຍກໍາລັງລີດເສື້ອ.",
            },
        ],
    },
    {
        id: 4,
        korean: "바지",
        read: "baji",
        english: "pants",
        lao: "ໂສ້ງ",
        speech: "n",
        emoji: "👖",
        examples: [
            {
                id: 1,
                korean: "저는 바지를 벗었습니다.",
                read: "Jeoneun bajireul beoseotsseumnida.",
                english: "I took off my pants.",
                lao: "ຂ້ອຍຖອດໂສ້ງຂອງຂ້ອຍອອກ.",
            },
        ],
    },
    {
        id: 5,
        korean: "드레스",
        read: "deureseu",
        english: "dress",
        lao: "ກະໂປ່ງ",
        speech: "n",
        emoji: "👗",
        examples: [
            {
                id: 1,
                korean: "오늘은 빨간 드레스를 입고 내일은 파란 드레스를 입을 것입니다.",
                read: "Oneureun ppalgan deureseureul ipkko naeireun paran deuresseureul ibeul ggeosimnida.",
                english: "I'll wear the red dress today, and the blue one tomorrow.",
                lao: "ຂ້ອຍຈະໃສ່ຊຸດສີແດງໃນມື້ນີ້ ແລະ ສີຟ້າໃນມື້ອື່ນ.",
            },
        ],
    },
    {
        id: 6,
        korean: "청바지",
        read: "cheongbaji",
        english: "jeans",
        lao: "ໂສ້ງຢີນ",
        speech: "n",
        emoji: "👖",
        examples: [
            {
                id: 1,
                korean: "물이 빠진 청바지",
                read: "muri ppajin cheongbaji",
                english: "faded jeans",
                lao: "ໂສ້ງຢີນຈືດໆ",
            },
        ],
    },
    {
        id: 7,
        korean: "티셔츠",
        read: "tisyeocheu",
        english: "T-shirt",
        lao: "ເສື້ອຍືດ",
        speech: "n",
        emoji: "👕",
        examples: [
            {
                id: 1,
                korean: "파란 티셔츠",
                read: "paran tisyeocheu",
                english: "blue T-shirt",
                lao: "ເສື້ອຍືດສີຟ້າ",
            },
        ],
    },
    {
        id: 8,
        korean: "짧은",
        read: "danlag",
        english: "short",
        lao: "ໂສ້ງຂາສັ້ນ",
        speech: "n",
        emoji: "🩳",
        examples: [
            {
                id: 1,
                korean: "그는 빨간색 반바지를 입는다.",
                read: "Geuneun ppalgansaeg banbajileul ibneunda.",
                english: "The cows are grazing in the field.",
                lao: "ລາວນຸ່ງໂສ້ງຂາສັ້ນສີແດງ.",
            },
        ],
    },
    {
        id: 9,
        korean: "물소",
        read: " mulso",
        english: "buffalo",
        lao: "ຄວາຍ",
        speech: "n",
        emoji: "🐃",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 10,
        korean: "칠면조",
        read: "chilmyeonjo",
        english: "turkey",
        lao: "ໄກ່ງວງ",
        speech: "n",
        emoji: "🦃",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 11,
        korean: "새",
        read: "sae",
        english: "bird",
        lao: "ນົກ",
        speech: "n",
        emoji: "🐦‍⬛",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 12,
        korean: "원숭이",
        read: "wonsung-i",
        english: "monkey",
        lao: "ລິງ",
        speech: "n",
        emoji: "🐒",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 13,
        korean: "호랑이",
        read: "holang-i",
        english: "tiger",
        lao: "ເສືອ",
        speech: "n",
        emoji: "🐅",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 14,
        korean: "코끼리",
        read: "kokkili",
        english: "elephant",
        lao: "ຊ້າງ",
        speech: "n",
        emoji: "🐘",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 15,
        korean: "기린",
        read: "gilin",
        english: "giraffe",
        lao: "ຈີຣາຟ",
        speech: "n",
        emoji: "🦒",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 16,
        korean: "캥거루",
        read: "kaeng-geolu",
        english: "kangaroo",
        lao: "ຈິງໂຈ້",
        speech: "n",
        emoji: "🦘",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 17,
        korean: "양",
        read: "yang",
        english: "sheep",
        lao: "ແກະ",
        speech: "n",
        emoji: "🐑",
        examples: [
            {
                id: 1,
                korean: "양이 풀을 먹고 있습니다.",
                read: "Yangi pureul meokko itsseumnida.",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 18,
        korean: "생쥐",
        read: "saengjwi",
        english: "mouse",
        lao: "ແກະ",
        speech: "n",
        emoji: "🐁",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 19,
        korean: "올빼미",
        read: "olppaemi",
        english: "owl",
        lao: "ນົກເຄົ້າ",
        speech: "n",
        emoji: "🦉",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 20,
        korean: "토끼",
        read: "tokki",
        english: "rabbit",
        lao: "ກະຕ່າຍ",
        speech: "n",
        emoji: "🐇",
        examples: [
            {
                id: 1,
                korean: "하얀 토끼가 풀밭에 있습니다.",
                read: "hayan tokkiga pulbate itsseumnida.",
                english: "white rabbit in the green grass",
                lao: "ກະຕ່າຍສີຂາວຢູ່ໃນຫຍ້າສີຂຽວ",
            },
        ],
    },
    {
        id: 21,
        korean: "사자",
        read: "saja",
        english: "lion",
        lao: "ສິງ",
        speech: "n",
        emoji: "🦁",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 22,
        korean: "사슴",
        read: "saseum",
        english: "deer",
        lao: "ກວາງ",
        speech: "n",
        emoji: "🦌",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 23,
        korean: "악어",
        read: "ag-eo",
        english: "crocodile",
        lao: "ແຂ້",
        speech: "n",
        emoji: "🐊",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 24,
        korean: "거북이",
        read: "geobug-i",
        english: "crocodile",
        lao: "ເຕົ່າ",
        speech: "n",
        emoji: "🐢",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
    {
        id: 25,
        korean: "뱀",
        read: "baem",
        english: "snake",
        lao: "ງູ",
        speech: "n",
        emoji: "🐍",
        examples: [
            {
                id: 1,
                korean: "나는 닭고기와 밥을 먹어요",
                read: "naneun dalg-gogiwa bab-eul meog-eoyo",
                english: "I eat chicken and rice",
                lao: "ຂ້ອຍກິນໄກ່ແລະເຂົ້າ",
            },
        ],
    },
];
