import type { WordModel } from "~/models";

export const DATES: WordModel[] = [
    {
        id: 1,
        korean: "첫 번째",
        read: "Cheot beon-jjae",
        english: "First",
        lao: "ວັນທີ 1",
    },
    {
        id: 2,
        korean: "두 번째",
        read: "Du beon-jjae",
        english: "Second",
        lao: "ວັນທີ 2",
    },
    {
        id: 3,
        korean: "세 번째",
        read: "Se beon-jjae",
        english: "Third",
        lao: "ວັນທີ 3",
    },
    {
        id: 4,
        korean: "네 번째",
        read: "Ne beon-jjae",
        english: "Fourth",
        lao: "ວັນທີ 4",
    },
    {
        id: 5,
        korean: "다섯 번째",
        read: "Daseot beon-jjae",
        english: "Fifth",
        lao: "ວັນທີ 5",
    },
    {
        id: 6,
        korean: "여섯 번째",
        read: "Yeoseot beon-jjae",
        english: "Sixth",
        lao: "ວັນທີ 6",
    },
    {
        id: 7,
        korean: "일곱 번째",
        read: "Ilgop beon-jjae",
        english: "Seventh",
        lao: "ວັນທີ 7",
    },
    {
        id: 8,
        korean: "여덟 번째",
        read: "Yeodeol beon-jjae",
        english: "Eighth",
        lao: "ວັນທີ 8",
    },
    {
        id: 9,
        korean: "아홉 번째",
        read: "Ahop beon-jjae",
        english: "Ninth",
        lao: "ວັນທີ 9",
    },
    {
        id: 10,
        korean: "열 번째",
        read: "Yeol beon-jjae",
        english: "Tenth",
        lao: "ວັນທີ 10",
    },
    {
        id: 11,
        korean: "열한 번째",
        read: "Yeolhan beon-jjae",
        english: "Eleventh",
        lao: "ວັນທີ 11",
    },
    {
        id: 12,
        korean: "열두 번째",
        read: "Yeoldu beon-jjae",
        english: "Twelfth",
        lao: "ວັນທີ 12",
    },
    {
        id: 13,
        korean: "열세 번째",
        read: "Yeolse beon-jjae",
        english: "Thirteenth",
        lao: "ວັນທີ 13",
    },
    {
        id: 14,
        korean: "열네 번째",
        read: "Yeolne beon-jjae",
        english: "Fourteenth",
        lao: "ວັນທີ 14",
    },
    {
        id: 15,
        korean: "열다섯 번째",
        read: "Yeoldaseot beon-jjae",
        english: "Fifteenth",
        lao: "ວັນທີ 15",
    },
    {
        id: 16,
        korean: "열여섯 번째",
        read: "Yeolyeoseot beon-jjae",
        english: "Sixteenth",
        lao: "ວັນທີ 16",
    },
    {
        id: 17,
        korean: "열일곱 번째",
        read: "Yeolilgop beon-jjae",
        english: "Seventeenth",
        lao: "ວັນທີ 17",
    },
    {
        id: 18,
        korean: "열여덟 번째",
        read: "Yeolyeodeol beon-jjae",
        english: "Eighteenth",
        lao: "ວັນທີ 18",
    },
    {
        id: 19,
        korean: "열아홉 번째",
        read: "Yeolahop beon-jjae",
        english: "Nineteenth",
        lao: "ວັນທີ 19",
    },
    {
        id: 20,
        korean: "스무 번째",
        read: "Seumu beon-jjae",
        english: "Twentieth",
        lao: "ວັນທີ 20",
    },
    {
        id: 21,
        korean: "스물한 번째",
        read: "Seumulhan beon-jjae",
        english: "Twenty-first",
        lao: "ວັນທີ 21",
    },
    {
        id: 22,
        korean: "스물두 번째",
        read: "Seumuldu beon-jjae",
        english: "Twenty-second",
        lao: "ວັນທີ 22",
    },
    {
        id: 23,
        korean: "스물세 번째",
        read: "Seumulse beon-jjae",
        english: "Twenty-third",
        lao: "ວັນທີ 23",
    },
    {
        id: 24,
        korean: "스물네 번째",
        read: "Seumulne beon-jjae",
        english: "Twenty-fourth",
        lao: "ວັນທີ 24",
    },
    {
        id: 25,
        korean: "스물다섯 번째",
        read: "Seumuldaseot beon-jjae",
        english: "Twenty-fifth",
        lao: "ວັນທີ 25",
    },
    {
        id: 26,
        korean: "스물여섯 번째",
        read: "Seumulyeoseot beon-jjae",
        english: "Twenty-sixth",
        lao: "ວັນທີ 26",
    },
    {
        id: 27,
        korean: "스물일곱 번째",
        read: "Seumulilgop beon-jjae",
        english: "Twenty-seventh",
        lao: "ວັນທີ 27",
    },
    {
        id: 28,
        korean: "스물여덟 번째",
        read: "Seumulyeodeol beon-jjae",
        english: "Twenty-eighth",
        lao: "ວັນທີ 28",
    },
    {
        id: 29,
        korean: "스물아홉 번째",
        read: "Seumulahop beon-jjae",
        english: "Twenty-ninth",
        lao: "ວັນທີ 29",
    },
    {
        id: 30,
        korean: "서른 번째",
        read: "Seoreun beon-jjae",
        english: "Thirtieth",
        lao: "ວັນທີ 30",
    },
    {
        id: 31,
        korean: "서른한 번째",
        read: "Seoreunhan beon-jjae",
        english: "Thirty-first",
        lao: "ວັນທີ 31",
    },
];
