import type { WordModel } from "~/models";

export const KITCHEN: WordModel[] = [
    {
        id: 1,
        korean: "접시",
        read: "jeop-si",
        english: "plate",
        lao: "ຈານ",
        speech: "n",
        emoji: "🍽",
        examples: [
            {
                id: 1,
                korean: "접시 위에 있는 포크",
                read: "jeopssi wie inneun pokeu",
                english: "fork on a plate",
                lao: "ສ້ອມຢູ່ໃນຈານ",
            },
        ],
    },
    {
        id: 2,
        korean: "그릇",
        read: "geu-reut",
        english: "bowl",
        lao: "ຖ້ວຍ",
        speech: "n",
        emoji: "🍚",
        examples: [
            {
                id: 1,
                korean: "파란 그릇",
                read: "paran geureut",
                english: "blue bowl",
                lao: "ຖ້ວຍສີຟ້າ",
            },
        ],
    },
    {
        id: 3,
        korean: "냄비",
        read: "naem-bi",
        english: "pot",
        lao: "ຫມໍ້",
        speech: "n",
        emoji: "🥘",
        examples: [
            {
                id: 1,
                korean: "냄비에 밥을 합니다",
                read: "naembie babeul hamnida",
                english: "cook rice in a pot",
                lao: "ແຕ່ງກິນໃນຫມໍ້",
            },
        ],
    },
    {
        id: 4,
        korean: "프라이팬",
        read: "peu-ra-i-paen",
        english: "frying pan",
        lao: "ກະທະ",
        speech: "n",
        emoji: "🍳",
        examples: [
            {
                id: 1,
                korean: "양파가 프라이팬에서 볶아지고 있습니다.",
                read: "yangpaga peuraipaeneseo bokkajigo itsseumnida",
                english: "The onions are being sautéed in the frying pan.",
                lao: "ຜັກບົ່ວຖືກຈືນໃນກະທະ.",
            },
        ],
    },
    {
        id: 5,
        korean: "나이프",
        read: "nai-peu",
        english: "knife",
        lao: "ມີດ",
        speech: "n",
        emoji: "🔪",
        examples: [
            {
                id: 1,
                korean: "나이프 좀 건네 주시겠어요?",
                read: "naipeu jom geonne jusigesseoyo",
                english: "Could you pass me the knife?",
                lao: "ເຈົ້າສາມາດເອົາມີດໃຫ້ຂ້ອຍໄດ້ບໍ?",
            },
        ],
    },
    {
        id: 6,
        korean: "숟가락",
        read: "sut-ggarak",
        english: "spoon",
        lao: "ບ່ວງ",
        speech: "n",
        emoji: "🥄",
        examples: [
            {
                id: 1,
                korean: "물약, 숟가락 그리고 작은 플라스틱 컵",
                read: "muryak, sutggarak geurigo jageun peullaseutik keop",
                english: "liquid medicine, a spoon and a small plastic cup",
                lao: "ຢານ້ຳ, ບ່ວງ ແລະ ຈອກພລາສຕິກນ້ອຍ",
            },
        ],
    },
    {
        id: 7,
        korean: "포크",
        read: "po-keu",
        english: "fork",
        lao: "ສ້ອມ",
        speech: "n",
        emoji: "🍴",
        examples: [
            {
                id: 1,
                korean: "접시 위에 있는 포크",
                read: "jeopssi wie inneun pokeu",
                english: "fork on a plate",
                lao: "ສ້ອມຢູ່ໃນຈານ",
            },
        ],
    },
    {
        id: 8,
        korean: "젓가락",
        read: "jeo-ggarak",
        english: "chopsticks",
        lao: "ໄມ້ທູ່",
        speech: "n",
        emoji: "🥢",
        examples: [
            {
                id: 1,
                korean: "젓가락을 사용하여 음식을 먹습니다.",
                read: "jeoggakakeul sayonghayeo eumsigeul meokseumnida",
                english: "Use chopsticks to eat food.",
                lao: "ໃຊ້ໄມ້ທູ່ເພື່ອກິນອາຫານ.",
            },
        ],
    },
    {
        id: 9,
        korean: "도마",
        read: "do-ma",
        english: "cutting board",
        lao: "ຂຽນ",
        speech: "n",
        emoji: "🔪",
        examples: [
            {
                id: 1,
                korean: "나무 도마",
                read: "namu doma",
                english: "wooden cutting board",
                lao: "ຂຽນໄມ້",
            },
        ],
    },
    {
        id: 10,
        korean: "소금",
        read: "so-geum",
        english: "salt",
        lao: "ເກືອ",
        speech: "n",
        emoji: "🧂",
        examples: [
            {
                id: 1,
                korean: "소금을 요리에 넣습니다.",
                read: "sogeumeul yorie neotseumnida",
                english: "Add salt to the dish.",
                lao: "ເພີ່ມເກືອໃສ່ອາຫານ.",
            },
        ],
    },
    {
        id: 11,
        korean: "설탕",
        read: "seol-tang",
        english: "sugar",
        lao: "ນ້ຳຕານ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "차에 설탕을 넣습니다.",
                read: "Cha-e seoltang-eul neohseumnida.",
                english: "I add sugar to my tea.",
                lao: "ຂ້ອຍເພີ່ມນ້ຳຕານໃສ່ຊາຂອງຂ້ອຍ.",
            },
        ],
    },
    {
        id: 12,
        korean: "냉장고",
        read: "naeng-jang-go",
        english: "refrigerator",
        lao: "ຕູ້ເຢັນ",
        speech: "n",
        emoji: "❄️",
        examples: [
            {
                id: 1,
                korean: "음식을 냉장고에 넣으세요.",
                read: "eumsigeul naengjanggoe neoeuseyo",
                english: "Put the food in the refrigerator.",
                lao: "ເອົາອາຫານໃສ່ຕູ້ເຢັນ.",
            },
        ],
    },
];
