import type { WordModel } from "~/models";

export const KITCHEN: WordModel[] = [
    {
        id: 1,
        korean: "접시",
        read: "jeopsi",
        english: "plate",
        lao: "ຈານ",
        speech: "n",
        emoji: "🍽",
        examples: [
            {
                id: 1,
                korean: "접시 위에 있는 포크",
                read: "jeopssi wie inneun pokeu",
                english: "fork on a plate",
                lao: "ສ້ອມຢູ່ໃນຈານ",
            },
        ],
    },
    {
        id: 2,
        korean: "그릇",
        read: "geureut",
        english: "bowl",
        lao: "ຖ້ວຍ",
        speech: "n",
        emoji: "🍚",
        examples: [
            {
                id: 1,
                korean: "파란 그릇",
                read: "paran geureut",
                english: "blue bowl",
                lao: "ຖ້ວຍສີຟ້າ",
            },
        ],
    },
    {
        id: 3,
        korean: "냄비",
        read: "naembi",
        english: "pot",
        lao: "ຫມໍ້",
        speech: "n",
        emoji: "🥘",
        examples: [
            {
                id: 1,
                korean: "파란 그릇",
                read: "paran geureut",
                english: "blue bowl",
                lao: "ຖ້ວຍສີຟ້າ",
            },
        ],
    },
    {
        id: 4,
        korean: "냄비",
        read: "naembi",
        english: "pot",
        lao: "ຫມໍ້",
        speech: "n",
        emoji: "🥘",
        examples: [
            {
                id: 1,
                korean: "냄비에 밥을 합니다",
                read: "naembie babeul hamnida",
                english: "cook rice in a pot",
                lao: "ແຕ່ງກິນໃນຫມໍ້",
            },
        ],
    },
    {
        id: 4,
        korean: "프라이팬",
        read: "peuraipaen",
        english: "frying pan",
        lao: "ຫມໍ້",
        speech: "n",
        emoji: "🍳",
        examples: [
            {
                id: 1,
                korean: "양파가 프라이팬에서 볶아지고 있습니다.",
                read: "Yangpaga peuraipaeneseo bokkajigo itsseumnida.",
                english: "The onions are being sautéed in the frying pan.",
                lao: "ຜັກບົ່ວຖືກຈືນໃນເຕົາຂົ້ວ.",
            },
        ],
    },
    {
        id: 5,
        korean: "나이프",
        read: "naipeu",
        english: "knife",
        lao: "ມີດ",
        speech: "n",
        emoji: "🍴",
        examples: [
            {
                id: 1,
                korean: "나이프 좀 건네 주시겠어요?",
                read: "Naipeu jom geonne jusigesseoyo?",
                english: "Could you pass me the knife?",
                lao: "ເຈົ້າສາມາດເອົາມີດໃຫ້ຂ້ອຍໄດ້ບໍ?",
            },
        ],
    },
    {
        id: 6,
        korean: "숟가락",
        read: "suggarak",
        english: "spoon",
        lao: "ມີດ",
        speech: "n",
        emoji: "🥄",
        examples: [
            {
                id: 1,
                korean: "물약, 숟가락 그리고 작은 플라스틱 컵",
                read: "muryak, sutkkarak geurigo jageun peullaseutik keop",
                english: "liquid medicine, a spoon and a small plastic cup",
                lao: "ຢາ, ບ່ວງ ແລະ ຈອກຢາງນ້ອຍໆ",
            },
        ],
    },
    {
        id: 7,
        korean: "포크",
        read: "pokeu",
        english: "fork",
        lao: "ສ້ອມ",
        speech: "n",
        emoji: "🍴",
        examples: [
            {
                id: 1,
                korean: "접시 위에 있는 포크",
                read: "jeopssi wie inneun pokeu",
                english: "fork on a plate",
                lao: "ສ້ອມຢູ່ໃນຈານ",
            },
        ],
    },
    {
        id: 8,
        korean: "젓가락",
        read: "jeosgalag",
        english: "chopsticks",
        lao: "ໄມ້ທູ່",
        speech: "n",
        emoji: "🥢",
        examples: [
            {
                id: 1,
                korean: "나무 도마",
                read: "namu doma",
                english: "wooden cutting board",
                lao: "ຂຽນໄມ້",
            },
        ],
    },
    {
        id: 9,
        korean: "도마",
        read: "doma",
        english: "cutting board",
        lao: "ຂຽນ",
        speech: "n",
        examples: [
            {
                id: 1,
                korean: "나무 도마",
                read: "namu doma",
                english: "wooden cutting board",
                lao: "ຂຽນໄມ້",
            },
        ],
    },
    {
        id: 10,
        korean: "소금",
        read: "sogeum",
        english: "salt",
        lao: "ເກືອ",
        speech: "n",
        emoji: "🧂",
        examples: [
            {
                id: 1,
                korean: "나무 도마",
                read: "namu doma",
                english: "wooden cutting board",
                lao: "ຂຽນໄມ້",
            },
        ],
    },
    {
        id: 11,
        korean: "냉장고",
        read: "naeng jang go",
        english: "refrigerator",
        lao: "ເກືອ",
        speech: "n",
        emoji: "❄️",
        examples: [
            {
                id: 1,
                korean: "나무 도마",
                read: "namu doma",
                english: "wooden cutting board",
                lao: "ຂຽນໄມ້",
            },
        ],
    },
];
