import type { WordModel } from "~/models";

export const SPORTS: WordModel[] = [
    {
        id: 1,
        korean: "축구",
        read: "chuggu",
        english: "Football",
        lao: "ບານເຕະ",
        speech: "n",
        emoji: "⚽️",
        examples: [
            {
                id: 1,
                korean: "축구 경기",
                read: "chuggu gyeong-gi",
                english: "A football game",
                lao: "ເກມບານເຕະ",
            },
        ],
    },
    {
        id: 2,
        korean: "농구",
        read: "nong-gu",
        english: "Basketball",
        lao: "ບານບ້ວງ",
        speech: "n",
        emoji: "🏀",
        examples: [
            {
                id: 1,
                korean: "나는 대학에서 농구를 했다.",
                read: "naneun daehag-eseo nong-guleul haessda.",
                english: "I played basketball at college.",
                lao: "ຂ້ອຍຫຼິ້ນບານບ້ວງຢູ່ວິທະຍາໄລ.",
            },
        ],
    },
    {
        id: 3,
        korean: "배구",
        read: "baegu",
        english: "Volleyball",
        lao: "ບານສົ່ງ",
        speech: "n",
        emoji: "🏐",
        examples: [
            {
                id: 1,
                korean: "내 아들은 의사예요.",
                read: "nae adeul-eun uisayeyo.",
                english: "My son is a doctor.",
                lao: "ລູກຊາຍຂອງຂ້ອຍເປັນທ່ານຫມໍ.",
            },
        ],
    },
    {
        id: 4,
        korean: "야구",
        read: "yagu",
        english: "Baseball",
        lao: "ເບສບອນ",
        speech: "n",
        emoji: "⚾️",
        examples: [
            {
                id: 1,
                korean: "야구선수",
                read: "yaguseonsu",
                english: "A baseball player",
                lao: "ນັກກິລາເບສບອນ",
            },
        ],
    },
    {
        id: 5,
        korean: "배드민턴",
        read: "baedeuminteon",
        english: "Badminton",
        lao: "ກິລາຕີດອກປີກໄກ່",
        speech: "n",
        emoji: "🏸",
        examples: [
            {
                id: 1,
                korean: "내 아들은 선생님이야",
                read: "nae adeul-eun seonsaengnim-iya",
                english: "My son is a teacher",
                lao: "ລູກຊາຍຂອງຂ້ອຍເປັນຄູສອນ",
            },
        ],
    },
    {
        id: 6,
        korean: "테니스",
        read: "Tennis",
        english: "Tennis",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🎾",
        examples: [],
    },
    {
        id: 7,
        korean: "골프",
        read: "Golpeu",
        english: "Golf",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏌️‍♂️",
        examples: [],
    },
    {
        id: 8,
        korean: "수영",
        read: "Suyeong",
        english: "Swimming",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏊‍♀️",
        examples: [],
    },
    {
        id: 9,
        korean: "탁구",
        read: "Takgu",
        english: "Table Tennis",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏓",
        examples: [],
    },
    {
        id: 10,
        korean: "럭비",
        read: "Reokbi",
        english: "Rugby",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏉",
        examples: [],
    },
    {
        id: 11,
        korean: "복싱",
        read: "Boksing",
        english: "Boxing",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🥊",
        examples: [],
    },
    {
        id: 12,
        korean: "사이클링",
        read: "Saikeulling",
        english: "Cycling",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🚴‍♂️",
        examples: [],
    },
    {
        id: 13,
        korean: "스키",
        read: "Seuki",
        english: "Skiing",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "⛷",
        examples: [],
    },
    {
        id: 14,
        korean: "가라테",
        read: "Garate",
        english: "Karate",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 15,
        korean: "유도",
        read: "Yudo",
        english: "Judo",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 16,
        korean: "태권도",
        read: "Taegwondo",
        english: "Taekwondo",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 17,
        korean: "달리기",
        read: "Dalligi",
        english: "Running",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏃🏻‍♂️",
        examples: [],
    },
];
