import type { WordModel } from "~/models";

export const SPORTS: WordModel[] = [
    {
        id: 1,
        korean: "축구",
        read: "chuggu",
        english: "football",
        lao: "ບານເຕະ",
        speech: "n",
        emoji: "⚽️",
        examples: [
            {
                id: 1,
                korean: "축구 경기",
                read: "chuggu gyeong-gi",
                english: "A football game",
                lao: "ເກມບານເຕະ",
            },
        ],
    },
    {
        id: 2,
        korean: "농구",
        read: "nong-gu",
        english: "basketball",
        lao: "ບານບ້ວງ",
        speech: "n",
        emoji: "🏀",
        examples: [
            {
                id: 1,
                korean: "나는 대학에서 농구를 했다.",
                read: "naneun daehag-eseo nong-guleul haessda.",
                english: "I played basketball at college.",
                lao: "ຂ້ອຍຫຼິ້ນບານບ້ວງຢູ່ວິທະຍາໄລ.",
            },
        ],
    },
    {
        id: 3,
        korean: "배구",
        read: "baegu",
        english: "volleyball",
        lao: "ບານສົ່ງ",
        speech: "n",
        emoji: "🏐",
        examples: [
            {
                id: 1,
                korean: "내 아들은 의사예요.",
                read: "nae adeul-eun uisayeyo.",
                english: "My son is a doctor.",
                lao: "ລູກຊາຍຂອງຂ້ອຍເປັນທ່ານຫມໍ.",
            },
        ],
    },
    {
        id: 4,
        korean: "야구",
        read: "yagu",
        english: "baseball",
        lao: "ເບສບອນ",
        speech: "n",
        emoji: "⚾️",
        examples: [
            {
                id: 1,
                korean: "야구선수",
                read: "yaguseonsu",
                english: "A baseball player",
                lao: "ນັກກິລາເບສບອນ",
            },
        ],
    },
    {
        id: 5,
        korean: "배드민턴",
        read: "baedeuminteon",
        english: "badminton",
        lao: "ຕີດອກປີກໄກ່",
        speech: "n",
        emoji: "🏸",
        examples: [
            {
                id: 1,
                korean: "내 아들은 선생님이야",
                read: "nae adeul-eun seonsaengnim-iya",
                english: "My son is a teacher",
                lao: "ລູກຊາຍຂອງຂ້ອຍເປັນຄູສອນ",
            },
        ],
    },
    {
        id: 6,
        korean: "테니스",
        read: "tennis",
        english: "tennis",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🎾",
        examples: [],
    },
    {
        id: 7,
        korean: "골프",
        read: "golpeu",
        english: "golf",
        lao: "ກອ",
        speech: "n",
        emoji: "🏌️‍♂️",
        examples: [],
    },
    {
        id: 8,
        korean: "수영",
        read: "suyeong",
        english: "swimming",
        lao: "ລອຍນ",
        speech: "n",
        emoji: "🏊‍♀️",
        examples: [],
    },
    {
        id: 9,
        korean: "탁구",
        read: "takgu",
        english: "table tennis",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏓",
        examples: [],
    },
    {
        id: 10,
        korean: "럭비",
        read: "reokbi",
        english: "Rugby",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🏉",
        examples: [],
    },
    {
        id: 11,
        korean: "복싱",
        read: "boksing",
        english: "boxing",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "🥊",
        examples: [],
    },
    {
        id: 12,
        korean: "사이클링",
        read: "saikeulling",
        english: "cycling",
        lao: "ຂີ່ລົດຖີບ",
        speech: "n",
        emoji: "🚴‍♂️",
        examples: [],
    },
    {
        id: 13,
        korean: "스키",
        read: "seuki",
        english: "skiing",
        lao: "ຕຳຫຼວດ",
        speech: "n",
        emoji: "⛷",
        examples: [],
    },
    {
        id: 14,
        korean: "가라테",
        read: "garate",
        english: "Karate",
        lao: "ກິລາຄາລາເຕ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 15,
        korean: "유도",
        read: "yudo",
        english: "judo",
        lao: "ກິລາຢູໂດ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 16,
        korean: "태권도",
        read: "taegwondo",
        english: "taekwondo",
        lao: "ກິລາເທຄອນໂດ",
        speech: "n",
        emoji: "🥋",
        examples: [],
    },
    {
        id: 17,
        korean: "달리기",
        read: "dalligi",
        english: "running",
        lao: "ກິລາແລ່ນ",
        speech: "n",
        emoji: "🏃🏻‍♂️",
        examples: [],
    },
];
