import type { WordModel } from "~/models";

export const SPORTS: WordModel[] = [
    {
        id: 1,
        korean: "축구",
        read: "chuggu",
        english: "football",
        lao: "ບານເຕະ",
        speech: "n",
        emoji: "⚽️",
        examples: [
            {
                id: 1,
                korean: "축구 경기",
                read: "chuggu gyeonggi",
                english: "A football game",
                lao: "ເກມບານເຕະ",
            },
        ],
    },
    {
        id: 2,
        korean: "농구",
        read: "nonggu",
        english: "basketball",
        lao: "ບານບ້ວງ",
        speech: "n",
        emoji: "🏀",
        examples: [
            {
                id: 1,
                korean: "나는 대학에서 농구를 했다.",
                read: "naneun daehag-eseo nonggureul haessda",
                english: "I played basketball at college.",
                lao: "ຂ້ອຍຫຼິ້ນບານບ້ວງຢູ່ວິທະຍາໄລ.",
            },
        ],
    },
    {
        id: 3,
        korean: "배구",
        read: "baegu",
        english: "volleyball",
        lao: "ບານສົ່ງ",
        speech: "n",
        emoji: "🏐",
        examples: [
            {
                id: 1,
                korean: "배구는 재미있습니다.",
                read: "baeguneun jaemiisseumnida",
                english: "Volleyball is fun.",
                lao: "ກິລາບານສົ່ງເປັນກິລາທີ່ມ່ວນຊື່ນ.",
            },
        ],
    },
    {
        id: 4,
        korean: "야구",
        read: "yagu",
        english: "baseball",
        lao: "ເບສບອນ",
        speech: "n",
        emoji: "⚾️",
        examples: [
            {
                id: 1,
                korean: "야구선수",
                read: "yaguseonsu",
                english: "A baseball player",
                lao: "ນັກກິລາເບສບອນ",
            },
        ],
    },
    {
        id: 5,
        korean: "배드민턴",
        read: "baedeuminteon",
        english: "badminton",
        lao: "ຕີດອກປີກໄກ່",
        speech: "n",
        emoji: "🏸",
        examples: [
            {
                id: 1,
                korean: "배드민턴을 치자.",
                read: "baedeuminteoneul chija",
                english: "Let's play badminton.",
                lao: "ຕີດອກປີກໄກ່.",
            },
        ],
    },
    {
        id: 6,
        korean: "테니스",
        read: "tennis",
        english: "tennis",
        lao: "ເທນນິດ",
        speech: "n",
        emoji: "🎾",
        examples: [
            {
                id: 1,
                korean: "테니스 경기를 보러 가자.",
                read: "tennis gyeonggireul boreo gaja",
                english: "Let's go watch a tennis match.",
                lao: "ໄປເບິ່ງເທນນິດກັນເຖີດ.",
            },
        ],
    },
    {
        id: 7,
        korean: "골프",
        read: "golpeu",
        english: "golf",
        lao: "ກອຟ",
        speech: "n",
        emoji: "🏌️‍♂️",
        examples: [
            {
                id: 1,
                korean: "골프를 치러 가자.",
                read: "golpeureul chireo gaja",
                english: "Let's go play golf.",
                lao: "ໄປຕີກອຟກັນເຖີດ.",
            },
        ],
    },
    {
        id: 8,
        korean: "수영",
        read: "suyeong",
        english: "swimming",
        lao: "ລອຍນ້ຳ",
        speech: "n",
        emoji: "🏊‍♀️",
        examples: [
            {
                id: 1,
                korean: "수영을 배우고 싶어요.",
                read: "suyeongeul baeugo sipeoyo",
                english: "I want to learn swimming.",
                lao: "ຂ້ອຍຢາກຮຽນລອຍນ້ຳ.",
            },
        ],
    },
    {
        id: 9,
        korean: "탁구",
        read: "takgu",
        english: "table tennis",
        lao: "ປີ່ງປອງ",
        speech: "n",
        emoji: "🏓",
        examples: [
            {
                id: 1,
                korean: "탁구를 잘 치나요?",
                read: "takgureul jal chinayo",
                english: "Are you good at table tennis?",
                lao: "ເຈົ້າຕີປີ່ງປອງເກັ່ງບໍ?",
            },
        ],
    },
    {
        id: 10,
        korean: "럭비",
        read: "reokbi",
        english: "rugby",
        lao: "ລັກບີ",
        speech: "n",
        emoji: "🏉",
        examples: [
            {
                id: 1,
                korean: "럭비는 격렬한 스포츠입니다.",
                read: "reokbineun gyeongnyeolhan seupocheuimnida",
                english: "Rugby is a rough sport.",
                lao: "ລັກບີເປັນກິລາທີ່ຮຸນແຮງ.",
            },
        ],
    },
    {
        id: 11,
        korean: "복싱",
        read: "boksing",
        english: "boxing",
        lao: "ມວຍ",
        speech: "n",
        emoji: "🥊",
        examples: [
            {
                id: 1,
                korean: "복싱은 체력을 기르기 좋은 운동입니다.",
                read: "boksingeun cheryeokeul gireugi joeun undongimnida",
                english: "Boxing is a good exercise for building strength.",
                lao: "ມວຍເປັນການອອກກໍາລັງກາຍທີ່ດີສໍາລັບສ້າງແຮງທ່ານ.",
            },
        ],
    },
    {
        id: 12,
        korean: "사이클링",
        read: "saikeulling",
        english: "cycling",
        lao: "ຂີ່ລົດຖີບ",
        speech: "n",
        emoji: "🚴‍♂️",
        examples: [
            {
                id: 1,
                korean: "사이클링은 재미있고 건강에 좋습니다.",
                read: "saikeullingeun jaemiitgo geongange joseumnida",
                english: "Cycling is fun and good for health.",
                lao: "ການຂີ່ລົດຖີບເປັນກິລາທີ່ມ່ວນຊື່ນແລະດີຕໍ່ສຸຂະພາບ.",
            },
        ],
    },
    {
        id: 13,
        korean: "스키",
        read: "seuki",
        english: "skiing",
        lao: "ສະກີ",
        speech: "n",
        emoji: "⛷",
        examples: [
            {
                id: 1,
                korean: "겨울에 스키 타러 가자.",
                read: "gyeoure seuki tareo gaja",
                english: "Let's go skiing in the winter.",
                lao: "ໄປເລີ່ນສະກີກັນໃນລະດູຫນາວ.",
            },
        ],
    },
    {
        id: 14,
        korean: "가라테",
        read: "garate",
        english: "karate",
        lao: "ກາລາເຕ",
        speech: "n",
        emoji: "🥋",
        examples: [
            {
                id: 1,
                korean: "가라테는 재미있어요.",
                read: "garateneun jaemiisseoyo",
                english: "Karate is fun.",
                lao: "ກາລາເຕເປັນກິລາທີ່ມ່ວນຊື່ນ.",
            },
        ],
    },
    {
        id: 15,
        korean: "유도",
        read: "yudo",
        english: "judo",
        lao: "ຢູໂດ",
        speech: "n",
        emoji: "🥋",
        examples: [
            {
                id: 1,
                korean: "유도는 좋은 운동입니다.",
                read: "yudoneun joeun undongimnida",
                english: "Judo is a good sport.",
                lao: "ຢູໂດເປັນກິລາທີ່ດີ.",
            },
        ],
    },
    {
        id: 16,
        korean: "태권도",
        read: "taegwondo",
        english: "taekwondo",
        lao: "ເທຄອນໂດ",
        speech: "n",
        emoji: "🥋",
        examples: [
            {
                id: 1,
                korean: "태권도를 배우고 싶어요.",
                read: "taegwondeoreul baeugo sipeoyo",
                english: "I want to learn taekwondo.",
                lao: "ຂ້ອຍຢາກຮຽນເທຄອນໂດ.",
            },
        ],
    },
    {
        id: 17,
        korean: "달리기",
        read: "dalligi",
        english: "running",
        lao: "ການແລ່ນ",
        speech: "n",
        emoji: "🏃🏻‍♂️",
        examples: [
            {
                id: 1,
                korean: "달리기는 건강에 좋아요.",
                read: "dalligineun geongange joayo",
                english: "Running is good for health.",
                lao: "ການແລ່ນດີຕໍ່ສຸຂະພາບ.",
            },
        ],
    },
];
