import type { WordModel } from "~/models";

export const VEGETABLES: WordModel[] = [
    {
        id: 1,
        korean: "당근",
        read: "dang-geun",
        english: "carrot",
        lao: "ແຄລອດ",
    },
    {
        id: 2,
        korean: "감자",
        read: "gam-ja",
        english: "potato",
        lao: "ມັນຝຣັ່ງ",
    },
    {
        id: 3,
        korean: "양파",
        read: "yang-pa",
        english: "Onion",
        lao: "ຫອມບົ່ວ",
    },
    {
        id: 4,
        korean: "마늘",
        read: "ma-neul",
        english: "garlic",
        lao: "ຫອມວຽນ",
    },
    {
        id: 5,
        korean: "토마토",
        read: "to-ma-to",
        english: "tomato",
        lao: "ເຂືອ",
    },
    {
        id: 6,
        korean: "양배추",
        read: "yang-bae-chu",
        english: "cabbage",
        lao: "ກະລໍ້າປີ",
    },
    {
        id: 7,
        korean: "상추",
        read: "sang-chu",
        english: "lettuce",
        lao: "ຜັກສະຫຼຽງ",
    },
    {
        id: 8,
        korean: "시금치",
        read: "si-geum-chi",
        english: "spinach",
        lao: "ຜັກຂະຫນາດ",
    },
    {
        id: 9,
        korean: "브로콜리",
        read: "beu-ro-kol-li",
        english: "broccoli",
        lao: "ບຣອກໂຄລີ",
    },
    {
        id: 10,
        korean: "콜리플라워",
        read: "kol-li-peul-la-wo",
        english: "cauliflower",
        lao: "ດອກກະລໍ່າດອກ",
    },
    {
        id: 11,
        korean: "오이",
        read: "o-i",
        english: "cucumber",
        lao: "ແຕງ",
    },
    {
        id: 12,
        korean: "피망",
        read: "pi-mang",
        english: "bell pepper",
        lao: "ໝາກເພັດຫວານ",
    },
    {
        id: 13,
        korean: "청양고추",
        read: "cheong-yang-go-chu",
        english: "green pepper",
        lao: "ໝາກເພັດຂຽວ",
    },
    {
        id: 14,
        korean: "가지",
        read: "ga-ji",
        english: "eggplant",
        lao: "ມັງ",
    },
    {
        id: 15,
        korean: "애호박",
        read: "ae-ho-bak",
        english: "zucchini",
        lao: "ໝາກແຝນ",
    },
    {
        id: 16,
        korean: "호박",
        read: "ho-bak",
        english: "pumpkin",
        lao: "ໝາກອຶ",
    },
    {
        id: 17,
        korean: "고구마",
        read: "go-gu-ma",
        english: "sweet potato",
        lao: "ມັນໝາກລິ້ງ",
    },
    {
        id: 18,
        korean: "무",
        read: "mu",
        english: "radish",
        lao: "ປາກເທົາ",
    },
    {
        id: 19,
        korean: "비트",
        read: "bi-teu",
        english: "beet",
        lao: "ຜັກບີດ",
    },
    {
        id: 20,
        korean: "버섯",
        read: "beo-seot",
        english: "mushroom",
        lao: "ເຫັດ",
    },
    {
        id: 21,
        korean: "완두콩",
        read: "wan-du-kong",
        english: "peas",
        lao: "ເຖົ່າຖົ່ວອອກ",
    },
    {
        id: 22,
        korean: "옥수수",
        read: "ok-su-su",
        english: "Corn",
        lao: "ໝາກພວງ",
    },
    {
        id: 23,
        korean: "아스파라거스",
        read: "A-seu-pa-ra-geo-seu",
        english: "Asparagus",
        lao: "ໜໍ່ໄມ້ຝຣັ່ງ",
    },
    {
        id: 24,
        korean: "케일",
        read: "Ke-il",
        english: "Kale",
        lao: "ເຄວ",
    },
    {
        id: 25,
        korean: "셀러리",
        read: "Sel-leo-ri",
        english: "Celery",
        lao: "ຜັກກັກ",
    },
];
