import type { WordModel } from "~/models";

export const VEGETABLES: WordModel[] = [
    {
        id: 1,
        korean: "당근",
        read: "Dang-geun",
        english: "Carrot",
        lao: "ແຄລອດ",
    },
    {
        id: 2,
        korean: "감자",
        read: "Gam-ja",
        english: "Potato",
        lao: "ມັນຝຣັ່ງ",
    },
    {
        id: 3,
        korean: "양파",
        read: "Yang-pa",
        english: "Onion",
        lao: "ຫອມບົ່ວ",
    },
    {
        id: 4,
        korean: "마늘",
        read: "Ma-neul",
        english: "Garlic",
        lao: "ຫອມວຽນ",
    },
    {
        id: 5,
        korean: "토마토",
        read: "To-ma-to",
        english: "Tomato",
        lao: "ເຂືອ",
    },
    {
        id: 6,
        korean: "양배추",
        read: "Yang-bae-chu",
        english: "Cabbage",
        lao: "ກະລໍ້າປີ",
    },
    {
        id: 7,
        korean: "상추",
        read: "Sang-chu",
        english: "Lettuce",
        lao: "ຜັກສະຫຼຽງ",
    },
    {
        id: 8,
        korean: "시금치",
        read: "Si-geum-chi",
        english: "Spinach",
        lao: "ຜັກຂະຫນາດ",
    },
    {
        id: 9,
        korean: "브로콜리",
        read: "Beu-ro-kol-li",
        english: "Broccoli",
        lao: "ບຣອກໂຄລີ",
    },
    {
        id: 10,
        korean: "콜리플라워",
        read: "Kol-li-peul-la-wo",
        english: "Cauliflower",
        lao: "ດອກກະລໍ່າດອກ",
    },
    {
        id: 11,
        korean: "오이",
        read: "O-i",
        english: "Cucumber",
        lao: "ແຕງ",
    },
    {
        id: 12,
        korean: "피망",
        read: "Pi-mang",
        english: "Bell Pepper",
        lao: "ໝາກເພັດຫວານ",
    },
    {
        id: 13,
        korean: "청양고추",
        read: "Cheong-yang-go-chu",
        english: "Green Pepper",
        lao: "ໝາກເພັດຂຽວ",
    },
    {
        id: 14,
        korean: "가지",
        read: "Ga-ji",
        english: "Eggplant",
        lao: "ມັງ",
    },
    {
        id: 15,
        korean: "애호박",
        read: "Ae-ho-bak",
        english: "Zucchini",
        lao: "ໝາກແຝນ",
    },
    {
        id: 16,
        korean: "호박",
        read: "Ho-bak",
        english: "Pumpkin",
        lao: "ໝາກອຶ",
    },
    {
        id: 17,
        korean: "고구마",
        read: "Go-gu-ma",
        english: "Sweet Potato",
        lao: "ມັນໝາກລິ້ງ",
    },
    {
        id: 18,
        korean: "무",
        read: "Mu",
        english: "Radish",
        lao: "ປາກເທົາ",
    },
    {
        id: 19,
        korean: "비트",
        read: "Bi-teu",
        english: "Beet",
        lao: "ຜັກບີດ",
    },
    {
        id: 20,
        korean: "버섯",
        read: "Beo-seot",
        english: "Mushroom",
        lao: "ເຫັດ",
    },
    {
        id: 21,
        korean: "완두콩",
        read: "Wan-du-kong",
        english: "Peas",
        lao: "ເຖົ່າຖົ່ວອອກ",
    },
    {
        id: 22,
        korean: "옥수수",
        read: "Ok-su-su",
        english: "Corn",
        lao: "ໝາກພວງ",
    },
    {
        id: 23,
        korean: "아스파라거스",
        read: "A-seu-pa-ra-geo-seu",
        english: "Asparagus",
        lao: "ໜໍ່ໄມ້ຝຣັ່ງ",
    },
    {
        id: 24,
        korean: "케일",
        read: "Ke-il",
        english: "Kale",
        lao: "ເຄວ",
    },
    {
        id: 25,
        korean: "셀러리",
        read: "Sel-leo-ri",
        english: "Celery",
        lao: "ຜັກກັກ",
    },
];
