export const WORK_RELATED = [
    {
        korean: "기계, 성형",
        english: "machinery, molding",
        lao: "ເຄື່ອງຈັກ, ການປັ້ນ",
        slug: "machinery-molding",
        db: "machines",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "섬유, 봉제",
        english: "textile, sewing",
        lao: "ແຜ່ນແພ, ຕັດຫຍິບ",
        slug: "textile-sewing",
        db: "textiles",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "전자, 전기",
        english: "electronics, electricity",
        lao: "ເອເລັກໂຕຣນິກ, ໄຟຟ້າ",
        slug: "electric",
        db: "electric",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "음식 관련",
        english: "food related",
        lao: "​ກ່ຽວ​ຂ້ອງກັບ​ອາ​ຫານ​",
        slug: "food",
        db: "food",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "금속",
        english: "metal",
        lao: "ໂລ​ຫະ",
        slug: "metal",
        db: "metal",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "고무, 플라스틱",
        english: "Rubber, Plastic",
        lao: "ຢາງ, ຢາງພາດສະຕິກ",
        slug: "rubber-plastic",
        db: "plastic",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "펄프, 종이, 목재",
        english: "Pulp, Paper, Wood",
        lao: "ເນື້ອເຍື່ອເຈ້ຍ, ເຈ້ຍ, ໄມ້",
        slug: "pulp-paper-wood",
        db: "paper",
        icon: "Icons.menu_book_rounded",
    },
    {
        korean: "화학",
        english: "Chemical",
        lao: "ເຄມີ",
        slug: "chemical",
        db: "chemical",
        icon: "Icons.menu_book_rounded",
    },
];
