import type { PhraseModel } from "~/models";

export const TO_SAY_SORRY: PhraseModel[] = [
    {
        id: 1,
        korean: "다시는 안 그럴게.",
        read: "Dasineun an geureolge.",
        english: "I won't do it again.",
        lao: "ຂ້ອຍຈະບໍ່ເຮັດແບບນັ້ນອີກແລ້ວ.",
    },
    {
        id: 2,
        korean: "그걸 의미한 게 아냐.",
        read: "Geugeol uimihan ge anya.",
        english: "I didn't mean that.",
        lao: "ຂ້ອຍບໍ່ໄດ້ຫມາຍຄວາມວ່າແບບນັ້ນ.",
    },
    {
        id: 3,
        korean: "내 잘못이에요.",
        read: "Nae jalmosieyo.",
        english: "It's my fault.",
        lao: "ນັ້ນເປັນຄວາມຜິດຂອງຂ້ອຍ.",
    },
    {
        id: 4,
        korean: "죄송해요.",
        read: "Joesonghaeyo.",
        english: "I'm sorry.",
        lao: "ຂ້ອຍຂໍໂທດ.",
    },
    {
        id: 5,
        korean: "미안해요.",
        read: "Mianhaeyo.",
        english: "I'm sorry.",
        lao: "ຂ້ອຍຂໍໂທດ.",
    },
    {
        id: 6,
        korean: "용서해 주길 바라요.",
        read: "Yongseohae jugil barayo.",
        english: "I hope you forgive me.",
        lao: "ຂ້ອຍຫວັງວ່າເຈົ້າຈະໃຫ້ອະໄພ.",
    },
    {
        id: 7,
        korean: "내 책임이에요.",
        read: "Nae chaegimieyo.",
        english: "I take full responsibility.",
        lao: "ນັ້ນເປັນຄວາມຮັບຜິດຊອບຂອງຂ້ອຍເຕັມເຕັມ.",
    },
    {
        id: 8,
        korean: "사과하고 싶어요.",
        read: "Sagwahago sipeoyo.",
        english: "I would like to apologize.",
        lao: "ຂ້ອຍຢາກຂໍໂທດ.",
    },
    {
        id: 9,
        korean: "이 실수를 다시 하지 않도록 명심할게요.",
        read: "I silsureul dasi haji antorok myeongsimhalgeyo.",
        english: "I'll make sure not to make this mistake again.",
        lao: "ຂ້ອຍຈະຈື່ໄວ້ວ່າບໍ່ເຮັດຄວາມຜິດນີ້ອີກ.",
    },
    {
        id: 10,
        korean: "진심으로 사과드립니다.",
        read: "Jinsimeuro sagwadeurimnida.",
        english: "I sincerely apologize.",
        lao: "ຂ້ອຍຂໍໂທດຈາກໃຈ.",
    },
    {
        id: 11,
        korean: "제가 그걸 하지 말았어야 했어요.",
        read: "Jega geugeol haji marasseoya haesseoyo.",
        english: "I shouldn't have done it.",
        lao: "ຂ້ອຍບໍ່ຄວນເຮັດຢ່າງນັ້ນ.",
    },
    {
        id: 12,
        korean: "돈을 늦게 돌려줘서 미안해요.",
        read: "Doneul neutge dolryeojwoseo mianhaeyo.",
        english: "Sorry for giving your money back late.",
        lao: "ຂ້ອຍຂໍໂທດທີ່ຄືນເງິນມື້ໄດ້ຊ້າ.",
    },
    {
        id: 13,
        korean: "제발 화내지 마세요.",
        read: "Jebal hwanaeji maseyo.",
        english: "Please don’t be mad at me.",
        lao: "ກະລຸນາຢ່າໂກດຂ້ອຍ.",
    },
    {
        id: 14,
        korean: "늦어서 미안해요.",
        read: "Neujeoseo mianhaeyo.",
        english: "Sorry I’m late.",
        lao: "ຂ້ອຍຂໍໂທດທີ່ມາຊ້າ.",
    },
    {
        id: 15,
        korean: "못되게 군 것 사과할게요.",
        read: "Motdoege gun geot sagwahalgeyo.",
        english: "I apologize for being mean to you.",
        lao: "ຂ້ອຍຂໍໂທດທີ່ມີຄວາມເຮັດໄຮ້.",
    },
    {
        id: 16,
        korean: "이기적으로 굴어서 미안해요.",
        read: "Igijeogeuro gureoseo mianhaeyo.",
        english: "I’m sorry for being selfish.",
        lao: "ຂ້ອຍຂໍໂທດທີ່ເປັນຄົນເອົາແຕ່ໄດ້.",
    },
];
