import type { PhraseModel } from "~/models";

export const INTRODUCE_DAILY_ROUTINES: PhraseModel[] = [
    {
        id: 1,
        korean: "나는 양치질을 한다.",
        read: "naneun yangchijireul handa.",
        english: "I brush my teeth.",
        lao: "ຂ້ອຍແປງຟັນ.",
    },
    {
        id: 2,
        korean: "나는 문을 잠근다.",
        read: "naneun muneul jamgeunda.",
        english: "I lock the door.",
        lao: "ຂ້ອຍລັອກປະຕູ.",
    },
    {
        id: 3,
        korean: "나는 일하러 간다.",
        read: "naneun ilhareo ganda.",
        english: "I go to work.",
        lao: "ຂ້ອຍໄປເຮັດວຽກ.",
    },
    {
        id: 4,
        korean: "나는 내 스마트 폰으로 음악을 듣는다.",
        read: "naneun nae seumateu poneuro eumageul deudneunda.",
        english: "I listen to music on my smartphone.",
        lao: "ຂ້ອຍຟັງເພງບນມືຖືຂອງຂ້ອຍ.",
    },
    {
        id: 5,
        korean: "내 컴퓨터를 켠다.",
        read: "nae keompyuteoreul kyeonda.",
        english: "I turn on my computer.",
        lao: "ຂ້ອຍເປີດຄອມພິວເຕີຂອງຂ້ອຍ.",
    },
    {
        id: 6,
        korean: "내 이메일을 확인한다.",
        read: "nae imeireul hwaginhanda.",
        english: "I check my e-mail.",
        lao: "ຂ້ອຍກວດອີເມວຂອງຂ້ອຍ.",
    },
    {
        id: 7,
        korean: "나는 세탁을 한다.",
        read: "naneun setageul handa.",
        english: "I do laundry.",
        lao: "ຂ້ອຍຊັກເຄື່ອງ.",
    },
    {
        id: 8,
        korean: "나는 점심을 만든다.",
        read: "naneun jeomsimeul mandeunda.",
        english: "I make lunch.",
        lao: "ຂ້ອຍເຮັດອາຫານທ່ຽງ.",
    },
    {
        id: 9,
        korean: "나는 식료품을 산다.",
        read: "naneun singnyopumeul sanda.",
        english: "I buy groceries.",
        lao: "ຂ້ອຍຊື້ເຄື່ອງອາຫານ.",
    },
    {
        id: 10,
        korean: "나는 회의에 참석한다.",
        read: "naneun hoeuie chamseokanda.",
        english: "I attend a meeting.",
        lao: "ຂ້ອຍເຂົ້າຮ່ວມປະຊຸມ.",
    },
    {
        id: 11,
        korean: "나는 전화를 받는다.",
        read: "naneun jeonhwareul banneunda.",
        english: "I receive a phone call.",
        lao: "ຂ້ອຍຮັບສາຍໂທ.",
    },
    {
        id: 12,
        korean: "나는 새로운 영화를 본다.",
        read: "naneun saeroun yeonghwareul bonda.",
        english: "I watch a new movie.",
        lao: "ຂ້ອຍເບິ່ງຫນັງໃຫມ່.",
    },
    {
        id: 13,
        korean: "나는 뜨거운 목욕을 한다.",
        read: "naneun tteugeoun mogyogeul handa.",
        english: "I take a hot bath.",
        lao: "ຂ້ອຍອາບນໍ້າຮ້ອນ.",
    },
    {
        id: 14,
        korean: "나는 휴대폰 배터리를 충전한다.",
        read: "naneun hyudaepon baeteorireul chungjeonhanda.",
        english: "I charge the battery on my phone.",
        lao: "ຂ້ອຍຊາດແບດໂທລະສັບ.",
    },
    {
        id: 15,
        korean: "나는 내일을 계획한다.",
        read: "naneun naeireul gyehoekanda.",
        english: "I plan for tomorrow.",
        lao: "ຂ້ອຍວາງແຜນສຳລັບມື້ອື່ນ.",
    },
    {
        id: 16,
        korean: "나는 자정 무렵에 잔다.",
        read: "naneun jajeong muryeobe janda.",
        english: "I go to sleep around midnight.",
        lao: "ຂ້ອຍນອນປະມານເວລາເທິງຄືນ.",
    },
    {
        id: 17,
        korean: "나는 오전 7시에 일어난다.",
        read: "naneun ojeon 7sie ireonanda.",
        english: "I wake up at 7 a.m.",
        lao: "ຂ້ອຍຕື່ນເວລາ7ໂມງເຊົ້າ.",
    },
    {
        id: 18,
        korean: "나는 내 알람을 끈다.",
        read: "naneun nae allameul kkeunda.",
        english: "I turn off my alarm.",
        lao: "ຂ້ອຍປິດເມືອງປຸກ.",
    },
    {
        id: 19,
        korean: "나는 침대에서 일어난다.",
        read: "naneun chimdaeeseo ireonanda.",
        english: "I get out of bed.",

        lao: "ຂ້ອຍລຸກຈາກຕຽງ.",
    },
    {
        id: 20,
        korean: "아침을 먹는다.",
        read: "achimeul meongneunda.",
        english: "I eat breakfast.",
        lao: "ຂ້ອຍກິນເຂົ້າເຊົ້າ.",
    },
];
