import type { PhraseModel } from "~/models";

export const GREETING_PHRASES: PhraseModel[] = [
    {
        id: 1,
        korean: "안녕.",
        read: "Annyeong.",
        english: "Hello.",
        lao: "ສະບາຍດີ",
    },
    {
        id: 2,
        korean: "안녕",
        read: "annyeong",
        english: "Hi",
        lao: "ສະບາຍດີ",
    },
    {
        id: 3,
        korean: "좋은 아침이에요.",
        read: "Joeun achimieyo.",
        english: "Good morning.",
        lao: "ສະບາຍດີຕອນເຊົ້າ.",
    },
    {
        id: 4,
        korean: "안녕하세요.",
        read: "Annyeonghaseyo.",
        english: "Good afternoon.",
        lao: "ສະ​ບາຍ​ດີ​ຕອນ​ສວາຍ.",
    },
    {
        id: 5,
        korean: "안녕하세요.",
        read: "Annyeonghaseyo.",
        english: "Good evening.",
        lao: "ສະ​ບາຍ​ດີ​ຕອນ​ແລງ.",
    },
    {
        id: 5,
        korean: "안녕히 주무세요.",
        read: "Annyeonghi jumuseyo.",
        english: "Good night.",
        lao: "ຝັນດີ",
    },
    {
        id: 6,
        korean: "어떻게 지내세요?",
        read: "Eotteoke jinaeseyo?",
        english: "How are you?",
        lao: "ສະ​ບາຍ​ດີ​ບໍ?",
    },
    {
        id: 7,
        korean: "고마워요.",
        read: "Gomawoyo.",
        english: "Thank you",
        lao: "ຂອບໃຈ",
    },
    {
        id: 8,
        korean: "괜찮아요",
        read: "gwaenchanayo",
        english: "You're welcome",
        lao: "ດ້ວຍຄວາມຍີນດີ",
    },
    {
        id: 9,
        korean: "이름이 뭐예요?",
        read: "Ireumi mwoyeyo?",
        english: "What's your name?",
        lao: "ເຈົ້າ​ຊື່​ຫຍັງ?",
    },
    {
        id: 10,
        korean: "어디 출신이세요?",
        read: "Eodi chulsiniseyo?",
        english: "Where are you from?",
        lao: "ເຈົ້າ​ມາ​ຈາກ​ໃສ?",
    },
    {
        id: 11,
        korean: "아니요.",
        read: "Aniyo.",
        english: "No.",
        lao: "ບໍ່",
    },
    {
        id: 12,
        korean: "미안해요.",
        read: "Mianhaeyo.",
        english: "I'm sorry.",
        lao: "ຂ້ອຍຂໍໂທດ",
    },
    {
        id: 13,
        korean: "실례합니다.",
        read: "Sillyehamnida.",
        english: "Excuse me.",
        lao: "ຂໍ​ອະ​ໄພ.",
    },
    {
        id: 14,
        korean: "제발.",
        read: "Jebal.",
        english: "Please.",
        lao: "ກະລຸນາ",
    },
    {
        id: 15,
        korean: "만나서 반가워요.",
        read: "Mannaseo bangawoyo.",
        english: "Nice to meet you.",
        lao: "ຍິນ​ດີ​ທີ່​ໄດ້​ຮູ້​ຈັກ​ເຈົ້າ.",
    },
    {
        id: 16,
        korean: "잘 가요.",
        read: "Jal gayo.",
        english: "Goodbye.",
        lao: "ລາກ່ອນ",
    },
    {
        id: 17,
        korean: "대단히 감사합니다.",
        read: "Daedanhi gamsahamnida.",
        english: "Thank you very much.",
        lao: "ຂອບໃຈຫລາຍໆ",
    },
    {
        id: 18,
        korean: "저는 ...입니다.",
        read: "Jeoneun ...imnida.",
        english: "I'm (name).",
        lao: "ຂ້ອຍຊື່...",
    },
    {
        id: 19,
        korean: "괜찮아요.",
        read: "Gwaenchanayo.",
        english: "I'm fine.",
        lao: "ຂ້ອຍສະບາຍດີ",
    },
    {
        id: 20,
        korean: "앉아도 돼요?",
        read: "Anjado dwaeyo?",
        english: "May I sit here?",
        lao: "ຂ້ອຍຂໍນັ່ງບ່ອນນີ້ໄດ້ບໍ່?",
    },
    {
        id: 21,
        korean: "네",
        read: "ne",
        english: "Yes",
        lao: "ໂດຍ",
    },
    {
        id: 22,
        korean: "축하해요.",
        read: "Chukhahaeyo.",
        english: "Congratulations!",
        lao: "ຂໍສະແດງຄວາມຍິນດີ",
    },
];
