import type { PhraseModel } from "~/models";

export const INTRODUCE_SMALL_TALK: PhraseModel[] = [
    {
        id: 1,
        korean: "멋지네요.",
        read: "Meotjineyo.",
        english: "You look great!",
        lao: "ເຈົ້າເບິ່ງດີ!",
    },
    {
        id: 2,
        korean: "잘 지내고 있어요?",
        read: "Jal jinaego isseoyo?",
        english: "How are things?",
        lao: "ເປັນແນວໃດບ້າງ?",
    },
    {
        id: 3,
        korean: "이런 우연이!",
        read: "Ireon uyeoni!",
        english: "What a coincidence!",
        lao: "ເປັນຄວາມບັງເອີນ!",
    },
    {
        id: 4,
        korean: "잘됐네요!",
        read: "Jaldwaenneyo!",
        english: "That's great!",
        lao: "ນັ້ນດີຫລາຍ!",
    },
    {
        id: 5,
        korean: "잘했어요!",
        read: "Jalhaesseoyo!",
        english: "Good for you!",
        lao: "ດີຫລາຍ!",
    },
    {
        id: 6,
        korean: "잘 지내요?",
        read: "Jal jinaeyo?",
        english: "How are you?",
        lao: "ເຈົ້າເປັນແນວໃດ?",
    },
    {
        id: 7,
        korean: "모든 것이 잘 되고 있어요?",
        read: "Modeun geosi jal doego isseoyo?",
        english: "Is everything going fine?",
        lao: "ທຸກຢ່າງເປັນໄປດີບໍ?",
    },
    {
        id: 8,
        korean: "믿지 못할거야!",
        read: "Mitji motalgeoya!",
        english: "You won't believe this!",
        lao: "ເຈົ້າຈະບໍ່ເຊື່ອນີ້!",
    },
    {
        id: 9,
        korean: "당신을 한 동안 못 봤네요.",
        read: "Dangsineul han dongan mon bwanneyo.",
        english: "I haven't seen you for ages.",
        lao: "ຂ້ອຍບໍ່ໄດ້ເຫັນເຈົ້າດົນແລ້ວ.",
    },
    {
        id: 10,
        korean: "심하네요!",
        read: "Simhaneyo!",
        english: "That's terrible!",
        lao: "ນັ້ນແຍ່ຫລາຍ!",
    },
    {
        id: 11,
        korean: "이제 보내드려야 겠어요.",
        read: "Ije bonaedeuryeoya gesseoyo.",
        english: "I'd better let you go.",
        lao: "ຂ້ອຍຄວນໃຫ້ເຈົ້າໄປແລ້ວ.",
    },
    {
        id: 12,
        korean: "오늘 뉴스를 들었어요?",
        read: "Oneul nyuseureul deureosseoyo?",
        english: "Did you catch the news today?",
        lao: "ເຈົ້າໄດ້ຟັງຂ່າວມື້ນີ້ບໍ?",
    },
    {
        id: 13,
        korean: "날씨가 좋아요, 그렇죠?",
        read: "Nalssiga joayo, geureochyo?",
        english: "Nice day outside, isn't it?",
        lao: "ມື້ນີ້ອາກາດດີແມ່ນບໍ?",
    },
    {
        id: 14,
        korean: "오래 기다렸어요?",
        read: "Orae gidaryeosseoyo?",
        english: "Have you been waiting long?",
        lao: "ເຈົ້າຄອຍດົນແລ້ວບໍ?",
    },
    {
        id: 15,
        korean: "여기 있어줘서 좋아요.",
        read: "Yeogi isseojwoseo joayo.",
        english: "It's good to have you here!",
        lao: "ດີທີ່ເຈົ້າຢູ່ທີ່ນີ້!",
    },
    {
        id: 16,
        korean: "무슨일로 여기에 왔어요?",
        read: "Museunillo yeogie wasseoyo?",
        english: "What brings you here?",
        lao: "ຫຍັງເອົາເຈົ້າມາຢູ່ນີ້?",
    },
    {
        id: 17,
        korean: "물어봐도 괜찮아요?",
        read: "Mureobwado gwaenchanayo?",
        english: "Do you mind me asking?",
        lao: "ເຈົ້າຈະບໍ່ວ່າຫາກຂ້ອຍຖາມ?",
    },
    {
        id: 18,
        korean: "여기에 사세요?",
        read: "Yeogie saseyo?",
        english: "Are you from around here?",
        lao: "ເຈົ້າຢູ່ທີ່ນີ້ບໍ?",
    },
    {
        id: 19,
        korean: "이 문제에 당신의 도움이 필요해요.",
        read: "I munjee dangsinui doumi pillyohaeyo.",
        english: "I need your help with this matter.",
        lao: "ຂ້ອຍຕ້ອງການຄວາມຊ່ວຍເຫຼືອຂອງເຈົ້າກັບເລື່ອງນີ້.",
    },
    {
        id: 20,
        korean: "즐거운 시간 보내요!",
        read: "Jeulgeoun sigan bonaeyo!",
        english: "Have fun!",
        lao: "ໃຫ້ມ່ວນ!",
    },
];
