import type { PhraseModel } from "~/models";

export const LEARNING_A_LANGUAGE: PhraseModel[] = [
    {
        id: 1,
        korean: "저희 가족은 그 언어를 사용하는 곳에서 왔어요.",
        read: "Jeohui gajogeun geu eoneoreul sayonghaneun goseseo waseoyo.",
        english: "My family comes from a place where the language is spoken.",
        lao: "ຄອບຄົວຂອງຂ້ອຍມາຈາກສະຖານທີ່ທີ່ໃຊ້ພາສານີ້.",
    },
    {
        id: 2,
        korean: "저는 그 언어를 사용하는 사람들과 문화를 좋아해요.",
        read: "Jeoneun geu eoneoreul sayonghaneun saramdeulgwa munhwareul joahaeyo.",
        english: "I love the culture and the people who speak the language.",
        lao: "ຂ້ອຍມັກວັດທະນະທໍາແລະຄົນທີ່ໃຊ້ພາສານີ້.",
    },
    {
        id: 3,
        korean: "저는 그냥 언어 배우기를 좋아해요!",
        read: "Jeoneun geunyang eoneo baeugireul joahaeyo!",
        english: "I just love learning languages!",
        lao: "ຂ້ອຍມັກຮຽນພາສາ!",
    },
    {
        id: 4,
        korean: "그 언어는 제 일에 유용합니다.",
        read: "Geu eoneoneun je ire yuyonghamnida.",
        english: "The language is useful for my job.",
        lao: "ພາສານີ້ເປັນປະໂຫຍດສໍາລັບວຽກງານຂອງຂ້ອຍ.",
    },
    {
        id: 5,
        korean: "저는 그 언어를 사용하는 국가에 살고 있습니다.",
        read: "Jeoneun geu eoneoreul sayonghaneun gukgae salgo itseumnida.",
        english: "I live in a country that speaks the language.",
        lao: "ຂ້ອຍອາໄສຢູ່ປະເທດທີ່ໃຊ້ພາສານີ້.",
    },
    {
        id: 6,
        korean: "저는 마음을 열고 더 국제적이 되고 싶습니다.",
        read: "Jeoneun maeumeul yeolgo deo gukjejeogi doego sipseumnida.",
        english: "I want to open my mind and become more international.",
        lao: "ຂ້ອຍຕ້ອງການເປີດໃຈແລະກາຍເປັນສາກົນຫຼາຍຂຶ້ນ.",
    },
    {
        id: 7,
        korean: "저는 제가 가장 좋아하는 노래, 영화와 티비 쇼를 이해하고 싶어요.",
        read: "Jeoneun jega gajang joahaneun norae, yeonghwawa tibi syoreul ihaehago sipeoyo.",
        english: "I want to understand my favorite songs, movies and TV shows.",
        lao: "ຂ້ອຍຢາກເຂົ້າໃຈເພງ, ພາບຍນກັບລາຍການທີວີທີ່ຂ້ອຍມັກ.",
    },
    {
        id: 8,
        korean: "저는 여행을 좋아해요!",
        read: "Jeoneun yeohaengeul joahaeyo!",
        english: "I love traveling!",
        lao: "ຂ້ອຍມັກການເດີນທາງ!",
    },
    {
        id: 9,
        korean: "그것은 제 종교의 중요한 부분이에요.",
        read: "Geugeoseun je jonggyoui jungyohan bubuniyeyo.",
        english: "It's an important part of my religion.",
        lao: "ນັ້ນເປັນສ່ວນທີ່ສໍາຄັນຂອງສາສນາຂອງຂ້ອຍ.",
    },
    {
        id: 10,
        korean: "그것은 제 대학 공부의 일부입니다.",
        read: "Geugeoseun je daehak gongbuui ilbuimnida.",
        english: "It's part of my university studies.",
        lao: "ນັ້ນເປັນສ່ວນໜຶ່ງຂອງການຮຽນຂອງຂ້ອຍ.",
    },
    {
        id: 11,
        korean: "그것은 제 취미입니다.",
        read: "Geugeoseun je chwimiimnida.",
        english: "It's my hobby.",
        lao: "ນັ້ນເປັນງານອະມົກຂອງຂ້ອຍ.",
    },
    {
        id: 12,
        korean: "저는 그 언어를 사용하는 나라 옆에 삽니다.",
        read: "Jeoneun geu eoneoreul sayonghaneun nara yeope samnida.",
        english: "I live next to a country speaking that language.",
        lao: "ຂ້ອຍອາໄສຢູ່ຕິດກັບປະເທດທີ່ໃຊ້ພາສານັ້ນ.",
    },
    {
        id: 13,
        korean: "저는 누군가에게 잘 보이기 위해 그 언어를 배우고 있습니다.",
        read: "Jeoneun nugungaege jal boigi wihae geu eoneoreul baeugo itseumnida.",
        english: "I am learning the language to impress someone.",
        lao: "ຂ້ອຍກໍາລັງຮຽນພາສານີ້ເພື່ອເອົາໃຈຄົນໜຶ່ງ.",
    },
    {
        id: 14,
        korean: "저는 제 배우자의 가족과 그들의 언어로 말하고 싶습니다.",
        read: "Jeoneun je baeujaui gajokgwa geudeurui eoneoro malhago sipseumnida.",
        english: "I want to speak to my partner's family in their language.",
        lao: "ຂ້ອຍຢາກສື່ສານກັບຄອບຄົວຂອງຄູ່ຄອງເຂົາໃນພາສາຂອງເຂົາ.",
    },
    {
        id: 15,
        korean: "아름다운 언어예요!",
        read: "Areumdaun eoneoyeyo!",
        english: "It's a beautiful language!",
        lao: "ມັນເປັນພາສາທີ່ງົດງາມ!",
    },
];
