import type { PhraseModel } from "~/models";

export const A_TIME_TO_MEET: PhraseModel[] = [
    {
        id: 1,
        korean: "제니퍼, 저랑 저녁 식사 하실래요?",
        read: "Jenipeo, jeorang jeonyeok sigsa hasil-laeyo?",
        english: "Jennifer, would you like to have dinner with me?",
        lao: "ຈີນີເພີໂຣ, ຂ້າມີເບົາການອາຫານໄດ້ບໍ່?",
    },
    {
        id: 2,
        korean: "네. 좋겠어요. 언제 가실 건가요?",
        read: "Ne. Jokkesseoyo. Eonje gasil geongayo?",
        english: "Yes. That would be nice. When do you want to go?",
        lao: "ໂດຍກັບ. ມັນຈະມີບໍ່ແມ່ນໄດ້ບໍ່?",
    },
    {
        id: 3,
        korean: "오늘 괜찮으세요?",
        read: "Oneul gwaenchanh-euseyo?",
        english: "Is today OK?",
        lao: "ມື້ນີ້ດີຜິດເຊື້ອບໍ?",
    },
    {
        id: 4,
        korean: "미안해요, 오늘은 안 되요.",
        read: "Mianhaeyo, oneul-eun an doeyo.",
        english: "Sorry, I can’t go today.",
        lao: "ຂໍຂອບຖ້ວນ, ມື້ນີ້ບໍ່ໄດ້.",
    },
    {
        id: 5,
        korean: "내일 밤은 어때요?",
        read: "Naeil bam-eun eottaeyo?",
        english: "How about tomorrow night?",
        lao: "ວັນອື່ນນາມີແຫ່ງວັນ?",
    },
    {
        id: 6,
        korean: "좋아요. 몇 시에요?",
        read: "Joh-ayo. Myeot si-eyo?",
        english: "Ok. What time?",
        lao: "ດອກ. ເວລາແມ່ນແມ່ນ?",
    },
    {
        id: 7,
        korean: "9시는 괜찮으세요?",
        read: "9 shi-neun gwaenchanh-euseyo?",
        english: "Is 9:00 PM all right?",
        lao: "ແຖວນ້ອຍ 9:00 ໂມງດຽວ?",
    },
    {
        id: 8,
        korean: "너무 늦지 않을까요?",
        read: "Neomu neutji anhgil-kkayo?",
        english: "I think that’s too late.",
        lao: "ຂໍຂອບຄ່າງເຖິງເລີຍບໍ?",
    },
    {
        id: 9,
        korean: "6시는 어때요?",
        read: "6 shi-neun eottaeyo?",
        english: "Is 6:00 PM OK?",
        lao: "6:00 ໂມງດຽວບໍ?",
    },
    {
        id: 10,
        korean: "네, 좋아요. 어디로 가실래요?",
        read: "Ne, joh-ayo. Eodilo gasillal-laeyo?",
        english: "Yes, that’s good. Where would you like to go?",
        lao: "ໂດຍກັບ, ມັນຈະມີບໍ່ແມ່ນໄດ້ບໍ່?",
    },
    {
        id: 11,
        korean: "5번가에 있는 이탈리안 레스토랑으로요.",
        read: "5 beon-ga-e issneun Itallian reseutorang-euro-yo.",
        english: "The Italian restaurant on 5th street.",
        lao: "ຮ້ານອາກາດໃນເຖິງຮ່າງເຖິງເລີຍ.",
    },
    {
        id: 12,
        korean: "저, 그 레스토랑은 싫어해요. 그곳에 가고 싶지 않아요.",
        read: "Je, geu reseutorang-eun silh-eohaeyo. Geugos-e gago sipji anh-ayo.",
        english: "Oh, I don’t like that Restaurant. I don’t want to go there.",
        lao: "ໂຢ, ຮ້ານອາກາດວ່າທ່ານບໍວ່າຂ້ອຍຈະມີບໍ່ແມ່ນຈັດຫວານ.",
    },
    {
        id: 13,
        korean: "옆에 있는 한국 레스토랑은 어때요?",
        read: "Yeop-e issneun hangug reseutorang-eun eottaeyo?",
        english: "How about the Korean restaurant next to it?",
        lao: "ວ່າທ່ານບໍວ່າຮ້ານອາກາດວ່າທ່ານບໍວ່າໄດ້ບໍ?",
    },
    {
        id: 14,
        korean: "좋아요, 그 곳 좋아해요.",
        read: "Joh-ayo, geu got joh-ahaeyo.",
        english: "OK, I like that place.",
        lao: "ດອກ, ຂ້ອຍຈະມີບໍ່ແມ່ນຈັດຫວານ.",
    },
];
