import type { PhraseModel } from "~/models";

export const GREETING_CONVERSATIONS: PhraseModel[] = [
    {
        id: 1,
        korean: "안녕.",
        read: "Annyeong.",
        english: "Hello.",
        lao: "ສະບາຍດີ.",
    },
    {
        id: 2,
        korean: "안녕.",
        read: "Annyeong.",
        english: "Hi.",
        lao: "ສະບາຍດີ.",
    },
    {
        id: 3,
        korean: "어떻게 지내세요?",
        read: "Eotteoke jinaeseyo?",
        english: "How are you?",
        lao: "ສະບາຍດີບໍ?",
    },
    {
        id: 4,
        korean: "난 괜찮아. 어떻게 지내세요?",
        read: "Nan gwaenchana. Eotteoke jinaeseyo?",
        english: "I’m good. How are you?",
        lao: "ຂ້ອຍສະບາຍດີ. ສະບາຍດີບໍ?",
    },
    {
        id: 5,
        korean: "좋아요. 한국어를 하세요?",
        read: "Johayo. Hangugeoreul haseyo?",
        english: "Good. Do you speak Korean?",
        lao: "ດີ. ເຈົ້າເວົ້າພາສາເກົາຫຼີບໍ?",
    },
    {
        id: 6,
        korean: "조금요. 당신은 한국인인가요?",
        read: "Jogeumyo. Dangshineun hangugin-inga-yo?",
        english: "A little. Are you Korean?",
        lao: "ໜ້ອຍໜຶ່ງ. ເຈົ້າເປັນຄົນເກົາຫລີບໍ?",
    },
    {
        id: 7,
        korean: "네.",
        read: "Ne.",
        english: "Yes.",
        lao: "ແມ່ນແລ້ວ.",
    },
    {
        id: 8,
        korean: "어디에서 오셨어요?",
        read: "Eodieseo osyeosseoyo?",
        english: "Where are you from?",
        lao: "ເຈົ້າມາຈາກໃສ?",
    },
    {
        id: 9,
        korean: "저는 서울에서 왔어요.",
        read: "Jeoneun seouleseo wasseoyo.",
        english: "I’m from Seoul.",
        lao: "ຂ້ອຍມາຈາກກຸງໂຊລ.",
    },
    {
        id: 10,
        korean: "반갑습니다.",
        read: "Bangapseumnida.",
        english: "Nice to meet you.",
        lao: "ຍິນດີທີ່ໄດ້ຮູ້ຈັກເຈົ້າ.",
    },
    {
        id: 11,
        korean: "저도 반갑습니다.",
        read: "Jeodo bangapseumnida.",
        english: "Nice to meet you too.",
        lao: "ຍິນດີທີ່ໄດ້ພົບເຈົ້າຄືກັນ.",
    },
];
