import type { PhraseModel } from "~/models";

export const ORDERING_FOOD: PhraseModel[] = [
    {
        id: 1,
        korean: "안녕하세요.",
        read: "Annyeonghaseyo.",
        english: "Hello.",
        lao: "ສະບາຍດີ.",
    },
    {
        id: 2,
        korean: "안녕하세요. 오늘 저녁 식사를 주문하려고 하는데요.",
        read: "Annyeonghaseyo. Oneul jeonyeok siksa-reul jumunharyeogo hande.",
        english: "Hello. I'd like to order dinner for tonight.",
        lao: "ສະບາຍດີ. ມື້ນີ້ຂ້າພະເຈົ້າຈະສັ່ງອາຫານເຂົ້າໄປທີ່.",
    },
    {
        id: 3,
        korean: "그럼요. 주문하실 음식을 골라주세요.",
        read: "Geureumyo. Jumunhasil eumsigeul gollajuseyo.",
        english: "Sure. Please choose the dishes you'd like to order.",
        lao: "ກວ່າງາມ. ກະລຸນາເລືອກອາຫານທີ່ຈະສັ່ງ.",
    },
    {
        id: 4,
        korean: "제일 인기 있는 메뉴가 무엇인가요?",
        read: "Jeil ingi issneun menuga mueosingayo?",
        english: "What is the most popular item on the menu?",
        lao: "ອາຫານໃຫຍ່ຂອງເມນູທີ່ປະມານສະຫນາມບັນຫາ?",
    },
    {
        id: 5,
        korean: "저희 매장의 추천 메뉴는 스테이크입니다.",
        read: "Jeohui maejang-ui chucheon menuneun seuteikeuimnida.",
        english: "Our recommended dish is the steak.",
        lao: "ອາຫານທີ່ເມນູຂອງພວກເຮົາຂອງເມນູເປັນຂີ້ຂອງຊາດເຟັກ.",
    },
    {
        id: 6,
        korean: "그럼 저는 스테이크를 주문하겠습니다.",
        read: "Geureom jeoneun seuteikeureul jumunhagesseumnida.",
        english: "Then, I'll have the steak.",
        lao: "ອາຫານໃນການສັ່ງພວກເຮົາຂອງພວກເຮົາຈະມີຂີ້ຂອງຊາດເຟັກທີ່ຈະຈັດສັນນັ່ງ.",
    },
    {
        id: 7,
        korean: "스테이크는 어떤 익기로 드릴까요?",
        read: "Seuteikeuneun eotteon iggiro deurilkkayo?",
        english: "How would you like your steak cooked?",
        lao: "ຊາດເຟັກຈະມີຂີ້ຂອງຊາດເຟັກທີ່ກັບສັງຄົມເຂົ້າໄປທີ່?",
    },
    {
        id: 8,
        korean: "저는 미디움 레어로 주문하겠습니다.",
        read: "Jeoneun midieom reeoro jumunhagesseumnida.",
        english: "I'll have it medium rare.",
        lao: "ມື້ນີ້ຂ້າພະເຈົ້າຈະເຂົ້າໄປທີ່ແຕບອີກແຕ່ແດນໂດຍເອກາຍ.",
    },
    {
        id: 9,
        korean: "네, 알겠습니다. 기다리시겠어요.",
        read: "Ne, algesseumnida. Gidarisekkesseoyo.",
        english: "Sure, I understand. Please wait a moment.",
        lao: "ກວ່າຮູ້ຂອງພວກເຮົາຢູ່ພວກເຮົາຈະລົດໄປດ້ວຍທາງພາກ.",
    },
    {
        id: 10,
        korean: "음식이 나오면 또 부탁드릴게요.",
        read: "Eumsigi naomyeon tto butakdeurilgeyo.",
        english: "I'll ask for your help again when the food arrives.",
        lao: "ຂໍຂອບໃຈດີທີ່ເດີມທາງທີ່ມີອາຫານເມື່ອມາຫາຍ.",
    },
    {
        id: 11,
        korean: "무슨 음료를 드릴까요?",
        read: "Museun eumnyoreul deurilkkayo?",
        english: "What beverage would you like?",
        lao: "ດົນສົບສະຫມາຍສູ້ເຮືອງແລ້ວ?",
    },
    {
        id: 12,
        korean: "콜라 한 잔 주세요.",
        read: "Kolla han jan juseyo.",
        english: "Please give me a glass of cola.",
        lao: "ກະລຸນາສະຫມັກຂໍລົງກະລາສະກໍ.",
    },
    {
        id: 13,
        korean: "네, 곧 가져다 드리겠습니다.",
        read: "Ne, got gajyeoda deurigesseumnida.",
        english: "Sure, I'll bring it right away.",
        lao: "ກວດສອບຮັບຈຳໄວທີ່ຈະເລີ່ມໄປດ້ວຍ.",
    },
    {
        id: 14,
        korean: "음식과 음료가 준비되었습니다.",
        read: "Eumsik-gwa eumnyoga junbidoeeossseubnida.",
        english: "The food and beverage are ready.",
        lao: "ອາຫານດີຂາດກວດສອບຮັບ.",
    },
    {
        id: 15,
        korean: "즐거운 식사 되세요.",
        read: "Jeulgeoun siksa doeseyo.",
        english: "Enjoy your meal.",
        lao: "ກິນລົງທຶນອາຫານຂອງທ່ານ.",
    },
    {
        id: 16,
        korean: "감사합니다.",
        read: "Gamsahamnida.",
        english: "Thank you.",
        lao: "ຂອບໃຈ.",
    },
];
